-- =====================================================================
-- PQR public channel: structured requester contact fields
-- =====================================================================
-- Replaces the legacy "encode name/email/phone inside the description
-- text" workaround (which forced parseRequester() on every read) with
-- dedicated columns on support_tickets. All columns are nullable +
-- optional so legacy rows (pre-migration) and anonymous submissions
-- from the public storefront keep working without backfill.
--
-- NOTE: This file was originally generated by `prisma migrate dev`
-- alongside ~120 unrelated FK drops and ~61 index renames (drift
-- captured against a divergent DB state). Those operations were
-- removed — they belong to separate housekeeping migrations, not to
-- the PQR feature.
--
-- All statements are idempotent (IF NOT EXISTS) so re-running this
-- migration is safe in case Prisma retries after a partial failure.
-- =====================================================================

-- AlterTable
ALTER TABLE "support_tickets"
  ADD COLUMN IF NOT EXISTS "requester_first_name"    VARCHAR(100),
  ADD COLUMN IF NOT EXISTS "requester_last_name"     VARCHAR(100),
  ADD COLUMN IF NOT EXISTS "requester_email"         VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "requester_phone"         VARCHAR(50),
  ADD COLUMN IF NOT EXISTS "requester_document_type" VARCHAR(20),
  ADD COLUMN IF NOT EXISTS "requester_document_num"  VARCHAR(50);