FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install --legacy-peer-deps --force && \
    if [ "$(uname -m)" = "aarch64" ]; then \
        npm install --save-optional @rollup/rollup-linux-arm64-musl --force; \
    else \
        npm install --save-optional @rollup/rollup-linux-x64-musl --force; \
    fi
COPY . .
EXPOSE 4200
CMD ["npx", "ng", "serve", "--host", "0.0.0.0", "--poll", "5000"]
