FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npx prisma generate
# Opcional: Ejecutar migraciones si es necesario
# RUN npx prisma migrate deploy
EXPOSE 3000
CMD ["npm", "run", "start:dev"]
