import { View } from 'react-native';
import {
  ShoppingCart,
  KeyRound,
  Lock,
  Eye,
  EyeOff,
  ArrowLeft,
  User,
  UserCheck,
  UserPlus,
  Mail,
  Phone,
  Building2,
  Store,
  Package,
  Receipt,
  Warehouse,
  Users,
  FileText,
  Calculator,
  Wallet,
  BarChart3,
  Settings,
  Shield,
  Bot,
  Activity,
  CreditCard,
  Home,
  LogOut,
  Check,
  Search,
  Plus,
  Minus,
  PlusCircle,
  Trash2,
  X,
  ChevronRight,
  ChevronDown,
  Filter,
  Calendar,
  TrendingUp,
  TrendingDown,
  DollarSign,
  ClipboardList,
  AlertTriangle,
  Clock,
  Truck,
  RotateCcw,
  Ban,
  Tag,
  Barcode,
  Grid3x3,
  List,
  MoreVertical,
  Share,
  Printer,
  RefreshCw,
  Sliders,
  ShoppingBag,
  Edit2,
} from 'lucide-react-native';
import { colors } from '@/shared/theme/colors';

const iconMap: Record<string, typeof ShoppingCart> = {
  'shopping-cart': ShoppingCart,
  'key-round': KeyRound,
  lock: Lock,
  eye: Eye,
  'eye-off': EyeOff,
  'arrow-left': ArrowLeft,
  user: User,
  'user-check': UserCheck,
  'user-plus': UserPlus,
  mail: Mail,
  phone: Phone,
  building: Building2,
  store: Store,
  package: Package,
  receipt: Receipt,
  warehouse: Warehouse,
  users: Users,
  'file-text': FileText,
  calculator: Calculator,
  wallet: Wallet,
  'bar-chart': BarChart3,
  settings: Settings,
  shield: Shield,
  bot: Bot,
  activity: Activity,
  'credit-card': CreditCard,
  home: Home,
  logout: LogOut,
  check: Check,
  search: Search,
  plus: Plus,
  minus: Minus,
  'plus-circle': PlusCircle,
  trash: Trash2,
  x: X,
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
  filter: Filter,
  calendar: Calendar,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'dollar-sign': DollarSign,
  'clipboard-list': ClipboardList,
  'alert-triangle': AlertTriangle,
  clock: Clock,
  truck: Truck,
  'rotate-ccw': RotateCcw,
  ban: Ban,
  tag: Tag,
  barcode: Barcode,
  grid: Grid3x3,
  list: List,
  'more-vertical': MoreVertical,
  share: Share,
  printer: Printer,
  refresh: RefreshCw,
  sliders: Sliders,
  'shopping-bag': ShoppingBag,
  'edit-2': Edit2,
};

interface IconProps {
  name: string;
  size?: number;
  color?: string;
}

export function Icon({ name, size = 24, color = colors.text.primary }: IconProps) {
  const LucideIcon = iconMap[name];
  if (!LucideIcon) {
    return <View style={{ width: size, height: size }} />;
  }
  return <LucideIcon size={size} color={color} strokeWidth={2} />;
}
