import { View, StyleProp, ViewStyle } from 'react-native';
import {
  ShoppingCart,
  KeyRound,
  Lock,
  Eye,
  EyeOff,
  ArrowLeft,
  User,
  UserCog,
  UserCheck,
  UserPlus,
  Mail,
  MailCheck,
  Phone,
  Building2,
  Store,
  Package,
  Receipt,
  Warehouse,
  Users,
  FileText,
  Calculator,
  Wallet,
  BarChart3,
  Settings,
  Shield,
  Bot,
  Activity,
  CreditCard,
  Home,
  LogOut,
  Check,
  Search,
  Plus,
  Minus,
  PlusCircle,
  X,
  ChevronRight,
  ChevronDown,
  Filter,
  Calendar,
  TrendingUp,
  TrendingDown,
  DollarSign,
  ClipboardList,
  AlertTriangle,
  Clock,
  Truck,
  RotateCcw,
  Ban,
  Tag,
  Barcode,
  Grid3x3,
  List,
  MoreVertical,
  MoreHorizontal,
  Share,
  Printer,
  RefreshCw,
  Sliders,
  ShoppingBag,
  Edit2,
  Pencil,
  Hash,
  Layers,
  Image as LucideImage,
  Scale,
  FilePlus,
  Save,
  ChevronUp,
  Bell,
  HelpCircle,
  Upload,
  Maximize2,
  Minimize2,
  Info,
  Megaphone,
  ChartLine,
  BookOpen,
  Banknote,
  Link2,
  Circle,
  PackageCheck,
  PackagePlus,
  ScanLine,
  CheckSquare,
  Square,
  CheckCircle,
  XCircle,
  AlertCircle,
  BellRing,
  Flag,
  Star,
  Globe,
  Factory,
  Boxes,
  Tags,
  ScrollText,
  History,
  Archive,
  ShieldCheck,
  ShieldAlert,
  Network,
  Database,
  BookText,
  Landmark,
  Coins,
  CircleDollarSign,
  PackageSearch,
  PackageX,
  ListChecks,
  ListTree,
  ArrowLeftRight,
  IdCard,
  Briefcase,
  Send,
  Inbox,
  FileCheck,
  FileClock,
  Cog,
  Sparkles,
  Target,
  Award,
  BadgeCheck,
  BadgeAlert,
  Hourglass,
  CalendarClock,
  CalendarCheck,
  CalendarDays,
  Building,
  Map,
  Compass,
  Zap,
  Rocket,
  Server,
  Webhook,
  Power,
  LayoutGrid,
  Component,
  Download,
  ExternalLink,
  Copy,
  Languages,
  Code,
  Terminal,
  FileBarChart,
  FileSpreadsheet,
  GanttChart,
  PieChart,
  LineChart,
  BarChart4,
  Watch,
  Timer,
  Monitor,
  Smartphone,
  Tablet,
  KeySquare,
  LogIn,
  UserMinus,
  UserX,
  UsersRound,
  AtSign,
  Plug,
  GitBranch,
  GitMerge,
  ArchiveX,
  FileX,
  Telescope,
  Globe2,
  LockKeyhole,
  Unlock,
  ArrowRightLeft,
  IterationCcw,
  BookOpenCheck,
  Notebook,
  Library,
  Bookmark,
  PiggyBank,
  Vault,
  Gem,
  Gift,
  HandCoins,
  ShoppingBasket,
  Utensils,
  Coffee,
  Pizza,
  Soup,
  Apple,
  Carrot,
  Beef,
  Fish,
  Egg,
  Milk,
  Wine,
  Beer,
  Cake,
  Cookie,
  Candy,
  Croissant,
  Salad,
  Sandwich,
  Popcorn,
  GlassWater,
  CupSoda,
  Martini,
  IceCream,
  Banana,
  Bean,
  Grape,
  Cherry,
  Citrus,
  Microwave,
  CookingPot,
  UtensilsCrossed,
  Shirt,
  Glasses,
  Tractor,
  Construction,
  Hammer,
  Axe,
  Pickaxe,
  Drill,
  Wrench,
  Nut,
  Bolt,
  MemoryStick,
  HardDrive,
  CircuitBoard,
  Cable,
  Usb,
  Bluetooth,
  Wifi,
  Radio,
  Cast,
  Airplay,
  ScreenShare,
  Tv,
  Projector,
  Computer,
  Laptop,
  Mouse,
  Keyboard,
  Webcam,
  Mic,
  Headphones,
  Speaker,
  Volume,
  VolumeX,
  Music,
  Disc,
  Play,
  Pause,
  StopCircle,
  SkipBack,
  SkipForward,
  Camera,
  Aperture,
  Frame,
  Crop,
  Brush,
  Eraser,
  Palette,
  Pipette,
  DraftingCompass,
  Pen,
  Highlighter,
  Ruler,
  Scroll,
  Signature,
  Type,
  Shapes,
  SquareStack,
  Diamond,
  Triangle,
  Pentagon,
  Hexagon,
  Octagon,
  Spline,
  Text,
  TextCursor,
  WholeWord,
  WrapText,
  ListOrdered,
  ListPlus,
  ListMinus,
  ListTodo,
  ListFilter,
  ListMusic,
  Film,
  Captions,
  Subtitles,
  AudioLines,
  AudioWaveform,
  Podcast,
  Mailbox,
  SendHorizontal,
  SendToBack,
  BringToFront,
  ArrowDownUp,
  ArrowUpDown,
  MoveHorizontal,
  MoveVertical,
  MoveDiagonal2,
  MoveDiagonal,
  ChevronsLeftRight,
  ChevronsUpDown,
  Ellipsis,
  EllipsisVertical,
  Menu,
  PanelLeft,
  PanelRight,
  PanelTop,
  PanelBottom,
  PanelLeftClose,
  PanelRightClose,
  PanelTopClose,
  PanelBottomClose,
  PanelLeftOpen,
  PanelRightOpen,
  PanelTopOpen,
  PanelBottomOpen,
  Sidebar,
  SidebarClose,
  SidebarOpen,
  LayoutDashboard,
  LayoutTemplate,
  LayoutPanelLeft,
  LayoutPanelTop,
  LayoutList,
  Table,
  Table2,
  TableProperties,
  Sheet,
  Rows,
  Columns,
  Grid2x2,
  ChartArea,
  ChartBar,
  ChartBarBig,
  ChartColumn,
  ChartColumnBig,
  ChartPie,
  ChartScatter,
  ChartSpline,
  ChartLine as ChartLineRenamed,
  ChartNoAxesColumn,
  ChartNoAxesCombined,
  ChartGantt,
  Lightbulb,
  Sun,
  Moon,
  Cloud,
  CloudOff,
  CloudRain,
  Snowflake,
  Wind,
  Umbrella,
  Droplet,
  Droplets,
  Thermometer,
  Flame,
  Mountain,
  TreePine,
  Trees,
  Leaf,
  Flower,
  Sprout,
  Bug,
  Snail,
  Cat,
  Dog,
  Bird,
  PawPrint,
  Skull,
  Bone,
  Footprints,
  Accessibility,
  Bike,
  Car,
  Bus,
  Train,
  Plane,
  Ship,
  Anchor,
  Gamepad,
  Dices,
  Dice1,
  Dice2,
  Dice3,
  Dice4,
  Dice5,
  Dice6,
  Puzzle,
  Atom,
  Pill,
  Stethoscope,
  HeartPulse,
  Trash,
  MapPin,
  ArrowDownCircle,
  ArrowUpCircle,
  Repeat,
  CornerDownLeft,
  ShieldOff,
  CheckCircle2,
  PencilLine,
  Edit3,
  ArrowDown,
  ArrowUp,
  CircleSlash,
  Ban as BanIcon,
} from 'lucide-react-native';
import { colors } from '@/shared/theme/colors';

const iconMap: Record<string, typeof ShoppingCart> = {
  'shopping-cart': ShoppingCart,
  'key-round': KeyRound,
  lock: Lock,
  eye: Eye,
  'eye-off': EyeOff,
  'arrow-left': ArrowLeft,
  user: User,
  'user-cog': UserCog,
  'user-check': UserCheck,
  'user-plus': UserPlus,
  mail: Mail,
  'mail-check': MailCheck,
  'map-pin': MapPin,
  phone: Phone,
  building: Building2,
  store: Store,
  package: Package,
  receipt: Receipt,
  warehouse: Warehouse,
  users: Users,
  'file-text': FileText,
  calculator: Calculator,
  wallet: Wallet,
  'bar-chart': BarChart3,
  // lucide-react-native no tiene `BarChart3` (web-only); el visual es idéntico a
  // `ChartBar` (4 barras verticales). Mantenemos el nombre web `bar-chart-3`
  // en el iconMap para paridad con apps/frontend (lucide-react).
  'bar-chart-3': ChartBar,
  settings: Settings,
  shield: Shield,
  bot: Bot,
  activity: Activity,
  'credit-card': CreditCard,
  home: Home,
  logout: LogOut,
  check: Check,
  search: Search,
  plus: Plus,
  minus: Minus,
  'plus-circle': PlusCircle,
  x: X,
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
  filter: Filter,
  calendar: Calendar,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'dollar-sign': DollarSign,
  'clipboard-list': ClipboardList,
  'alert-triangle': AlertTriangle,
  clock: Clock,
  truck: Truck,
  'rotate-ccw': RotateCcw,
  ban: Ban,
  tag: Tag,
  barcode: Barcode,
  grid: Grid3x3,
  list: List,
  'more-vertical': MoreVertical,
  'more-horizontal': MoreHorizontal,
  share: Share,
  printer: Printer,
  refresh: RefreshCw,
  sliders: Sliders,
  'shopping-bag': ShoppingBag,
  'edit-2': Edit2,
  edit: Pencil,
  hash: Hash,
  'building-2': Building2,
  layers: Layers,
  image: LucideImage,
  scale: Scale,
  'file-plus': FilePlus,
  save: Save,
  'chevron-up': ChevronUp,
  bell: Bell,
  'help-circle': HelpCircle,
  upload: Upload,
  'maximize-2': Maximize2,
  'minimize-2': Minimize2,
  info: Info,
  megaphone: Megaphone,
  'chart-line': ChartLine,
  'book-open': BookOpen,
  banknote: Banknote,
  'link-2': Link2,
  circle: Circle,
  'package-check': PackageCheck,
  'package-plus': PackagePlus,
  'scan-line': ScanLine,
  'check-square': CheckSquare,
  square: Square,
  'check-circle': CheckCircle,
  'x-circle': XCircle,
  'alert-circle': AlertCircle,
  'bell-ring': BellRing,
  flag: Flag,
  star: Star,
  globe: Globe,
  factory: Factory,
  boxes: Boxes,
  tags: Tags,
  'scroll-text': ScrollText,
  history: History,
  archive: Archive,
  'shield-check': ShieldCheck,
  'shield-alert': ShieldAlert,
  network: Network,
  database: Database,
  'book-text': BookText,
  landmark: Landmark,
  coins: Coins,
  'circle-dollar-sign': CircleDollarSign,
  'package-search': PackageSearch,
  'package-x': PackageX,
  'list-checks': ListChecks,
  'list-tree': ListTree,
  'arrow-left-right': ArrowLeftRight,
  'arrow-right-left': ArrowRightLeft,
  'id-card': IdCard,
  briefcase: Briefcase,
  send: Send,
  inbox: Inbox,
  'file-check': FileCheck,
  'file-clock': FileClock,
  cog: Cog,
  sparkles: Sparkles,
  target: Target,
  award: Award,
  'badge-check': BadgeCheck,
  'badge-alert': BadgeAlert,
  hourglass: Hourglass,
  'calendar-clock': CalendarClock,
  'calendar-check': CalendarCheck,
  'calendar-days': CalendarDays,
  building2: Building,
  map: Map,
  compass: Compass,
  zap: Zap,
  rocket: Rocket,
  server: Server,
  webhook: Webhook,
  power: Power,
  'layout-grid': LayoutGrid,
  component: Component,
  download: Download,
  'external-link': ExternalLink,
  copy: Copy,
  languages: Languages,
  code: Code,
  terminal: Terminal,
  'file-bar-chart': FileBarChart,
  'file-spreadsheet': FileSpreadsheet,
  'gantt-chart': GanttChart,
  'pie-chart': PieChart,
  'line-chart': LineChart,
  'bar-chart-4': BarChart4,
  watch: Watch,
  timer: Timer,
  monitor: Monitor,
  smartphone: Smartphone,
  tablet: Tablet,
  'key-square': KeySquare,
  login: LogIn,
  'user-minus': UserMinus,
  'user-x': UserX,
  'users-round': UsersRound,
  'at-sign': AtSign,
  plug: Plug,
  'git-branch': GitBranch,
  'git-merge': GitMerge,
  'archive-x': ArchiveX,
  'file-x': FileX,
  telescope: Telescope,
  'globe-2': Globe2,
  'lock-keyhole': LockKeyhole,
  unlock: Unlock,
  'iteration-ccw': IterationCcw,
  'book-open-check': BookOpenCheck,
  notebook: Notebook,
  library: Library,
  bookmark: Bookmark,
  'piggy-bank': PiggyBank,
  vault: Vault,
  gem: Gem,
  gift: Gift,
  'hand-coins': HandCoins,
  'shopping-basket': ShoppingBasket,
  utensils: Utensils,
  coffee: Coffee,
  pizza: Pizza,
  soup: Soup,
  apple: Apple,
  carrot: Carrot,
  beef: Beef,
  fish: Fish,
  egg: Egg,
  milk: Milk,
  wine: Wine,
  beer: Beer,
  cake: Cake,
  cookie: Cookie,
  candy: Candy,
  croissant: Croissant,
  salad: Salad,
  sandwich: Sandwich,
  popcorn: Popcorn,
  'glass-water': GlassWater,
  'cup-soda': CupSoda,
  martini: Martini,
  'ice-cream': IceCream,
  banana: Banana,
  bean: Bean,
  grape: Grape,
  cherry: Cherry,
  citrus: Citrus,
  microwave: Microwave,
  'cooking-pot': CookingPot,
  'utensils-crossed': UtensilsCrossed,
  shirt: Shirt,
  glasses: Glasses,
  tractor: Tractor,
  construction: Construction,
  hammer: Hammer,
  axe: Axe,
  pickaxe: Pickaxe,
  drill: Drill,
  wrench: Wrench,
  nut: Nut,
  bolt: Bolt,
  'memory-stick': MemoryStick,
  'hard-drive': HardDrive,
  'circuit-board': CircuitBoard,
  cable: Cable,
  usb: Usb,
  bluetooth: Bluetooth,
  wifi: Wifi,
  radio: Radio,
  cast: Cast,
  airplay: Airplay,
  'screen-share': ScreenShare,
  tv: Tv,
  projector: Projector,
  computer: Computer,
  laptop: Laptop,
  mouse: Mouse,
  keyboard: Keyboard,
  webcam: Webcam,
  mic: Mic,
  headphones: Headphones,
  speaker: Speaker,
  volume: Volume,
  'volume-x': VolumeX,
  music: Music,
  disc: Disc,
  play: Play,
  pause: Pause,
  'stop-circle': StopCircle,
  'skip-back': SkipBack,
  'skip-forward': SkipForward,
  camera: Camera,
  aperture: Aperture,
  frame: Frame,
  crop: Crop,
  brush: Brush,
  eraser: Eraser,
  palette: Palette,
  pipette: Pipette,
  'drafting-compass': DraftingCompass,
  pen: Pen,
  pencil: Pencil,
  highlighter: Highlighter,
  ruler: Ruler,
  scroll: Scroll,
  signature: Signature,
  type: Type,
  shapes: Shapes,
  'square-stack': SquareStack,
  diamond: Diamond,
  triangle: Triangle,
  pentagon: Pentagon,
  hexagon: Hexagon,
  octagon: Octagon,
  spline: Spline,
  text: Text,
  'text-cursor': TextCursor,
  'whole-word': WholeWord,
  'wrap-text': WrapText,
  'list-ordered': ListOrdered,
  'list-plus': ListPlus,
  'list-minus': ListMinus,
  'list-todo': ListTodo,
  'list-filter': ListFilter,
  'list-music': ListMusic,
  film: Film,
  captions: Captions,
  subtitles: Subtitles,
  'audio-lines': AudioLines,
  'audio-waveform': AudioWaveform,
  podcast: Podcast,
  mailbox: Mailbox,
  'send-horizontal': SendHorizontal,
  'send-to-back': SendToBack,
  'bring-to-front': BringToFront,
  'arrow-down-up': ArrowDownUp,
  'arrow-up-down': ArrowUpDown,
  'move-horizontal': MoveHorizontal,
  'move-vertical': MoveVertical,
  'move-diagonal': MoveDiagonal,
  'move-diagonal-2': MoveDiagonal2,
  'chevrons-left-right': ChevronsLeftRight,
  'chevrons-up-down': ChevronsUpDown,
  ellipsis: Ellipsis,
  'ellipsis-vertical': EllipsisVertical,
  menu: Menu,
  'panel-left': PanelLeft,
  'panel-right': PanelRight,
  'panel-top': PanelTop,
  'panel-bottom': PanelBottom,
  'panel-left-close': PanelLeftClose,
  'panel-right-close': PanelRightClose,
  'panel-top-close': PanelTopClose,
  'panel-bottom-close': PanelBottomClose,
  'panel-left-open': PanelLeftOpen,
  'panel-right-open': PanelRightOpen,
  'panel-top-open': PanelTopOpen,
  'panel-bottom-open': PanelBottomOpen,
  sidebar: Sidebar,
  'sidebar-close': SidebarClose,
  'sidebar-open': SidebarOpen,
  'layout-dashboard': LayoutDashboard,
  'layout-template': LayoutTemplate,
  'layout-panel-left': LayoutPanelLeft,
  'layout-panel-top': LayoutPanelTop,
  'layout-list': LayoutList,
  table: Table,
  'table-2': Table2,
  'table-properties': TableProperties,
  sheet: Sheet,
  rows: Rows,
  columns: Columns,
  'grid-2x2': Grid2x2,
  'grid-3x3': Grid3x3,
  'chart-area': ChartArea,
  'chart-bar': ChartBar,
  'chart-bar-big': ChartBarBig,
  'chart-column': ChartColumn,
  'chart-column-big': ChartColumnBig,
  'chart-pie': ChartPie,
  'chart-scatter': ChartScatter,
  'chart-spline': ChartSpline,
  'chart-no-axes-column': ChartNoAxesColumn,
  'chart-no-axes-combined': ChartNoAxesCombined,
  'chart-gantt': ChartGantt,
  lightbulb: Lightbulb,
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  'cloud-off': CloudOff,
  'cloud-rain': CloudRain,
  snowflake: Snowflake,
  wind: Wind,
  umbrella: Umbrella,
  droplet: Droplet,
  droplets: Droplets,
  thermometer: Thermometer,
  flame: Flame,
  mountain: Mountain,
  'tree-pine': TreePine,
  trees: Trees,
  leaf: Leaf,
  flower: Flower,
  sprout: Sprout,
  bug: Bug,
  snail: Snail,
  cat: Cat,
  dog: Dog,
  bird: Bird,
  'paw-print': PawPrint,
  skull: Skull,
  bone: Bone,
  footprints: Footprints,
  accessibility: Accessibility,
  bike: Bike,
  car: Car,
  bus: Bus,
  train: Train,
  plane: Plane,
  ship: Ship,
  anchor: Anchor,
  gamepad: Gamepad,
  dices: Dices,
  'dice-1': Dice1,
  'dice-2': Dice2,
  'dice-3': Dice3,
  'dice-4': Dice4,
  'dice-5': Dice5,
  'dice-6': Dice6,
  puzzle: Puzzle,
  atom: Atom,
  pill: Pill,
  stethoscope: Stethoscope,
  'heart-pulse': HeartPulse,
  'mic-2': Mic,
  'volume-2': Volume,
  'trash-2': Trash,
  'arrow-down-circle': ArrowDownCircle,
  'arrow-up-circle': ArrowUpCircle,
  'arrow-down': ArrowDown,
  'arrow-up': ArrowUp,
  repeat: Repeat,
  'corner-down-left': CornerDownLeft,
  'shield-off': ShieldOff,
  'x-circle': XCircle,
  'check-circle-2': CheckCircle2,
  'pencil-line': PencilLine,
  'edit-3': Edit3,
  'circle-slash': CircleSlash,
  'ban-solid': BanIcon,
};

interface IconProps {
  name: string;
  size?: number;
  color?: string;
  strokeWidth?: number;
  style?: StyleProp<ViewStyle>;
}

export type IconName = keyof typeof iconMap;

export function Icon({
  name,
  size = 24,
  color = colors.text.primary,
  strokeWidth = 2,
  style,
}: IconProps) {
  const LucideIcon = iconMap[name];
  if (!LucideIcon) {
    return <View style={[{ width: size, height: size }, style]} />;
  }
  return <LucideIcon size={size} color={color} strokeWidth={strokeWidth} style={style} />;
}
