import { DianEventCode } from '../constants/dian-endpoints';
import {
  DianEventDetails,
  DianEventParty,
} from '../xml/ubl-application-response.builder';

/**
 * Request to register a RADIAN document event (Res. 000085/2022) against an
 * already-accepted electronic document.
 *
 * The caller owns the business decisions (which document, which code, which
 * consecutive); the provider owns the transport (CUDE, XML, signature, ZIP,
 * SOAP, audit trail).
 */
export interface DianDocumentEventRequest {
  event_code: DianEventCode;
  /**
   * "Tipo de operación" (numeral 14.1.2) that lands in `cbc:CustomizationID`.
   * Required for events with more than one operation type; the provider falls back
   * to the event code, which is what the annex uses for single-operation events.
   */
  operation_code?: string;
  /** Extra blocks the 035–051 family carries (endorsee, amounts, mandate dates). */
  details?: DianEventDetails;
  /** Event consecutive assigned by the caller — `cbc:ID`, unique per store. */
  event_number: string;
  /**
   * Which side of the REFERENCED document generates this event.
   *
   * RADIAN splits the family: 030/031/032/033 are generated by the adquiriente,
   * 034 (aceptación tácita) by the emisor once the 3 business days lapse. The
   * provider only knows its own identity, so the caller states the role and the
   * provider maps it onto SenderParty/ReceiverParty.
   */
  generated_by: 'issuer' | 'customer';
  /** Document number of the referenced invoice, e.g. `SETP990000001`. */
  referenced_document_number: string;
  /** CUFE of the referenced invoice. */
  referenced_document_key: string;
  /** Issue date of the referenced invoice, `YYYY-MM-DD`. */
  referenced_document_date: string;
  /** `cbc:DocumentTypeCode` of the referenced document; defaults to '01'. */
  referenced_document_type_code?: string;
  /** The adquiriente of the referenced invoice. */
  customer: DianEventParty;
  /** Supplier/issuer on a received supplier invoice. Required only by buyer-event adapters. */
  referenced_issuer?: DianEventParty;
  /** Event issue date, `YYYY-MM-DD`. */
  issue_date: string;
  /** Event issue time with offset. Derived from the store timezone when absent. */
  issue_time?: string;
  /** Justification. RADIAN expects one on a reclamo (031). */
  description?: string;
}

/** Exact fiscal DIAN configuration selected by the caller for a buyer event. */
export interface DianEventConfigurationSelection {
  configuration_id: number;
  accounting_entity_id: number;
  /** Validated operational store for organization-scope received-document flows. */
  store_id?: number | null;
}

export interface DianDocumentEventResult {
  success: boolean;
  event_code: DianEventCode;
  /**
   * Configuration that signed and transmitted the event. Surfaced so the caller
   * persists it without re-resolving the fiscal scope a second time.
   */
  dian_configuration_id: number;
  /** CUDE of the ApplicationResponse we transmitted. */
  cude: string;
  /** Key DIAN echoed back, when it echoed one. */
  tracking_id?: string;
  status_code?: string;
  message?: string;
  request_xml: string;
  response_xml?: string;
  errors: { code?: string; message: string }[];
}

/**
 * Backend-internal JSON-safe snapshot of a signed event, before any DIAN network
 * call. Callers preparing received-document events must restrict them to buyer
 * event codes and roles.
 */
export interface DianPreparedDocumentEvent {
  event_code: DianEventCode;
  event_number: string;
  dian_configuration_id: number;
  accounting_entity_id: number;
  /** Store used to resolve an organization-scoped fiscal entity, when applicable. */
  store_id?: number | null;
  environment: 'test' | 'production';
  cude: string;
  signed_xml: string;
  signed_xml_sha256: string;
  xml_filename: string;
  zip_filename: string;
  software_id: string;
  certificate_s3_key: string | null;
  certificate_kms_key_id: string | null;
  certificate_fingerprint?: string | null;
}

export interface DianPreparedEventTransmissionResult extends DianDocumentEventResult {
  delivery_status: 'accepted' | 'rejected' | 'unknown';
}
