import { ReportCategory, ReportCategoryId, ReportDefinition, ReportType } from '../interfaces/report.interface';

export const REPORT_CATEGORIES: ReportCategory[] = [
  { id: 'overview', label: 'Resumen', description: 'Reporte general consolidado del negocio', icon: 'layout-dashboard', color: 'var(--color-primary)' },
  { id: 'sales', label: 'Ventas', description: 'Reportes de ventas y facturacion', icon: 'shopping-cart', color: 'var(--color-primary)' },
  { id: 'inventory', label: 'Inventario', description: 'Reportes de stock y movimientos', icon: 'warehouse', color: 'var(--color-warning)' },
  { id: 'products', label: 'Productos', description: 'Reportes de rendimiento y rentabilidad', icon: 'package', color: 'var(--color-accent)' },
  { id: 'customers', label: 'Clientes', description: 'Reportes de cartera y cuentas por cobrar', icon: 'users', color: 'var(--color-info)' },
  { id: 'purchases', label: 'Compras', description: 'Reportes de ordenes de compra y proveedores', icon: 'truck', color: 'var(--color-warning)' },
  { id: 'reviews', label: 'Reseñas', description: 'Reportes de reseñas y satisfaccion de clientes', icon: 'star', color: 'var(--color-accent)' },
  { id: 'financial', label: 'Financiero', description: 'Reportes de gastos, perdidas y ganancias, caja y cuentas por pagar', icon: 'wallet', color: 'var(--color-destructive)' },
  { id: 'accounting', label: 'Contabilidad', description: 'Reportes contables: balance de prueba, balance general, libro mayor e impuestos', icon: 'scale', color: 'var(--color-info)' },
  { id: 'payroll', label: 'Nomina', description: 'Reportes de nomina, empleados y provisiones laborales', icon: 'banknote', color: 'var(--color-success)' },
];

export const REPORT_DEFINITIONS: ReportDefinition[] = [
  // ─── RESUMEN (1) ─────────────────────────────────────────────────────────────────

  {
    id: 'overview-summary',
    category: 'overview',
    title: 'Resumen General',
    description: 'Vista consolidada de ventas, inventario y clientes',
    detailedDescription: 'Reporte general que consolida las metricas principales del negocio: ventas totales, estado de inventario, clientes activos y indicadores clave de rendimiento.',
    icon: 'layout-dashboard',
    route: '/admin/reports/overview/overview-summary',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'summary' as ReportType,
    summaryLayout: {
      fields: [
        { key: 'total_income', label: 'Ingresos Totales', type: 'currency' },
        { key: 'total_expenses', label: 'Gastos Totales', type: 'currency' },
        { key: 'net_profit', label: 'Ganancia Neta', type: 'currency' },
        { key: 'total_taxes', label: 'Impuestos', type: 'currency' },
        { key: 'income_growth', label: 'Crecimiento Ingresos', type: 'percentage' },
        { key: 'net_profit_growth', label: 'Crecimiento Ganancia', type: 'percentage' },
      ],
    },
    columns: [],
    exportFilename: 'resumen-general',
    stats: [
      { key: 'total_income', label: 'Ingresos Totales', type: 'currency', icon: 'dollar-sign' },
      { key: 'total_expenses', label: 'Gastos Totales', type: 'currency', icon: 'trending-down' },
      { key: 'net_profit', label: 'Ganancia Neta', type: 'currency', icon: 'trending-up' },
      { key: 'total_taxes', label: 'Impuestos', type: 'currency', icon: 'percent' },
    ],
    dataEndpoint: 'store/analytics/overview/summary',
  },

  // ─── COMPRAS (2) ─────────────────────────────────────────────────────────────────

  {
    id: 'purchase-summary',
    category: 'purchases',
    title: 'Resumen de Compras',
    description: 'Totales de ordenes de compra y proveedores del periodo',
    detailedDescription: 'Reporte consolidado de todas las ordenes de compra realizadas, incluyendo total comprado, cantidad de ordenes, proveedores principales y comparativa con periodos anteriores.',
    icon: 'truck',
    route: '/admin/reports/purchases/purchase-summary',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'summary' as ReportType,
    summaryLayout: {
      fields: [
        { key: 'total_spent', label: 'Total Compras', type: 'currency' },
        { key: 'total_orders', label: 'Total Ordenes', type: 'number' },
        { key: 'completed_orders', label: 'Completadas', type: 'number' },
        { key: 'average_order_value', label: 'Ticket Promedio', type: 'currency' },
      ],
    },
    columns: [],
    exportFilename: 'resumen-compras',
    stats: [
      { key: 'total_spent', label: 'Total Compras', type: 'currency', icon: 'dollar-sign' },
      { key: 'total_orders', label: 'Ordenes', type: 'number', icon: 'file-text' },
      { key: 'completed_orders', label: 'Completadas', type: 'number', icon: 'check-circle' },
      { key: 'average_order_value', label: 'Ticket Promedio', type: 'currency', icon: 'calculator' },
    ],
    dataEndpoint: 'store/analytics/purchases/summary',
  },
  {
    id: 'purchase-by-supplier',
    category: 'purchases',
    title: 'Por Proveedor',
    description: 'Desglose de compras agrupadas por proveedor',
    detailedDescription: 'Analisis detallado de las compras realizadas a cada proveedor, mostrando volumen, frecuencia y montos para evaluar relaciones comerciales.',
    icon: 'building-2',
    route: '/admin/reports/purchases/purchase-by-supplier',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    columns: [
      { key: 'supplier_name', header: 'Proveedor', type: 'text' },
      { key: 'order_count', header: 'Ordenes', type: 'number', footer: 'sum' },
      { key: 'total_spent', header: 'Total Comprado', type: 'currency', footer: 'sum' },
      { key: 'pending_orders', header: 'Pendientes', type: 'number' },
      { key: 'last_order_date', header: 'Ultima Orden', type: 'date' },
    ],
    exportFilename: 'compras-por-proveedor',
    stats: [
      { key: 'order_count', label: 'Total Ordenes', type: 'number', icon: 'file-text' },
      { key: 'total_spent', label: 'Total Comprado', type: 'currency', icon: 'dollar-sign' },
      { key: 'pending_orders', label: 'Pendientes', type: 'number', icon: 'clock' },
      { key: '_count', label: 'Proveedores', type: 'number', icon: 'building-2' },
    ],
    dataEndpoint: 'store/analytics/purchases/by-supplier',
  },

  // ─── RESEÑAS (1) ──────────────────────────────────────────────────────────────────

  {
    id: 'reviews-summary',
    category: 'reviews',
    title: 'Resumen de Reseñas',
    description: 'Calificacion promedio y distribucion de reseñas',
    detailedDescription: 'Reporte consolidado de las reseñas recibidas, incluyendo calificacion promedio, distribucion por estrellas, productos mejor valorados y tendencias de satisfaccion.',
    icon: 'star',
    route: '/admin/reports/reviews/reviews-summary',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'summary' as ReportType,
    summaryLayout: {
      fields: [
        { key: 'average_rating', label: 'Calificacion Promedio', type: 'number' },
        { key: 'total_reviews', label: 'Total Reseñas', type: 'number' },
        { key: 'approved_reviews', label: 'Aprobadas', type: 'number' },
        { key: 'total_helpful_votes', label: 'Votos Utiles', type: 'number' },
      ],
    },
    columns: [],
    exportFilename: 'resumen-resenas',
    stats: [
      { key: 'average_rating', label: 'Calificacion Promedio', type: 'number', icon: 'star' },
      { key: 'total_reviews', label: 'Total Reseñas', type: 'number', icon: 'message-square' },
      { key: 'approved_reviews', label: 'Aprobadas', type: 'number', icon: 'award' },
      { key: 'total_helpful_votes', label: 'Votos Utiles', type: 'number', icon: 'thumbs-up' },
    ],
    dataEndpoint: 'store/analytics/reviews/summary',
  },

  // ─── VENTAS (6) ───────────────────────────────────────────────────────────────

  {
    id: 'sales-summary',
    category: 'sales',
    title: 'Resumen de Ventas',
    description: 'Totales de ventas, promedios y ticket promedio del periodo',
    detailedDescription:
      'Visualiza un resumen completo de las ventas del periodo seleccionado, incluyendo total facturado, cantidad de ordenes, ticket promedio, descuentos aplicados y comparativa con periodo anterior.',
    icon: 'bar-chart-3',
    route: '/admin/reports/sales/sales-summary',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'summary' as ReportType,
    summaryLayout: {
      fields: [
        { key: 'total_revenue', label: 'Ventas Totales', type: 'currency' },
        { key: 'total_orders', label: 'Total Pedidos', type: 'number' },
        { key: 'average_order_value', label: 'Ticket Promedio', type: 'currency' },
        { key: 'total_units_sold', label: 'Productos Vendidos', type: 'number' },
        { key: 'total_customers', label: 'Clientes Unicos', type: 'number' },
        { key: 'revenue_growth', label: 'Crecimiento Ingresos', type: 'percentage' },
        { key: 'orders_growth', label: 'Crecimiento Ordenes', type: 'percentage' },
      ],
    },
    columns: [
      { key: 'total_revenue', header: 'Ventas Totales', type: 'currency' },
      { key: 'total_orders', header: 'Total Pedidos', type: 'number' },
      { key: 'average_order_value', header: 'Ticket Promedio', type: 'currency' },
      { key: 'total_units_sold', header: 'Productos Vendidos', type: 'number' },
      { key: 'total_customers', header: 'Clientes', type: 'number' },
      { key: 'revenue_growth', header: 'Crecimiento', type: 'percentage' },
      { key: 'orders_growth', header: 'Crec. Ordenes', type: 'percentage' },
    ],
    exportFilename: 'sales_summary',
    stats: [
      { key: 'total_revenue', label: 'Ventas Totales', type: 'currency', icon: 'dollar-sign' },
      { key: 'total_orders', label: 'Total Pedidos', type: 'number', icon: 'shopping-cart' },
      { key: 'average_order_value', label: 'Ticket Promedio', type: 'currency', icon: 'calculator' },
      { key: 'total_units_sold', label: 'Productos Vendidos', type: 'number', icon: 'package' },
    ],
    dataEndpoint: 'store/analytics/sales/summary',
    exportEndpoint: 'store/analytics/sales/export',
  },

  {
    id: 'sales-by-product',
    category: 'sales',
    title: 'Por Producto',
    description: 'Ranking de productos vendidos con cantidades y montos',
    detailedDescription:
      'Identifica tus productos estrella con un ranking detallado por cantidad vendida e ingreso generado. Incluye margen de ganancia por producto.',
    icon: 'package-search',
    route: '/admin/reports/sales/sales-by-product',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'product_id',
    columns: [
      { key: 'product_name', header: 'Producto', type: 'text' },
      { key: 'units_sold', header: 'Cantidad Vendida', type: 'number', footer: 'sum' },
      { key: 'revenue', header: 'Ingreso Total', type: 'currency', footer: 'sum' },
      { key: 'average_price', header: 'Precio Promedio', type: 'currency', footer: 'average' },
      { key: 'profit_margin', header: 'Margen', type: 'percentage', footer: 'average' },
    ],
    exportFilename: 'sales_by_product',
    stats: [
      { key: 'units_sold', label: 'Unidades Vendidas', type: 'number', icon: 'package' },
      { key: 'revenue', label: 'Ingreso Total', type: 'currency', icon: 'dollar-sign' },
      { key: 'average_price', label: 'Precio Promedio', type: 'currency', icon: 'calculator' },
      { key: 'profit_margin', label: 'Margen', type: 'percentage', icon: 'percent' },
    ],
    dataEndpoint: 'store/analytics/sales/by-product',
  },

  {
    id: 'sales-by-category',
    category: 'sales',
    title: 'Por Categoria',
    description: 'Desglose de ventas por categoria de producto',
    detailedDescription:
      'Analiza que categorias de productos generan mas ingresos. Util para decisiones de inventario y marketing.',
    icon: 'tags',
    route: '/admin/reports/sales/sales-by-category',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'category_id',
    columns: [
      { key: 'category_name', header: 'Categoria', type: 'text' },
      { key: 'units_sold', header: 'Unidades Vendidas', type: 'number', footer: 'sum' },
      { key: 'revenue', header: 'Total Ventas', type: 'currency', footer: 'sum' },
      { key: 'percentage_of_total', header: 'Participacion', type: 'percentage' },
    ],
    exportFilename: 'sales_by_category',
    stats: [
      { key: 'units_sold', label: 'Unidades Vendidas', type: 'number', icon: 'package' },
      { key: 'revenue', label: 'Total Ventas', type: 'currency', icon: 'dollar-sign' },
      { key: 'percentage_of_total', label: 'Participacion', type: 'percentage', icon: 'pie-chart' },
      { key: '_count', label: 'Categorias', type: 'number', icon: 'tags' },
    ],
    dataEndpoint: 'store/analytics/sales/by-category',
  },

  {
    id: 'sales-by-customer',
    category: 'sales',
    title: 'Por Cliente',
    description: 'Clientes con mayor facturacion en el periodo',
    detailedDescription:
      'Descubre quienes son tus mejores clientes por volumen de compra. Incluye frecuencia de compra y ticket promedio por cliente.',
    icon: 'user-check',
    route: '/admin/reports/sales/sales-by-customer',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'customer_id',
    columns: [
      { key: 'customer_name', header: 'Cliente', type: 'text' },
      { key: 'total_spent', header: 'Total Compras', type: 'currency', footer: 'sum' },
      { key: 'total_orders', header: 'Cantidad Ordenes', type: 'number', footer: 'sum' },
      { key: 'average_order_value', header: 'Ticket Promedio', type: 'currency', footer: 'average' },
      { key: 'last_order_date', header: 'Ultima Compra', type: 'date' },
    ],
    exportFilename: 'sales_by_customer',
    stats: [
      { key: 'total_spent', label: 'Total Compras', type: 'currency', icon: 'dollar-sign' },
      { key: 'total_orders', label: 'Cantidad Ordenes', type: 'number', icon: 'shopping-cart' },
      { key: 'average_order_value', label: 'Ticket Promedio', type: 'currency', icon: 'calculator' },
      { key: '_count', label: 'Clientes', type: 'number', icon: 'users' },
    ],
    dataEndpoint: 'store/analytics/sales/by-customer',
  },

  {
    id: 'sales-by-payment',
    category: 'sales',
    title: 'Por Metodo de Pago',
    description: 'Distribucion por efectivo, tarjeta, transferencia, etc.',
    detailedDescription:
      'Conoce como prefieren pagar tus clientes. Desglose por metodo de pago con porcentaje de participacion y montos.',
    icon: 'credit-card',
    route: '/admin/reports/sales/sales-by-payment',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'payment_method',
    columns: [
      { key: 'payment_method', header: 'Metodo de Pago', type: 'text' },
      { key: 'display_name', header: 'Nombre', type: 'text' },
      { key: 'total_amount', header: 'Monto Total', type: 'currency', footer: 'sum' },
      { key: 'transaction_count', header: 'Transacciones', type: 'number', footer: 'sum' },
      { key: 'percentage', header: 'Participacion', type: 'percentage' },
    ],
    exportFilename: 'sales_by_payment',
    stats: [
      { key: 'total_amount', label: 'Monto Total', type: 'currency', icon: 'dollar-sign' },
      { key: 'transaction_count', label: 'Transacciones', type: 'number', icon: 'credit-card' },
      { key: 'percentage', label: 'Participacion', type: 'percentage', icon: 'pie-chart' },
      { key: '_count', label: 'Metodos', type: 'number', icon: 'wallet' },
    ],
    dataEndpoint: 'store/analytics/sales/by-payment-method',
  },

  {
    id: 'sales-trends',
    category: 'sales',
    title: 'Tendencias',
    description: 'Evolucion temporal de ventas (diario/semanal/mensual)',
    detailedDescription:
      'Observa como evolucionan tus ventas en el tiempo. Detecta patrones estacionales, dias de mayor venta y tendencias de crecimiento.',
    icon: 'trending-up',
    route: '/admin/reports/sales/sales-trends',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    keyMapping: { period: 'date', revenue: 'total_sales', orders: 'order_count', average_order_value: 'avg_ticket' },
    trackKey: 'period',
    columns: [
      { key: 'date', header: 'Fecha', type: 'date' },
      { key: 'total_sales', header: 'Total Ventas', type: 'currency', footer: 'sum' },
      { key: 'order_count', header: 'Cantidad Ordenes', type: 'number', footer: 'sum' },
      { key: 'avg_ticket', header: 'Ticket Promedio', type: 'currency', footer: 'average' },
    ],
    exportFilename: 'sales_trends',
    stats: [
      { key: 'total_sales', label: 'Total Ventas', type: 'currency', icon: 'dollar-sign' },
      { key: 'order_count', label: 'Cantidad Ordenes', type: 'number', icon: 'shopping-cart' },
      { key: 'avg_ticket', label: 'Ticket Promedio', type: 'currency', icon: 'calculator' },
      { key: '_count', label: 'Dias con Ventas', type: 'number', icon: 'calendar' },
    ],
    dataEndpoint: 'store/analytics/sales/trends',
  },

  // ─── INVENTARIO (7) ──────────────────────────────────────────────────────────

  {
    id: 'inventory-overview',
    category: 'inventory',
    title: 'Resumen de Inventario',
    description: 'Estado general del stock y alertas',
    detailedDescription: 'Vista consolidada del estado de tu inventario con alertas de stock bajo y surplus.',
    icon: 'package-search',
    route: '/admin/reports/inventory/inventory-overview',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'summary' as ReportType,
    summaryLayout: {
      fields: [
        { key: 'total_stock_value', label: 'Valor en Stock', type: 'currency' },
        { key: 'total_quantity_on_hand', label: 'Unidades en Mano', type: 'number' },
        { key: 'low_stock_count', label: 'Bajo Stock', type: 'number' },
        { key: 'out_of_stock_count', label: 'Sin Stock', type: 'number' },
      ],
    },
    columns: [],
    exportFilename: 'resumen-inventario',
    stats: [
      { key: 'total_stock_value', label: 'Valor en Stock', type: 'currency', icon: 'dollar-sign' },
      { key: 'total_quantity_on_hand', label: 'Unidades en Mano', type: 'number', icon: 'layers' },
      { key: 'low_stock_count', label: 'Bajo Stock', type: 'number', icon: 'alert-triangle' },
      { key: 'out_of_stock_count', label: 'Sin Stock', type: 'number', icon: 'x-circle' },
    ],
    dataEndpoint: 'store/analytics/inventory/summary',
  },
  {
    id: 'inventory-stock-info',
    category: 'inventory',
    title: 'Info de Stock',
    description: 'Niveles de stock por ubicacion y producto',
    detailedDescription: 'Consulta niveles de inventario detallados por producto, ubicacion y almacen.',
    icon: 'warehouse',
    route: '/admin/reports/inventory/inventory-stock-info',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'product_id',
    columns: [
      { key: 'product_name', header: 'Producto', type: 'text' },
      { key: 'sku', header: 'SKU', type: 'text' },
      { key: 'quantity_on_hand', header: 'En Mano', type: 'number', footer: 'sum' },
      { key: 'quantity_available', header: 'Disponible', type: 'number', footer: 'sum' },
      { key: 'cost_per_unit', header: 'Costo Unit.', type: 'currency' },
      { key: 'total_value', header: 'Valor Total', type: 'currency', footer: 'sum' },
    ],
    exportFilename: 'info-stock',
    stats: [
      { key: 'total_value', label: 'Valor Total', type: 'currency', icon: 'dollar-sign' },
      { key: 'quantity_on_hand', label: 'En Mano', type: 'number', icon: 'layers' },
      { key: 'quantity_available', label: 'Disponible', type: 'number', icon: 'check-circle' },
      { key: 'quantity_reserved', label: 'Reservado', type: 'number', icon: 'lock' },
    ],
    dataEndpoint: 'store/analytics/inventory/stock-levels',
  },

  {
    id: 'inventory-valuation',
    category: 'inventory',
    title: 'Valoracion',
    description: 'Valor total del inventario por costo y precio de venta',
    detailedDescription:
      'Calcula el valor total de tu inventario actual, tanto a precio de costo como a precio de venta. Incluye desglose por ubicacion y categoria.',
    icon: 'calculator',
    route: '/admin/reports/inventory/inventory-valuation',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'location_id',
    columns: [
      { key: 'location_name', header: 'Ubicacion', type: 'text' },
      { key: 'total_quantity', header: 'Cantidad Total', type: 'number', footer: 'sum' },
      { key: 'average_cost', header: 'Costo Promedio', type: 'currency', footer: 'average' },
      { key: 'total_value', header: 'Valor Total', type: 'currency', footer: 'sum' },
      { key: 'percentage_of_total', header: 'Participacion', type: 'percentage' },
    ],
    exportFilename: 'inventory_valuation',
    stats: [
      { key: 'total_quantity', label: 'Cantidad Total', type: 'number', icon: 'layers' },
      { key: 'total_value', label: 'Valor Total', type: 'currency', icon: 'dollar-sign' },
      { key: 'average_cost', label: 'Costo Promedio', type: 'currency', icon: 'calculator' },
      { key: 'total_locations', label: 'Ubicaciones', type: 'number', icon: 'map-pin' },
    ],
    dataEndpoint: 'store/analytics/inventory/valuation',
  },

  {
    id: 'inventory-movements',
    category: 'inventory',
    title: 'Movimientos',
    description: 'Entradas, salidas, ajustes y transferencias del periodo',
    detailedDescription:
      'Rastrea todos los movimientos de inventario: compras, ventas, ajustes manuales y transferencias entre ubicaciones. Ideal para auditorias.',
    icon: 'arrow-left-right',
    route: '/admin/reports/inventory/inventory-movements',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'id',
    columns: [
      { key: 'date', header: 'Fecha', type: 'date' },
      { key: 'product_name', header: 'Producto', type: 'text' },
      { key: 'movement_type', header: 'Tipo', type: 'text' },
      { key: 'quantity', header: 'Cantidad', type: 'number', footer: 'sum' },
      { key: 'from_location', header: 'Desde', type: 'text' },
      { key: 'to_location', header: 'Hacia', type: 'text' },
      { key: 'reason', header: 'Razon', type: 'text' },
    ],
    exportFilename: 'inventory_movements',
    stats: [
      { key: '_count', label: 'Total Movimientos', type: 'number', icon: 'arrow-left-right' },
      { key: 'quantity', label: 'Cantidad Total', type: 'number', icon: 'layers' },
      { key: 'product_id', label: 'Productos', type: 'number', icon: 'package' },
      { key: 'reference_id', label: 'Referencias', type: 'number', icon: 'file-text' },
    ],
    dataEndpoint: 'store/analytics/inventory/movements',
  },

  {
    id: 'inventory-movement-analysis',
    category: 'inventory',
    title: 'Analisis de Movimientos',
    description: 'Resumen y tendencias de movimientos por tipo',
    detailedDescription:
      'Analisis agregado de movimientos de inventario por tipo y periodo. Identifica patrones de rotacion y detecta anomalias.',
    icon: 'activity',
    route: '/admin/reports/inventory/inventory-movement-analysis',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    keyMapping: { count: 'transaction_count' },
    trackKey: 'movement_type',
    columns: [
      { key: 'movement_type', header: 'Tipo de Movimiento', type: 'text' },
      { key: 'total_quantity', header: 'Cantidad Total', type: 'number', footer: 'sum' },
      { key: 'transaction_count', header: 'Transacciones', type: 'number', footer: 'sum' },
      { key: 'percentage', header: 'Participacion', type: 'percentage' },
    ],
    exportFilename: 'inventory_movement_analysis',
    stats: [
      { key: '_count', label: 'Tipos de Movimiento', type: 'number', icon: 'arrow-left-right' },
      { key: 'total_quantity', label: 'Cantidad Total', type: 'number', icon: 'layers' },
      { key: 'transaction_count', label: 'Transacciones', type: 'number', icon: 'list' },
      { key: 'percentage', label: 'Participacion', type: 'percentage', icon: 'pie-chart' },
    ],
    dataEndpoint: 'store/analytics/inventory/movement-summary',
  },

  // ─── PRODUCTOS (3) ────────────────────────────────────────────────────────────

  {
    id: 'product-performance',
    category: 'products',
    title: 'Rendimiento',
    description: 'Margen, rotacion y rentabilidad por producto',
    detailedDescription:
      'Evaluacion integral del rendimiento de cada producto: ventas, margen de ganancia, rotacion de inventario e indice de rentabilidad.',
    icon: 'gauge',
    route: '/admin/reports/products/product-performance',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'product_id',
    columns: [
      { key: 'product_name', header: 'Producto', type: 'text' },
      { key: 'units_sold', header: 'Unidades Vendidas', type: 'number', footer: 'sum' },
      { key: 'revenue', header: 'Ingreso', type: 'currency', footer: 'sum' },
      { key: 'order_count', header: 'Ordenes', type: 'number', footer: 'sum' },
      { key: 'avg_units_per_order', header: 'Unid/Orden', type: 'number', footer: 'average' },
      { key: 'return_rate', header: 'Tasa Devolucion', type: 'percentage' },
    ],
    exportFilename: 'product_performance',
    stats: [
      { key: 'units_sold', label: 'Unidades Vendidas', type: 'number', icon: 'package' },
      { key: 'revenue', label: 'Ingreso', type: 'currency', icon: 'dollar-sign' },
      { key: 'order_count', label: 'Ordenes', type: 'number', icon: 'shopping-cart' },
      { key: 'return_rate', label: 'Tasa Devolucion', type: 'percentage', icon: 'rotate-ccw' },
    ],
    dataEndpoint: 'store/analytics/products/performance',
  },

  {
    id: 'product-top-sellers',
    category: 'products',
    title: 'Top Sellers',
    description: 'Top sellers por cantidad vendida y por ingreso generado',
    detailedDescription:
      'Los productos mas exitosos de tu catalogo. Ranking dual: por unidades vendidas y por ingresos generados, para tomar decisiones de reabastecimiento.',
    icon: 'trophy',
    route: '/admin/reports/products/product-top-sellers',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'product_id',
    columns: [
      { key: 'product_name', header: 'Producto', type: 'text' },
      { key: 'units_sold', header: 'Unidades Vendidas', type: 'number', footer: 'sum' },
      { key: 'revenue', header: 'Ingreso Total', type: 'currency', footer: 'sum' },
      { key: 'average_price', header: 'Precio Promedio', type: 'currency', footer: 'average' },
      { key: 'profit_margin', header: 'Margen', type: 'percentage', footer: 'average' },
    ],
    exportFilename: 'product_top_sellers',
    stats: [
      { key: 'units_sold', label: 'Unidades Vendidas', type: 'number', icon: 'trophy' },
      { key: 'revenue', label: 'Ingreso Total', type: 'currency', icon: 'dollar-sign' },
      { key: 'average_price', label: 'Precio Promedio', type: 'currency', icon: 'calculator' },
      { key: 'profit_margin', label: 'Margen', type: 'percentage', icon: 'percent' },
    ],
    dataEndpoint: 'store/analytics/products/top-sellers',
  },

  {
    id: 'product-profitability',
    category: 'products',
    title: 'Rentabilidad',
    description: 'Costo vs precio vs margen detallado de cada producto',
    detailedDescription:
      'Analisis de rentabilidad linea por linea. Compara precio de costo, precio de venta y margen real para optimizar tu catalogo de precios.',
    icon: 'percent',
    route: '/admin/reports/products/product-profitability',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'product_id',
    columns: [
      { key: 'product_name', header: 'Producto', type: 'text' },
      { key: 'revenue', header: 'Ingresos', type: 'currency', footer: 'sum' },
      { key: 'total_cost', header: 'Costo Total', type: 'currency', footer: 'sum' },
      { key: 'profit', header: 'Ganancia', type: 'currency', footer: 'sum' },
      { key: 'margin', header: 'Margen (%)', type: 'percentage', footer: 'average' },
      { key: 'units_sold', header: 'Unidades', type: 'number', footer: 'sum' },
    ],
    exportFilename: 'product_profitability',
    stats: [
      { key: 'revenue', label: 'Ingresos', type: 'currency', icon: 'dollar-sign' },
      { key: 'total_cost', label: 'Costo Total', type: 'currency', icon: 'trending-down' },
      { key: 'profit', label: 'Ganancia', type: 'currency', icon: 'trending-up' },
      { key: 'margin', label: 'Margen', type: 'percentage', icon: 'percent' },
    ],
    dataEndpoint: 'store/analytics/products/profitability',
  },

  // ─── CLIENTES (3) ─────────────────────────────────────────────────────────────

  {
    id: 'customer-summary',
    category: 'customers',
    title: 'Resumen de Clientes',
    description: 'Nuevos, activos, recurrentes y promedio de compra',
    detailedDescription:
      'Panorama general de tu base de clientes: cuantos son nuevos, cuantos repiten compra, y metricas clave como valor de vida del cliente y frecuencia de compra.',
    icon: 'users',
    route: '/admin/reports/customers/customer-summary',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'summary' as ReportType,
    summaryLayout: {
      fields: [
        { key: 'total_customers', label: 'Total Clientes', type: 'number' },
        { key: 'active_customers', label: 'Clientes Activos', type: 'number' },
        { key: 'new_customers', label: 'Clientes Nuevos', type: 'number' },
        { key: 'inactive_customers', label: 'Clientes Inactivos', type: 'number' },
        { key: 'average_spend', label: 'Gasto Promedio', type: 'currency' },
        { key: 'new_customers_growth', label: 'Crecimiento Nuevos', type: 'percentage' },
      ],
    },
    columns: [
      { key: 'metric', header: 'Metrica', type: 'text' },
      { key: 'value', header: 'Valor', type: 'number' },
      { key: 'change', header: 'Cambio', type: 'percentage' },
    ],
    exportFilename: 'customer_summary',
    stats: [
      { key: 'total_customers', label: 'Total Clientes', type: 'number', icon: 'users' },
      { key: 'active_customers', label: 'Clientes Activos', type: 'number', icon: 'user-check' },
      { key: 'new_customers', label: 'Clientes Nuevos', type: 'number', icon: 'user-plus' },
      { key: 'average_spend', label: 'Gasto Promedio', type: 'currency', icon: 'dollar-sign' },
    ],
    dataEndpoint: 'store/analytics/customers/summary',
  },
  {
    id: 'customer-acquisition',
    category: 'customers',
    title: 'Adquisicion',
    description: 'Nuevos clientes y canales de adquisicion',
    detailedDescription: 'Rastrea nuevos clientes e identifica cuales canales estan trayendo mas conversiones.',
    icon: 'user-plus',
    route: '/admin/reports/customers/customer-acquisition',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'channel',
    columns: [
      { key: 'channel', header: 'Canal', type: 'text' },
      { key: 'orders', header: 'Ordenes', type: 'number', footer: 'sum' },
      { key: 'revenue', header: 'Ingreso', type: 'currency', footer: 'sum' },
      { key: 'percentage', header: 'Participacion', type: 'percentage' },
    ],
    exportFilename: 'adquisicion-clientes',
    stats: [
      { key: 'total_new_customers', label: 'Clientes Nuevos', type: 'number', icon: 'user-plus' },
      { key: 'total_revenue', label: 'Ingreso Total', type: 'currency', icon: 'dollar-sign' },
      { key: 'total_orders', label: 'Total Ordenes', type: 'number', icon: 'shopping-cart' },
      { key: '_count', label: 'Canales', type: 'number', icon: 'share-2' },
    ],
    dataEndpoint: 'store/analytics/customers/channels',
  },
  {
    id: 'customer-abandoned-carts',
    category: 'customers',
    title: 'Carritos Abandonados',
    description: 'Tasa de abandono y recuperacion de carritos',
    detailedDescription: 'Analiza la tasa de abandono de carritos y recupera ventas potenciales.',
    icon: 'shopping-cart',
    route: '/admin/reports/customers/customer-abandoned-carts',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'summary' as ReportType,
    summaryLayout: {
      fields: [
        { key: 'total_abandoned_carts', label: 'Carritos Abandonados', type: 'number' },
        { key: 'total_abandoned_value', label: 'Valor Abandonado', type: 'currency' },
        { key: 'recovery_rate', label: 'Tasa Recuperacion', type: 'percentage' },
        { key: 'recovered_value', label: 'Valor Recuperado', type: 'currency' },
      ],
    },
    columns: [],
    exportFilename: 'carritos-abandonados',
    stats: [
      { key: 'total_abandoned_carts', label: 'Carritos Abandonados', type: 'number', icon: 'shopping-cart' },
      { key: 'total_abandoned_value', label: 'Valor Total', type: 'currency', icon: 'dollar-sign' },
      { key: 'recovery_rate', label: 'Tasa Recuperacion', type: 'percentage', icon: 'rotate-ccw' },
      { key: 'recovered_value', label: 'Valor Recuperado', type: 'currency', icon: 'check-circle' },
    ],
    dataEndpoint: 'store/analytics/customers/abandoned-carts/summary',
  },

  // ─── CONTABILIDAD (11) ────────────────────────────────────────────────────────

  {
    id: 'trial-balance',
    category: 'accounting',
    title: 'Balance de Prueba',
    description: 'Sumas y saldos por cuenta contable',
    detailedDescription:
      'Reporte contable fundamental que muestra los debitos y creditos totales de cada cuenta. Verifica que la contabilidad este balanceada.',
    icon: 'scale',
    route: '/admin/reports/accounting/trial-balance',
    requiresDateRange: true,
    requiresFiscalPeriod: true,
    type: 'summary' as ReportType,
    summaryLayout: {
      fields: [
        { key: 'total_debit', label: 'Total Debitos', type: 'currency' },
        { key: 'total_credit', label: 'Total Creditos', type: 'currency' },
      ],
    },
    columns: [
      { key: 'account_code', header: 'Codigo', type: 'text' },
      { key: 'account_name', header: 'Cuenta', type: 'text' },
      { key: 'total_debit', header: 'Debito', type: 'currency', footer: 'sum' },
      { key: 'total_credit', header: 'Credito', type: 'currency', footer: 'sum' },
      { key: 'balance', header: 'Saldo', type: 'currency', footer: 'sum' },
    ],
    exportFilename: 'trial_balance',
    stats: [
      { key: 'totals_total_debit', label: 'Total Debitos', type: 'currency', icon: 'arrow-up' },
      { key: 'totals_total_credit', label: 'Total Creditos', type: 'currency', icon: 'arrow-down' },
      { key: '_count', label: 'Total Cuentas', type: 'number', icon: 'list' },
      { key: 'balance', label: 'Saldo Neto', type: 'currency', icon: 'scale' },
    ],
    dataEndpoint: 'store/accounting/reports/trial-balance',
    fullViewRoute: '/admin/accounting/reports/trial-balance',
  },

  {
    id: 'balance-sheet',
    category: 'accounting',
    title: 'Balance General',
    description: 'Activos, pasivos y patrimonio de la empresa',
    detailedDescription:
      'Estado de situacion financiera: activos, pasivos y patrimonio neto. Fotografia de la salud financiera de tu negocio en un momento dado.',
    icon: 'landmark',
    route: '/admin/reports/accounting/balance-sheet',
    requiresDateRange: true,
    requiresFiscalPeriod: true,
    type: 'nested' as ReportType,
    trackKey: 'account_code',
    columns: [
      { key: 'account_code', header: 'Codigo', type: 'text' },
      { key: 'account_name', header: 'Cuenta', type: 'text' },
      { key: 'balance', header: 'Monto', type: 'currency', footer: 'sum' },
    ],
    exportFilename: 'balance_sheet',
    stats: [
      { key: 'total_assets', label: 'Total Activos', type: 'currency', icon: 'trending-up' },
      { key: 'total_liabilities', label: 'Total Pasivos', type: 'currency', icon: 'trending-down' },
      { key: 'total_equity', label: 'Patrimonio', type: 'currency', icon: 'landmark' },
      { key: '_count', label: 'Total Cuentas', type: 'number', icon: 'list' },
    ],
    dataEndpoint: 'store/accounting/reports/balance-sheet',
    fullViewRoute: '/admin/accounting/reports/balance-sheet',
  },

  {
    id: 'income-statement',
    category: 'accounting',
    title: 'Estado de Resultados',
    description: 'Ingresos menos gastos del periodo',
    detailedDescription:
      'Tu negocio genera ganancias? Este reporte muestra ingresos, costos y gastos para determinar la utilidad neta del periodo fiscal.',
    icon: 'file-bar-chart',
    route: '/admin/reports/accounting/income-statement',
    requiresDateRange: true,
    requiresFiscalPeriod: true,
    type: 'nested' as ReportType,
    trackKey: 'account_code',
    columns: [
      { key: 'account_code', header: 'Codigo', type: 'text' },
      { key: 'account_name', header: 'Cuenta', type: 'text' },
      { key: 'balance', header: 'Monto', type: 'currency', footer: 'sum' },
    ],
    exportFilename: 'income_statement',
    stats: [
      { key: 'total_revenue', label: 'Ingresos', type: 'currency', icon: 'trending-up' },
      { key: 'total_costs', label: 'Costos', type: 'currency', icon: 'trending-down' },
      { key: 'net_income', label: 'Utilidad Neta', type: 'currency', icon: 'dollar-sign' },
      { key: '_count', label: 'Total Cuentas', type: 'number', icon: 'list' },
    ],
    dataEndpoint: 'store/accounting/reports/income-statement',
    fullViewRoute: '/admin/accounting/reports/income-statement',
  },

  {
    id: 'general-ledger',
    category: 'accounting',
    title: 'Libro Mayor',
    description: 'Movimientos detallados por cuenta contable',
    detailedDescription:
      'Detalle completo de todos los movimientos contables por cuenta. Filtra por cuenta especifica para ver cada debito y credito registrado.',
    icon: 'book-open',
    route: '/admin/reports/accounting/general-ledger',
    requiresDateRange: true,
    requiresFiscalPeriod: true,
    type: 'list' as ReportType,
    trackKey: 'entry_number',
    columns: [
      { key: 'entry_date', header: 'Fecha', type: 'date' },
      { key: 'entry_number', header: 'No. Asiento', type: 'text' },
      { key: 'entry_description', header: 'Descripcion', type: 'text' },
      { key: 'debit_amount', header: 'Debito', type: 'currency', footer: 'sum' },
      { key: 'credit_amount', header: 'Credito', type: 'currency', footer: 'sum' },
      { key: 'running_balance', header: 'Saldo', type: 'currency' },
    ],
    exportFilename: 'general_ledger',
    stats: [
      { key: 'debit_amount', label: 'Total Debitos', type: 'currency', icon: 'arrow-up' },
      { key: 'credit_amount', label: 'Total Creditos', type: 'currency', icon: 'arrow-down' },
      { key: '_count', label: 'Total Asientos', type: 'number', icon: 'file-text' },
      { key: 'running_balance', label: 'Saldo', type: 'currency', icon: 'scale' },
    ],
    dataEndpoint: 'store/accounting/reports/general-ledger',
    fullViewRoute: '/admin/accounting/reports/general-ledger',
  },
  {
    id: 'chart-of-accounts',
    category: 'accounting',
    title: 'Plan de Cuentas',
    description: 'Listado completo de cuentas contables',
    detailedDescription: 'Todas las cuentas del PUC organizadas por tipo, grupo y cuenta con sus saldos actuales.',
    icon: 'list',
    route: '/admin/reports/accounting/chart-of-accounts',
    requiresDateRange: false,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'code',
    columns: [
      { key: 'code', header: 'Codigo', type: 'text' },
      { key: 'name', header: 'Nombre', type: 'text' },
      { key: 'account_type', header: 'Tipo', type: 'text' },
      { key: 'balance', header: 'Saldo', type: 'currency' },
      { key: 'is_active', header: 'Estado', type: 'text' },
    ],
    exportFilename: 'plan-de-cuentas',
    stats: [
      { key: '_count', label: 'Total Cuentas', type: 'number', icon: 'list' },
      { key: 'balance', label: 'Saldo Total', type: 'currency', icon: 'dollar-sign' },
      { key: 'level', label: 'Nivel Max', type: 'number', icon: 'layers' },
      { key: 'is_active', label: 'Cuentas Activas', type: 'number', icon: 'check-circle' },
    ],
    dataEndpoint: 'store/accounting/chart-of-accounts',
  },
  {
    id: 'journal-entries',
    category: 'accounting',
    title: 'Asientos Contables',
    description: 'Listado de asientos contables del periodo',
    detailedDescription: 'Todos los asientos contables registrados con sus debitos, creditos y estado de aprobacion.',
    icon: 'book-open',
    route: '/admin/reports/accounting/journal-entries',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'entry_number',
    columns: [
      { key: 'entry_number', header: 'No. Asiento', type: 'text' },
      { key: 'entry_date', header: 'Fecha', type: 'date' },
      { key: 'description', header: 'Descripcion', type: 'text' },
      { key: 'total_debit', header: 'Debitos', type: 'currency', footer: 'sum' },
      { key: 'total_credit', header: 'Creditos', type: 'currency', footer: 'sum' },
      { key: 'status', header: 'Estado', type: 'text' },
    ],
    exportFilename: 'asientos-contables',
    stats: [
      { key: '_count', label: 'Total Asientos', type: 'number', icon: 'file-text' },
      { key: 'total_debit', label: 'Total Debitos', type: 'currency', icon: 'arrow-up' },
      { key: 'total_credit', label: 'Total Creditos', type: 'currency', icon: 'arrow-down' },
      { key: 'status', label: 'Estado', type: 'number', icon: 'check-circle' },
    ],
    dataEndpoint: 'store/accounting/journal-entries',
  },
  {
    id: 'fixed-assets',
    category: 'accounting',
    title: 'Activos Fijos',
    description: 'Listado de activos fijos con valor en libros',
    detailedDescription: 'Inventario de activos fijos con costo de adquisicion, depreciacion acumulada y valor en libros.',
    icon: 'building',
    route: '/admin/reports/accounting/fixed-assets',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'id',
    columns: [
      { key: 'asset_number', header: 'Numero', type: 'text' },
      { key: 'name', header: 'Activo', type: 'text' },
      { key: 'acquisition_cost', header: 'Costo', type: 'currency' },
      { key: 'accumulated_depreciation', header: 'Dep. Acumulada', type: 'currency' },
      { key: 'salvage_value', header: 'Valor Residual', type: 'currency' },
      { key: 'useful_life_months', header: 'Vida Util (meses)', type: 'number' },
      { key: 'status', header: 'Estado', type: 'text' },
    ],
    exportFilename: 'activos-fijos',
    stats: [
      { key: '_count', label: 'Total Activos', type: 'number', icon: 'building' },
      { key: 'acquisition_cost', label: 'Costo Total', type: 'currency', icon: 'dollar-sign' },
      { key: 'accumulated_depreciation', label: 'Dep. Total', type: 'currency', icon: 'trending-down' },
      { key: 'useful_life_months', label: 'Vida Util Prom.', type: 'number', icon: 'clock' },
    ],
    dataEndpoint: 'store/accounting/fixed-assets',
  },
  {
    id: 'receivables',
    category: 'accounting',
    title: 'Cuentas por Cobrar',
    description: 'Facturas pendientes de cobro',
    detailedDescription: 'Listado de facturas por cobrar con saldos pendientes, fecha de vencimiento y dias de mora.',
    icon: 'receipt',
    route: '/admin/reports/accounting/receivables',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'id',
    columns: [
      { key: 'document_number', header: 'Documento', type: 'text' },
      { key: 'original_amount', header: 'Monto Original', type: 'currency' },
      { key: 'paid_amount', header: 'Pagado', type: 'currency' },
      { key: 'balance', header: 'Saldo', type: 'currency', footer: 'sum' },
      { key: 'due_date', header: 'Vencimiento', type: 'date' },
      { key: 'days_overdue', header: 'Dias Mora', type: 'number' },
      { key: 'status', header: 'Estado', type: 'text' },
    ],
    exportFilename: 'cuentas-por-cobrar',
    stats: [
      { key: '_count', label: 'Facturas', type: 'number', icon: 'file-text' },
      { key: 'balance', label: 'Total Pendiente', type: 'currency', icon: 'dollar-sign' },
      { key: 'original_amount', label: 'Monto Total', type: 'currency', icon: 'landmark' },
      { key: 'paid_amount', label: 'Total Cobrado', type: 'currency', icon: 'check-circle' },
    ],
    dataEndpoint: 'store/accounts-receivable',
  },
  {
    id: 'payables',
    category: 'accounting',
    title: 'Cuentas por Pagar',
    description: 'Facturas pendientes de pago a proveedores',
    detailedDescription: 'Listado de obligaciones con proveedores, montos pendientes y fechas de vencimiento.',
    icon: 'file-text',
    route: '/admin/reports/accounting/payables',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'id',
    columns: [
      { key: 'document_number', header: 'Documento', type: 'text' },
      { key: 'original_amount', header: 'Monto Original', type: 'currency' },
      { key: 'paid_amount', header: 'Pagado', type: 'currency' },
      { key: 'balance', header: 'Saldo', type: 'currency', footer: 'sum' },
      { key: 'due_date', header: 'Vencimiento', type: 'date' },
      { key: 'days_overdue', header: 'Dias Mora', type: 'number' },
      { key: 'status', header: 'Estado', type: 'text' },
    ],
    exportFilename: 'cuentas-por-pagar',
    stats: [
      { key: '_count', label: 'Facturas', type: 'number', icon: 'file-text' },
      { key: 'balance', label: 'Total por Pagar', type: 'currency', icon: 'dollar-sign' },
      { key: 'original_amount', label: 'Monto Total', type: 'currency', icon: 'landmark' },
      { key: 'paid_amount', label: 'Total Pagado', type: 'currency', icon: 'check-circle' },
    ],
    dataEndpoint: 'store/accounts-payable',
  },
  {
    id: 'aging-report',
    category: 'accounting',
    title: 'Cartera por Vencimiento',
    description: 'Clasificacion de cartera por antiguedad',
    detailedDescription: 'Aging report con clasificacion por rangos de vencimiento: corriente, 1-30, 31-60, 61-90 y mas de 90 dias.',
    icon: 'clock',
    route: '/admin/reports/accounting/aging-report',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'customer_id',
    columns: [
      { key: 'customer_name', header: 'Cliente', type: 'text' },
      { key: 'current', header: 'Corriente', type: 'currency', footer: 'sum' },
      { key: 'days_1_30', header: '1-30 Dias', type: 'currency', footer: 'sum' },
      { key: 'days_31_60', header: '31-60 Dias', type: 'currency', footer: 'sum' },
      { key: 'days_61_90', header: '61-90 Dias', type: 'currency', footer: 'sum' },
      { key: 'over_90', header: '+90 Dias', type: 'currency', footer: 'sum' },
      { key: 'total', header: 'Total', type: 'currency', footer: 'sum' },
    ],
    exportFilename: 'cartera-vencimiento',
    stats: [
      { key: 'current', label: 'Corriente', type: 'currency', icon: 'check-circle' },
      { key: 'days_1_30', label: '1-30 Dias', type: 'currency', icon: 'clock' },
      { key: 'days_31_60', label: '31-60 Dias', type: 'currency', icon: 'alert-triangle' },
      { key: 'total', label: 'Total', type: 'currency', icon: 'dollar-sign' },
    ],
    dataEndpoint: 'store/accounts-receivable/aging',
  },

  // ─── NÓMINA (7) ───────────────────────────────────────────────────────────────

  {
    id: 'payroll-summary',
    category: 'payroll',
    title: 'Resumen de Nomina',
    description: 'Totales por periodo: devengados, deducciones y neto a pagar',
    detailedDescription:
      'Resumen consolidado de nomina con totales de devengados (salarios, auxilios, horas extra), deducciones (salud, pension, otros) y neto a pagar.',
    icon: 'banknote',
    route: '/admin/reports/payroll/payroll-summary',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'period',
    columns: [
      { key: 'period', header: 'Periodo', type: 'text' },
      { key: 'total_earnings', header: 'Total Devengado', type: 'currency', footer: 'sum' },
      { key: 'total_deductions', header: 'Total Deducciones', type: 'currency', footer: 'sum' },
      { key: 'employer_costs', header: 'Costos Empleador', type: 'currency', footer: 'sum' },
      { key: 'net_pay', header: 'Neto a Pagar', type: 'currency', footer: 'sum' },
      { key: 'employee_count', header: 'Empleados', type: 'number', footer: 'sum' },
    ],
    exportFilename: 'payroll_summary',
    stats: [
      { key: 'total_earnings', label: 'Total Devengado', type: 'currency', icon: 'trending-up' },
      { key: 'total_deductions', label: 'Total Deducciones', type: 'currency', icon: 'trending-down' },
      { key: 'net_pay', label: 'Neto a Pagar', type: 'currency', icon: 'dollar-sign' },
      { key: 'employee_count', label: 'Empleados', type: 'number', icon: 'users' },
    ],
    dataEndpoint: 'store/reports/payroll/summary',
  },

  {
    id: 'payroll-by-employee',
    category: 'payroll',
    title: 'Nomina por Empleado',
    description: 'Detalle de cada empleado en el periodo de pago',
    detailedDescription:
      'Desglose individual por empleado: salario base, auxilios, horas extra, deducciones de ley, deducciones voluntarias y neto a pagar.',
    icon: 'user-cog',
    route: '/admin/reports/payroll/payroll-by-employee',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'employee_id',
    columns: [
      { key: 'employee_name', header: 'Empleado', type: 'text' },
      { key: 'base_salary', header: 'Salario Base', type: 'currency' },
      { key: 'earnings', header: 'Devengado', type: 'currency', footer: 'sum' },
      { key: 'deductions', header: 'Deducciones', type: 'currency', footer: 'sum' },
      { key: 'net_pay', header: 'Neto a Pagar', type: 'currency', footer: 'sum' },
    ],
    exportFilename: 'payroll_by_employee',
    stats: [
      { key: 'base_salary', label: 'Salario Base', type: 'currency', icon: 'dollar-sign' },
      { key: 'earnings', label: 'Devengado', type: 'currency', icon: 'trending-up' },
      { key: 'deductions', label: 'Deducciones', type: 'currency', icon: 'trending-down' },
      { key: 'net_pay', label: 'Neto a Pagar', type: 'currency', icon: 'wallet' },
    ],
    dataEndpoint: 'store/reports/payroll/by-employee',
  },

  {
    id: 'payroll-provisions',
    category: 'payroll',
    title: 'Provisiones Laborales',
    description: 'Cesantias, primas, vacaciones e intereses acumulados',
    detailedDescription:
      'Estado actual de las provisiones de prestaciones sociales: cesantias, intereses de cesantias, prima de servicios y vacaciones acumuladas por empleado.',
    icon: 'piggy-bank',
    route: '/admin/reports/payroll/payroll-provisions',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'employee_id',
    columns: [
      { key: 'employee_name', header: 'Empleado', type: 'text' },
      { key: 'severance', header: 'Cesantias', type: 'currency', footer: 'sum' },
      { key: 'severance_interest', header: 'Int. Cesantias', type: 'currency', footer: 'sum' },
      { key: 'bonus', header: 'Prima', type: 'currency', footer: 'sum' },
      { key: 'vacation', header: 'Vacaciones', type: 'currency', footer: 'sum' },
      { key: 'total_provisions', header: 'Total Provisiones', type: 'currency', footer: 'sum' },
    ],
    exportFilename: 'payroll_provisions',
    stats: [
      { key: 'severance', label: 'Cesantias', type: 'currency', icon: 'piggy-bank' },
      { key: 'bonus', label: 'Prima', type: 'currency', icon: 'gift' },
      { key: 'vacation', label: 'Vacaciones', type: 'currency', icon: 'palmtree' },
      { key: 'total_provisions', label: 'Total Provisiones', type: 'currency', icon: 'calculator' },
    ],
    dataEndpoint: 'store/reports/payroll/provisions',
  },
  {
    id: 'payroll-employees',
    category: 'payroll',
    title: 'Empleados',
    description: 'Listado de empleados con datos de nomina',
    detailedDescription: 'Directorio de empleados con salario base, tipo de contrato, fecha de ingreso y estado.',
    icon: 'users',
    route: '/admin/reports/payroll/payroll-employees',
    requiresDateRange: false,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'id',
    columns: [
      { key: 'first_name', header: 'Nombre', type: 'text' },
      { key: 'last_name', header: 'Apellido', type: 'text' },
      { key: 'document_number', header: 'Documento', type: 'text' },
      { key: 'position', header: 'Cargo', type: 'text' },
      { key: 'base_salary', header: 'Salario Base', type: 'currency' },
      { key: 'contract_type', header: 'Contrato', type: 'text' },
      { key: 'hire_date', header: 'Fecha Ingreso', type: 'date' },
      { key: 'status', header: 'Estado', type: 'text' },
    ],
    exportFilename: 'empleados',
    stats: [
      { key: '_count', label: 'Total Empleados', type: 'number', icon: 'users' },
      { key: 'base_salary', label: 'Nomina Total', type: 'currency', icon: 'dollar-sign' },
      { key: 'base_salary', label: 'Salario Promedio', type: 'currency', icon: 'calculator' },
      { key: 'status', label: 'Estado', type: 'number', icon: 'check-circle' },
    ],
    dataEndpoint: 'store/payroll/employees',
  },
  {
    id: 'payroll-runs',
    category: 'payroll',
    title: 'Ejecuciones de Nomina',
    description: 'Historial de ejecuciones de nomina',
    detailedDescription: 'Registro de todas las ejecuciones de nomina con periodo, totales devengados, deducciones y estado.',
    icon: 'play-circle',
    route: '/admin/reports/payroll/payroll-runs',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'id',
    columns: [
      { key: 'payroll_number', header: 'Numero', type: 'text' },
      { key: 'period_start', header: 'Inicio', type: 'date' },
      { key: 'period_end', header: 'Fin', type: 'date' },
      { key: 'total_earnings', header: 'Total Devengado', type: 'currency', footer: 'sum' },
      { key: 'total_deductions', header: 'Total Deducciones', type: 'currency', footer: 'sum' },
      { key: 'total_net_pay', header: 'Neto Pagado', type: 'currency', footer: 'sum' },
      { key: 'status', header: 'Estado', type: 'text' },
    ],
    exportFilename: 'ejecuciones-nomina',
    stats: [
      { key: '_count', label: 'Total Ejecuciones', type: 'number', icon: 'play-circle' },
      { key: 'total_net_pay', label: 'Total Pagado', type: 'currency', icon: 'dollar-sign' },
      { key: 'total_earnings', label: 'Total Devengado', type: 'currency', icon: 'trending-up' },
      { key: 'total_deductions', label: 'Total Deducciones', type: 'currency', icon: 'trending-down' },
    ],
    dataEndpoint: 'store/payroll/runs',
  },
  {
    id: 'payroll-settlements',
    category: 'payroll',
    title: 'Liquidaciones',
    description: 'Liquidaciones laborales procesadas',
    detailedDescription: 'Registro de liquidaciones laborales con concepto, monto, empleado y estado.',
    icon: 'file-check',
    route: '/admin/reports/payroll/payroll-settlements',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'id',
    columns: [
      { key: 'settlement_number', header: 'Numero', type: 'text' },
      { key: 'termination_reason', header: 'Motivo', type: 'text' },
      { key: 'base_salary', header: 'Salario Base', type: 'currency' },
      { key: 'severance', header: 'Cesantias', type: 'currency' },
      { key: 'vacation', header: 'Vacaciones', type: 'currency' },
      { key: 'pending_salary', header: 'Salario Pendiente', type: 'currency' },
      { key: 'status', header: 'Estado', type: 'text' },
    ],
    exportFilename: 'liquidaciones',
    stats: [
      { key: '_count', label: 'Total Liquidaciones', type: 'number', icon: 'file-check' },
      { key: 'base_salary', label: 'Salario Base', type: 'currency', icon: 'dollar-sign' },
      { key: 'severance', label: 'Cesantias', type: 'currency', icon: 'piggy-bank' },
      { key: 'vacation', label: 'Vacaciones', type: 'currency', icon: 'palmtree' },
    ],
    dataEndpoint: 'store/payroll/settlements',
  },
  {
    id: 'payroll-advances',
    category: 'payroll',
    title: 'Anticipos',
    description: 'Anticipos de nomina solicitados',
    detailedDescription: 'Registro de anticipos de nomina con monto, fecha, empleado y estado de aprobacion.',
    icon: 'hand-coins',
    route: '/admin/reports/payroll/payroll-advances',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'id',
    columns: [
      { key: 'advance_number', header: 'Numero', type: 'text' },
      { key: 'amount_requested', header: 'Monto Solicitado', type: 'currency', footer: 'sum' },
      { key: 'amount_approved', header: 'Monto Aprobado', type: 'currency', footer: 'sum' },
      { key: 'amount_pending', header: 'Pendiente', type: 'currency', footer: 'sum' },
      { key: 'advance_date', header: 'Fecha', type: 'date' },
      { key: 'status', header: 'Estado', type: 'text' },
    ],
    exportFilename: 'anticipos-nomina',
    stats: [
      { key: '_count', label: 'Total Anticipos', type: 'number', icon: 'hand-coins' },
      { key: 'amount_requested', label: 'Monto Total', type: 'currency', icon: 'dollar-sign' },
      { key: 'amount_pending', label: 'Pendiente', type: 'currency', icon: 'clock' },
      { key: 'amount_approved', label: 'Aprobado', type: 'currency', icon: 'check-circle' },
    ],
    dataEndpoint: 'store/payroll/advances',
  },

  // ─── FINANCIERO (3) ───────────────────────────────────────────────────────────

  {
    id: 'tax-summary',
    category: 'financial',
    title: 'Resumen de Impuestos',
    description: 'IVA, retenciones e ICA del periodo',
    detailedDescription:
      'Consolidado de impuestos del periodo: IVA generado, IVA descontable, retenciones en la fuente, retencion de ICA y otros impuestos. Util para declaraciones tributarias.',
    icon: 'file-stack',
    route: '/admin/reports/financial/tax-summary',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'summary' as ReportType,
    summaryLayout: {
      fields: [
        { key: 'total_tax_collected', label: 'Impuestos Recaudados', type: 'currency' },
        { key: 'total_tax_refunded', label: 'Impuestos Reembolsados', type: 'currency' },
        { key: 'net_tax', label: 'Impuesto Neto', type: 'currency' },
        { key: 'total_taxable_revenue', label: 'Base Gravable', type: 'currency' },
        { key: 'effective_tax_rate', label: 'Tasa Efectiva', type: 'percentage' },
      ],
    },
    columns: [
      { key: 'tax_name', header: 'Tipo de Impuesto', type: 'text' },
      { key: 'taxable_amount', header: 'Base Gravable', type: 'currency', footer: 'sum' },
      { key: 'total_tax', header: 'Impuesto', type: 'currency', footer: 'sum' },
      { key: 'tax_rate', header: 'Tasa', type: 'percentage' },
    ],
    exportFilename: 'tax_summary',
    stats: [
      { key: 'total_tax_collected', label: 'Impuestos Recaudados', type: 'currency', icon: 'dollar-sign' },
      { key: 'total_tax_refunded', label: 'Impuestos Reembolsados', type: 'currency', icon: 'rotate-ccw' },
      { key: 'net_tax', label: 'Impuesto Neto', type: 'currency', icon: 'calculator' },
      { key: 'effective_tax_rate', label: 'Tasa Efectiva', type: 'percentage', icon: 'percent' },
    ],
    dataEndpoint: 'store/analytics/financial/tax-summary',
  },

  {
    id: 'financial-refunds',
    category: 'financial',
    title: 'Reembolsos',
    description: 'Devoluciones y reembolsos procesados',
    detailedDescription: 'Controla las devoluciones y reembolsos para identificar problemas de calidad o servicio.',
    icon: 'rotate-ccw',
    route: '/admin/reports/financial/financial-refunds',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'refund_id',
    columns: [
      { key: 'order_id', header: 'Orden', type: 'text' },
      { key: 'customer_name', header: 'Cliente', type: 'text' },
      { key: 'amount', header: 'Monto', type: 'currency', footer: 'sum' },
      { key: 'reason', header: 'Motivo', type: 'text' },
      { key: 'status', header: 'Estado', type: 'text' },
      { key: 'created_at', header: 'Fecha', type: 'date' },
    ],
    exportFilename: 'reembolsos',
    stats: [
      { key: 'total_refunds', label: 'Total Reembolsos', type: 'currency', icon: 'dollar-sign' },
      { key: 'subtotal_refunds', label: 'Subtotal', type: 'currency', icon: 'rotate-ccw' },
      { key: 'tax_refunds', label: 'Impuestos', type: 'currency', icon: 'percent' },
      { key: 'shipping_refunds', label: 'Envios', type: 'currency', icon: 'truck' },
    ],
    dataEndpoint: 'store/analytics/financial/refunds',
  },

  {
    id: 'profit-loss',
    category: 'financial',
    title: 'Estado de Resultados',
    description: 'Ingreso neto del negocio en el periodo',
    detailedDescription:
      'El reporte mas importante para duenos de negocio: cuanto ganaste realmente? Ingresos por ventas menos costos de mercancia, gastos operativos y otros gastos.',
    icon: 'trending-up',
    route: '/admin/reports/financial/profit-loss',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'nested' as ReportType,
    trackKey: 'account_code',
    columns: [
      { key: 'concept', header: 'Concepto', type: 'text' },
      { key: 'amount', header: 'Monto', type: 'currency', footer: 'sum' },
      { key: 'percentage', header: 'Porcentaje', type: 'percentage' },
    ],
    exportFilename: 'profit_loss',
    stats: [
      { key: 'gross_revenue', label: 'Ingresos Brutos', type: 'currency', icon: 'trending-up' },
      { key: 'cogs', label: 'Costo Mercancia', type: 'currency', icon: 'trending-down' },
      { key: 'net_profit', label: 'Utilidad Neta', type: 'currency', icon: 'dollar-sign' },
      { key: 'net_margin', label: 'Margen Neto', type: 'percentage', icon: 'percent' },
    ],
    dataEndpoint: 'store/analytics/financial/profit-loss',
  },
];

// ─── HELPERS ──────────────────────────────────────────────────────────────────

export function getReportById(id: string): ReportDefinition | undefined {
  return REPORT_DEFINITIONS.find((report) => report.id === id);
}

export function getReportsByCategory(categoryId: ReportCategoryId): ReportDefinition[] {
  return REPORT_DEFINITIONS.filter((report) => report.category === categoryId);
}

export function getCategoryById(id: ReportCategoryId): ReportCategory | undefined {
  return REPORT_CATEGORIES.find((category) => category.id === id);
}

export function getDefaultReportForCategory(categoryId: ReportCategoryId): ReportDefinition | undefined {
  return getReportsByCategory(categoryId)[0];
}
