import { ReportCategory, ReportCategoryId, ReportDefinition, ReportType } from '../interfaces/report.interface';

export const REPORT_CATEGORIES: ReportCategory[] = [
  { id: 'overview', label: 'Resumen', description: 'Reporte general consolidado del negocio', icon: 'layout-dashboard', color: 'var(--color-primary)' },
  { id: 'sales', label: 'Ventas', description: 'Reportes de ventas y facturacion', icon: 'shopping-cart', color: 'var(--color-primary)' },
  { id: 'inventory', label: 'Inventario', description: 'Reportes de stock y movimientos', icon: 'warehouse', color: 'var(--color-warning)' },
  { id: 'products', label: 'Productos', description: 'Reportes de rendimiento y rentabilidad', icon: 'package', color: 'var(--color-accent)' },
  { id: 'customers', label: 'Clientes', description: 'Reportes de cartera y cuentas por cobrar', icon: 'users', color: 'var(--color-info)' },
  { id: 'purchases', label: 'Compras', description: 'Reportes de ordenes de compra y proveedores', icon: 'truck', color: 'var(--color-warning)' },
  { id: 'reviews', label: 'Reseñas', description: 'Reportes de reseñas y satisfaccion de clientes', icon: 'star', color: 'var(--color-accent)' },
  { id: 'financial', label: 'Financiero', description: 'Reportes de gastos, perdidas y ganancias, caja y cuentas por pagar', icon: 'wallet', color: 'var(--color-destructive)' },
  { id: 'accounting', label: 'Contabilidad', description: 'Reportes contables: balance de prueba, balance general, libro mayor e impuestos', icon: 'scale', color: 'var(--color-info)' },
  { id: 'payroll', label: 'Nómina', description: 'Reportes de nómina: resumen por período, detalle por empleado y provisiones laborales', icon: 'banknote', color: 'var(--color-primary)' },
];

export const REPORT_DEFINITIONS: ReportDefinition[] = [
  // ─── RESUMEN (1) ─────────────────────────────────────────────────────────────────

  {
    id: 'overview-summary',
    category: 'overview',
    title: 'Resumen General',
    description: 'Vista consolidada de ventas, inventario y clientes',
    detailedDescription: 'Reporte general que consolida las metricas principales del negocio: ventas totales, estado de inventario, clientes activos y indicadores clave de rendimiento.',
    icon: 'layout-dashboard',
    route: '/admin/reports/overview/overview-summary',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'summary' as ReportType,
    summaryLayout: {
      fields: [
        { key: 'total_income', label: 'Ingresos Totales', type: 'currency' },
        { key: 'total_expenses', label: 'Gastos Totales', type: 'currency' },
        { key: 'net_profit', label: 'Ganancia Neta', type: 'currency' },
        { key: 'total_taxes', label: 'Impuestos', type: 'currency' },
        { key: 'income_growth', label: 'Crecimiento Ingresos', type: 'percentage' },
        { key: 'net_profit_growth', label: 'Crecimiento Ganancia', type: 'percentage' },
      ],
    },
    columns: [
      { key: 'total_income', header: 'Ingresos Totales', type: 'currency' },
      { key: 'total_expenses', header: 'Gastos Totales', type: 'currency' },
      { key: 'net_profit', header: 'Ganancia Neta', type: 'currency' },
      { key: 'breakeven_ratio', header: 'Punto de Equilibrio', type: 'percentage' },
      { key: 'total_taxes', header: 'Impuestos', type: 'currency' },
      { key: 'income_growth', header: 'Crec. Ingresos', type: 'percentage' },
      { key: 'expenses_growth', header: 'Crec. Gastos', type: 'percentage' },
      { key: 'net_profit_growth', header: 'Crec. Ganancia', type: 'percentage' },
      { key: 'taxes_growth', header: 'Crec. Impuestos', type: 'percentage' },
    ],
    exportFilename: 'resumen-general',
    stats: [
      { key: 'total_income', label: 'Ingresos Totales', type: 'currency', icon: 'dollar-sign' },
      { key: 'total_expenses', label: 'Gastos Totales', type: 'currency', icon: 'trending-down' },
      { key: 'net_profit', label: 'Ganancia Neta', type: 'currency', icon: 'trending-up' },
      { key: 'total_taxes', label: 'Impuestos', type: 'currency', icon: 'percent' },
    ],
    dataEndpoint: 'store/analytics/overview/summary',
  },

  // ─── COMPRAS (3) ─────────────────────────────────────────────────────────────────

  {
    id: 'purchase-summary',
    category: 'purchases',
    title: 'Resumen de Compras',
    description: 'Totales de ordenes de compra y proveedores del periodo',
    detailedDescription: 'Reporte consolidado de todas las ordenes de compra realizadas, incluyendo total comprado, cantidad de ordenes, proveedores principales y comparativa con periodos anteriores.',
    icon: 'truck',
    route: '/admin/reports/purchases/purchase-summary',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'summary' as ReportType,
    summaryLayout: {
      fields: [
        { key: 'total_spent', label: 'Total Compras', type: 'currency' },
        { key: 'total_orders', label: 'Total Ordenes', type: 'number' },
        { key: 'completed_orders', label: 'Completadas', type: 'number' },
        { key: 'average_order_value', label: 'Ticket Promedio', type: 'currency' },
      ],
    },
    columns: [
      { key: 'total_spent', header: 'Total Compras', type: 'currency' },
      { key: 'total_orders', header: 'Total Ordenes', type: 'number' },
      { key: 'completed_orders', header: 'Completadas', type: 'number' },
      { key: 'average_order_value', header: 'Ticket Promedio', type: 'currency' },
    ],
    exportFilename: 'resumen-compras',
    stats: [
      { key: 'total_spent', label: 'Total Compras', type: 'currency', icon: 'dollar-sign' },
      { key: 'total_orders', label: 'Ordenes', type: 'number', icon: 'file-text' },
      { key: 'completed_orders', label: 'Completadas', type: 'number', icon: 'check-circle' },
      { key: 'average_order_value', label: 'Ticket Promedio', type: 'currency', icon: 'calculator' },
    ],
    dataEndpoint: 'store/analytics/purchases/summary',
    exportEndpoint: 'store/analytics/purchases/export',
  },
  {
    id: 'purchase-by-supplier',
    category: 'purchases',
    title: 'Por Proveedor',
    description: 'Desglose de compras agrupadas por proveedor',
    detailedDescription: 'Analisis detallado de las compras realizadas a cada proveedor, mostrando volumen, frecuencia y montos para evaluar relaciones comerciales.',
    icon: 'building-2',
    route: '/admin/reports/purchases/purchase-by-supplier',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    columns: [
      { key: 'supplier_name', header: 'Proveedor', type: 'text' },
      { key: 'order_count', header: 'Ordenes', type: 'number', footer: 'sum' },
      { key: 'total_spent', header: 'Total Comprado', type: 'currency', footer: 'sum' },
      { key: 'pending_orders', header: 'Pendientes', type: 'number' },
      { key: 'last_order_date', header: 'Ultima Orden', type: 'date' },
    ],
    exportFilename: 'compras-por-proveedor',
    stats: [
      { key: 'order_count', label: 'Total Ordenes', type: 'number', icon: 'file-text' },
      { key: 'total_spent', label: 'Total Comprado', type: 'currency', icon: 'dollar-sign' },
      { key: 'pending_orders', label: 'Pendientes', type: 'number', icon: 'clock' },
      { key: '_count', label: 'Proveedores', type: 'number', icon: 'building-2' },
    ],
    dataEndpoint: 'store/analytics/purchases/by-supplier',
  },

  {
    // QUI-547: Tendencias de compra. Serie temporal con date_trunc sobre
    // order_date al granularity del query (hour|day|week|month|year,
    // default day). Permite ver el comportamiento de compras en el tiempo.
    id: 'purchase-trends',
    category: 'purchases',
    title: 'Tendencias de Compra',
    description: 'Serie temporal de órdenes de compra por período',
    detailedDescription:
      'Evolución temporal de las compras: cuántas órdenes se generaron, monto total y desglose entre pendientes y recibidas en cada período (hora, día, semana, mes o año).',
    icon: 'trending-up',
    route: '/admin/reports/purchases/purchase-trends',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'period',
    columns: [
      { key: 'period', header: 'Período', type: 'date' },
      { key: 'order_count', header: 'Órdenes', type: 'number', footer: 'sum' },
      { key: 'total_spent', header: 'Gasto Total', type: 'currency', footer: 'sum' },
      { key: 'pending_count', header: 'Pendientes', type: 'number', footer: 'sum' },
      { key: 'completed_count', header: 'Recibidas', type: 'number', footer: 'sum' },
    ],
    exportFilename: 'tendencias_compra',
    stats: [
      { key: 'total_spent', label: 'Gasto Total', type: 'currency', icon: 'dollar-sign' },
      { key: 'order_count', label: 'Órdenes Totales', type: 'number', icon: 'file-text' },
      { key: 'pending_count', label: 'Pendientes', type: 'number', icon: 'clock' },
    ],
    dataEndpoint: 'store/analytics/purchases/trends',
    exportEndpoint: 'store/analytics/purchases/trends/export',
  },

  // ─── RESEÑAS (2) ──────────────────────────────────────────────────────────────────

  {
    id: 'reviews-summary',
    category: 'reviews',
    title: 'Resumen de Reseñas',
    description: 'Calificacion promedio y distribucion de reseñas',
    detailedDescription: 'Reporte consolidado de las reseñas recibidas, incluyendo calificacion promedio, distribucion por estrellas, productos mejor valorados y tendencias de satisfaccion.',
    icon: 'star',
    route: '/admin/reports/reviews/reviews-summary',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'summary' as ReportType,
    summaryLayout: {
      fields: [
        { key: 'average_rating', label: 'Calificacion Promedio', type: 'number' },
        { key: 'total_reviews', label: 'Total Reseñas', type: 'number' },
        { key: 'approved_reviews', label: 'Aprobadas', type: 'number' },
        { key: 'total_helpful_votes', label: 'Votos Utiles', type: 'number' },
      ],
    },
    columns: [
      { key: 'average_rating', header: 'Calificacion Promedio', type: 'number' },
      { key: 'total_reviews', header: 'Total Reseñas', type: 'number' },
      { key: 'approved_reviews', header: 'Aprobadas', type: 'number' },
      { key: 'total_helpful_votes', header: 'Votos Utiles', type: 'number' },
    ],
    exportFilename: 'resumen-resenas',
    stats: [
      { key: 'average_rating', label: 'Calificacion Promedio', type: 'number', icon: 'star' },
      { key: 'total_reviews', label: 'Total Reseñas', type: 'number', icon: 'message-square' },
      { key: 'approved_reviews', label: 'Aprobadas', type: 'number', icon: 'award' },
      { key: 'total_helpful_votes', label: 'Votos Utiles', type: 'number', icon: 'thumbs-up' },
    ],
    dataEndpoint: 'store/analytics/reviews/summary',
    exportEndpoint: 'store/analytics/reviews/export',
  },

  {
    // QUI-548: Reseñas por producto. Una fila por producto con total,
    // promedio, distribución de estrellas y conteo de verificadas.
    id: 'reviews-by-product',
    category: 'reviews',
    title: 'Reseñas por Producto',
    description: 'Calificación promedio y distribución de estrellas por producto',
    detailedDescription:
      'Detalle de reseñas agrupadas por producto: total, promedio (1 decimal), distribución 1-5 estrellas, cuántas son de compra verificada y cuántas siguen pendientes de moderación.',
    icon: 'star',
    route: '/admin/reports/reviews/reviews-by-product',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'product_id',
    columns: [
      { key: 'product_name', header: 'Producto', type: 'text' },
      { key: 'sku', header: 'SKU', type: 'text' },
      { key: 'total_reviews', header: 'Reseñas', type: 'number', footer: 'sum' },
      { key: 'average_rating', header: 'Promedio', type: 'number' },
      { key: 'stars_5', header: '5★', type: 'number', footer: 'sum' },
      { key: 'stars_4', header: '4★', type: 'number', footer: 'sum' },
      { key: 'stars_3', header: '3★', type: 'number', footer: 'sum' },
      { key: 'stars_2', header: '2★', type: 'number', footer: 'sum' },
      { key: 'stars_1', header: '1★', type: 'number', footer: 'sum' },
      { key: 'verified_count', header: 'Verificadas', type: 'number', footer: 'sum' },
      { key: 'pending_count', header: 'Pendientes', type: 'number', footer: 'sum' },
      { key: 'last_review_date', header: 'Última Reseña', type: 'date' },
    ],
    exportFilename: 'resenas_por_producto',
    stats: [
      { key: 'total_reviews', label: 'Total Reseñas', type: 'number', icon: 'message-square' },
      { key: 'average_rating', label: 'Promedio General', type: 'number', icon: 'star' },
      { key: 'verified_count', label: 'Verificadas', type: 'number', icon: 'check-circle' },
    ],
    dataEndpoint: 'store/analytics/reviews/by-product',
    exportEndpoint: 'store/analytics/reviews/by-product/export',
  },

  // ─── VENTAS (6) ───────────────────────────────────────────────────────────────

  {
    id: 'sales-summary',
    category: 'sales',
    title: 'Resumen de Ventas',
    description: 'Totales de ventas, promedios y ticket promedio del periodo',
    detailedDescription:
      'Visualiza un resumen completo de las ventas del periodo seleccionado, incluyendo total facturado, cantidad de ordenes, ticket promedio, descuentos aplicados y comparativa con periodo anterior.',
    icon: 'bar-chart-3',
    route: '/admin/reports/sales/sales-summary',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'summary' as ReportType,
    summaryLayout: {
      fields: [
        { key: 'total_revenue', label: 'Ventas Totales', type: 'currency' },
        { key: 'total_orders', label: 'Total Pedidos', type: 'number' },
        { key: 'average_order_value', label: 'Ticket Promedio', type: 'currency' },
        { key: 'total_units_sold', label: 'Productos Vendidos', type: 'number' },
        { key: 'total_customers', label: 'Clientes Unicos', type: 'number' },
        { key: 'revenue_growth', label: 'Crecimiento Ingresos', type: 'percentage' },
        { key: 'orders_growth', label: 'Crecimiento Ordenes', type: 'percentage' },
      ],
    },
    columns: [
      { key: 'total_revenue', header: 'Ventas Totales', type: 'currency' },
      { key: 'total_orders', header: 'Total Pedidos', type: 'number' },
      { key: 'average_order_value', header: 'Ticket Promedio', type: 'currency' },
      { key: 'total_units_sold', header: 'Productos Vendidos', type: 'number' },
      { key: 'total_customers', header: 'Clientes', type: 'number' },
      { key: 'revenue_growth', header: 'Crecimiento', type: 'percentage' },
      { key: 'orders_growth', header: 'Crec. Ordenes', type: 'percentage' },
    ],
    exportFilename: 'sales_summary',
    stats: [
      { key: 'total_revenue', label: 'Ventas Totales', type: 'currency', icon: 'dollar-sign' },
      { key: 'total_orders', label: 'Total Pedidos', type: 'number', icon: 'shopping-cart' },
      { key: 'average_order_value', label: 'Ticket Promedio', type: 'currency', icon: 'calculator' },
      { key: 'total_units_sold', label: 'Productos Vendidos', type: 'number', icon: 'package' },
    ],
    dataEndpoint: 'store/analytics/sales/summary',
    exportEndpoint: 'store/analytics/sales/export',
  },

  {
    id: 'sales-by-product',
    category: 'sales',
    title: 'Por Producto',
    description: 'Ranking de productos vendidos con cantidades y montos',
    detailedDescription:
      'Identifica tus productos estrella con un ranking detallado por cantidad vendida e ingreso generado. Incluye margen de ganancia por producto.',
    icon: 'package-search',
    route: '/admin/reports/sales/sales-by-product',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'product_id',
    columns: [
      { key: 'product_name', header: 'Producto', type: 'text' },
      { key: 'units_sold', header: 'Cantidad Vendida', type: 'number', footer: 'sum' },
      { key: 'revenue', header: 'Ingreso Total', type: 'currency', footer: 'sum' },
      { key: 'average_price', header: 'Precio Promedio', type: 'currency', footer: 'average' },
      { key: 'profit_margin', header: 'Margen', type: 'percentage', footer: 'average' },
    ],
    exportFilename: 'sales_by_product',
    stats: [
      { key: 'units_sold', label: 'Unidades Vendidas', type: 'number', icon: 'package' },
      { key: 'revenue', label: 'Ingreso Total', type: 'currency', icon: 'dollar-sign' },
      { key: 'average_price', label: 'Precio Promedio', type: 'currency', icon: 'calculator' },
      { key: 'profit_margin', label: 'Margen', type: 'percentage', icon: 'percent' },
    ],
    dataEndpoint: 'store/analytics/sales/by-product',
  },

  {
    id: 'sales-by-category',
    category: 'sales',
    title: 'Por Categoria',
    description: 'Desglose de ventas por categoria de producto',
    detailedDescription:
      'Analiza que categorias de productos generan mas ingresos. Util para decisiones de inventario y marketing.',
    icon: 'tags',
    route: '/admin/reports/sales/sales-by-category',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'category_id',
    columns: [
      { key: 'category_name', header: 'Categoria', type: 'text' },
      { key: 'units_sold', header: 'Unidades Vendidas', type: 'number', footer: 'sum' },
      { key: 'revenue', header: 'Total Ventas', type: 'currency', footer: 'sum' },
      { key: 'percentage_of_total', header: 'Participacion', type: 'percentage' },
    ],
    exportFilename: 'sales_by_category',
    stats: [
      { key: 'units_sold', label: 'Unidades Vendidas', type: 'number', icon: 'package' },
      { key: 'revenue', label: 'Total Ventas', type: 'currency', icon: 'dollar-sign' },
      { key: 'percentage_of_total', label: 'Participacion', type: 'percentage', icon: 'pie-chart' },
      { key: '_count', label: 'Categorias', type: 'number', icon: 'tags' },
    ],
    dataEndpoint: 'store/analytics/sales/by-category',
  },

  {
    id: 'sales-by-customer',
    category: 'sales',
    title: 'Por Cliente',
    description: 'Clientes con mayor facturacion en el periodo',
    detailedDescription:
      'Descubre quienes son tus mejores clientes por volumen de compra. Incluye frecuencia de compra y ticket promedio por cliente.',
    icon: 'user-check',
    route: '/admin/reports/sales/sales-by-customer',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'customer_id',
    columns: [
      { key: 'customer_name', header: 'Cliente', type: 'text' },
      { key: 'total_spent', header: 'Total Compras', type: 'currency', footer: 'sum' },
      { key: 'total_orders', header: 'Cantidad Ordenes', type: 'number', footer: 'sum' },
      { key: 'average_order_value', header: 'Ticket Promedio', type: 'currency', footer: 'average' },
      { key: 'last_order_date', header: 'Ultima Compra', type: 'date' },
    ],
    exportFilename: 'sales_by_customer',
    stats: [
      { key: 'total_spent', label: 'Total Compras', type: 'currency', icon: 'dollar-sign' },
      { key: 'total_orders', label: 'Cantidad Ordenes', type: 'number', icon: 'shopping-cart' },
      { key: 'average_order_value', label: 'Ticket Promedio', type: 'currency', icon: 'calculator' },
      { key: '_count', label: 'Clientes', type: 'number', icon: 'users' },
    ],
    dataEndpoint: 'store/analytics/sales/by-customer',
  },

  {
    id: 'sales-by-payment',
    category: 'sales',
    title: 'Por Metodo de Pago',
    description: 'Distribucion por efectivo, tarjeta, transferencia, etc.',
    detailedDescription:
      'Conoce como prefieren pagar tus clientes. Desglose por metodo de pago con porcentaje de participacion y montos.',
    icon: 'credit-card',
    route: '/admin/reports/sales/sales-by-payment',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'payment_method',
    columns: [
      { key: 'payment_method', header: 'Metodo de Pago', type: 'text' },
      { key: 'display_name', header: 'Nombre', type: 'text' },
      { key: 'total_amount', header: 'Monto Total', type: 'currency', footer: 'sum' },
      { key: 'transaction_count', header: 'Transacciones', type: 'number', footer: 'sum' },
      { key: 'percentage', header: 'Participacion', type: 'percentage' },
    ],
    exportFilename: 'sales_by_payment',
    stats: [
      { key: 'total_amount', label: 'Monto Total', type: 'currency', icon: 'dollar-sign' },
      { key: 'transaction_count', label: 'Transacciones', type: 'number', icon: 'credit-card' },
      { key: 'percentage', label: 'Participacion', type: 'percentage', icon: 'pie-chart' },
      { key: '_count', label: 'Metodos', type: 'number', icon: 'wallet' },
    ],
    dataEndpoint: 'store/analytics/sales/by-payment-method',
  },

  {
    // QUI-549: Ventas por canal. groupBy de orders.channel con
    // COMPLETED_SALE_STATES, mostrando órdenes, ingresos y % de
    // participación por canal (POS, ecommerce, agent, whatsapp,
    // marketplace).
    id: 'sales-by-channel',
    category: 'sales',
    title: 'Por Canal',
    description: 'Distribución de ventas por canal: POS, ecommerce, agente, etc.',
    detailedDescription:
      'Conoce por dónde venden más: punto de venta, tienda online, agente IA, WhatsApp o marketplace. Distribución con conteo de órdenes, ingresos y % de participación.',
    icon: 'radio',
    route: '/admin/reports/sales/sales-by-channel',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'channel',
    columns: [
      { key: 'display_name', header: 'Canal', type: 'text' },
      { key: 'order_count', header: 'Órdenes', type: 'number', footer: 'sum' },
      { key: 'revenue', header: 'Ingresos', type: 'currency', footer: 'sum' },
      { key: 'percentage', header: '% Participación', type: 'percentage' },
    ],
    exportFilename: 'ventas_por_canal',
    stats: [
      { key: 'revenue', label: 'Ingresos Totales', type: 'currency', icon: 'dollar-sign' },
      { key: 'order_count', label: 'Órdenes Totales', type: 'number', icon: 'shopping-cart' },
    ],
    dataEndpoint: 'store/analytics/sales/by-channel',
    exportEndpoint: 'store/analytics/sales/by-channel/export',
  },

  {
    // QUI-551: Ventas por vendedor. sales_orders.created_by_user_id
    // es el proxy de "vendedor" (POS-heavy; ecommerce/whatsapp sin
    // sales_order previa no se atribuyen a nadie).
    id: 'sales-by-seller',
    category: 'sales',
    title: 'Por Vendedor',
    description: 'Ventas atribuidas al staff que creó la orden',
    detailedDescription:
      'Ranking de vendedores por ingresos generados. La atribución es al usuario staff que creó la sales_order (principalmente POS). Órdenes ecommerce y WhatsApp que no pasan por sales_order no se atribuyen a un vendedor específico.',
    icon: 'user-cog',
    route: '/admin/reports/sales/sales-by-seller',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'seller_id',
    columns: [
      { key: 'seller_name', header: 'Vendedor', type: 'text' },
      { key: 'email', header: 'Correo', type: 'text' },
      { key: 'order_count', header: 'Órdenes', type: 'number', footer: 'sum' },
      { key: 'total_revenue', header: 'Ingresos', type: 'currency', footer: 'sum' },
    ],
    exportFilename: 'ventas_por_vendedor',
    stats: [
      { key: 'total_revenue', label: 'Ingresos Totales', type: 'currency', icon: 'dollar-sign' },
      { key: 'order_count', label: 'Órdenes Totales', type: 'number', icon: 'shopping-cart' },
      { key: '_count', label: 'Vendedores', type: 'number', icon: 'users' },
    ],
    dataEndpoint: 'store/analytics/sales/by-seller',
    exportEndpoint: 'store/analytics/sales/by-seller/export',
  },

  {
    id: 'sales-trends',
    category: 'sales',
    title: 'Tendencias',
    description: 'Evolucion temporal de ventas (diario/semanal/mensual)',
    detailedDescription:
      'Observa como evolucionan tus ventas en el tiempo. Detecta patrones estacionales, dias de mayor venta y tendencias de crecimiento.',
    icon: 'trending-up',
    route: '/admin/reports/sales/sales-trends',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    keyMapping: { period: 'date', revenue: 'total_sales', orders: 'order_count', average_order_value: 'avg_ticket' },
    trackKey: 'period',
    columns: [
      { key: 'date', header: 'Fecha', type: 'date' },
      { key: 'total_sales', header: 'Total Ventas', type: 'currency', footer: 'sum' },
      { key: 'order_count', header: 'Cantidad Ordenes', type: 'number', footer: 'sum' },
      { key: 'avg_ticket', header: 'Ticket Promedio', type: 'currency', footer: 'average' },
    ],
    exportFilename: 'sales_trends',
    stats: [
      { key: 'total_sales', label: 'Total Ventas', type: 'currency', icon: 'dollar-sign' },
      { key: 'order_count', label: 'Cantidad Ordenes', type: 'number', icon: 'shopping-cart' },
      { key: 'avg_ticket', label: 'Ticket Promedio', type: 'currency', icon: 'calculator' },
      { key: '_count', label: 'Dias con Ventas', type: 'number', icon: 'calendar' },
    ],
    dataEndpoint: 'store/analytics/sales/trends',
  },

  // ─── INVENTARIO (7) ──────────────────────────────────────────────────────────

  {
    id: 'inventory-overview',
    category: 'inventory',
    title: 'Resumen de Inventario',
    description: 'Estado general del stock y alertas',
    detailedDescription: 'Vista consolidada del estado de tu inventario con alertas de stock bajo y surplus.',
    icon: 'package-search',
    route: '/admin/reports/inventory/inventory-overview',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'summary' as ReportType,
    summaryLayout: {
      fields: [
        { key: 'total_stock_value', label: 'Valor en Stock', type: 'currency' },
        { key: 'total_quantity_on_hand', label: 'Unidades en Mano', type: 'number' },
        { key: 'low_stock_count', label: 'Bajo Stock', type: 'number' },
        { key: 'out_of_stock_count', label: 'Sin Stock', type: 'number' },
      ],
    },
    columns: [
      { key: 'total_stock_value', header: 'Valor en Stock', type: 'currency' },
      { key: 'total_quantity_on_hand', header: 'Unidades en Mano', type: 'number' },
      { key: 'low_stock_count', header: 'Bajo Stock', type: 'number' },
      { key: 'out_of_stock_count', header: 'Sin Stock', type: 'number' },
    ],
    exportFilename: 'resumen-inventario',
    stats: [
      { key: 'total_stock_value', label: 'Valor en Stock', type: 'currency', icon: 'dollar-sign' },
      { key: 'total_quantity_on_hand', label: 'Unidades en Mano', type: 'number', icon: 'layers' },
      { key: 'low_stock_count', label: 'Bajo Stock', type: 'number', icon: 'alert-triangle' },
      { key: 'out_of_stock_count', label: 'Sin Stock', type: 'number', icon: 'x-circle' },
    ],
    dataEndpoint: 'store/analytics/inventory/summary',
  },
  {
    id: 'inventory-stock-info',
    category: 'inventory',
    title: 'Info de Stock',
    description: 'Niveles de stock por ubicacion y producto',
    detailedDescription: 'Consulta niveles de inventario detallados por producto, ubicacion y almacen.',
    icon: 'warehouse',
    route: '/admin/reports/inventory/inventory-stock-info',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'product_id',
    columns: [
      { key: 'product_name', header: 'Producto', type: 'text' },
      { key: 'sku', header: 'SKU', type: 'text' },
      { key: 'quantity_on_hand', header: 'En Mano', type: 'number', footer: 'sum' },
      { key: 'quantity_available', header: 'Disponible', type: 'number', footer: 'sum' },
      { key: 'cost_per_unit', header: 'Costo Unit.', type: 'currency' },
      { key: 'total_value', header: 'Valor Total', type: 'currency', footer: 'sum' },
    ],
    exportFilename: 'info-stock',
    stats: [
      { key: 'total_value', label: 'Valor Total', type: 'currency', icon: 'dollar-sign' },
      { key: 'quantity_on_hand', label: 'En Mano', type: 'number', icon: 'layers' },
      { key: 'quantity_available', label: 'Disponible', type: 'number', icon: 'check-circle' },
      { key: 'quantity_reserved', label: 'Reservado', type: 'number', icon: 'lock' },
    ],
    dataEndpoint: 'store/analytics/inventory/stock-levels',
    exportEndpoint: 'store/analytics/inventory/export',
  },

  {
    // QUI-545: Stock bajo / puntos de reorden. Reusa getLowStockAlerts del
    // service (que ya filtra qty <= reorder_point con el helper compartido)
    // y le agrega `stock_value_at_risk` (qty * cost_price) para mostrar el
    // impacto monetario de reponer.
    id: 'inventory-low-stock',
    category: 'inventory',
    title: 'Stock Bajo',
    description: 'Productos en o por debajo del punto de reorden',
    detailedDescription:
      'Productos activos con stock_quantity ≤ reorder_point, incluyendo el valor en riesgo (stock_actual × costo) para priorizar la reposición.',
    icon: 'alert-triangle',
    route: '/admin/reports/inventory/inventory-low-stock',
    requiresDateRange: false,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'product_id',
    columns: [
      { key: 'product_name', header: 'Producto', type: 'text' },
      { key: 'sku', header: 'SKU', type: 'text' },
      { key: 'stock_quantity', header: 'Stock Actual', type: 'number', footer: 'sum' },
      { key: 'min_stock_level', header: 'Stock Mínimo', type: 'number' },
      { key: 'reorder_point', header: 'Punto de Reorden', type: 'number' },
      { key: 'status', header: 'Estado', type: 'text' },
      { key: 'stock_value_at_risk', header: 'Valor en Riesgo', type: 'currency', footer: 'sum' },
    ],
    exportFilename: 'stock_bajo',
    stats: [
      { key: 'stock_quantity', label: 'Unidades en Riesgo', type: 'number', icon: 'layers' },
      { key: 'stock_value_at_risk', label: 'Valor en Riesgo', type: 'currency', icon: 'dollar-sign' },
    ],
    dataEndpoint: 'store/analytics/inventory/low-stock',
    exportEndpoint: 'store/analytics/inventory/low-stock/export',
  },

  {
    // QUI-550: Inventario por proveedor via supplier_products.
    // Una fila por proveedor con: productos vinculados, stock total,
    // costo promedio pactado, valorización total y cuántos de sus
    // productos son preferred.
    id: 'inventory-by-supplier',
    category: 'inventory',
    title: 'Inventario por Proveedor',
    description: 'Stock y valorización agrupados por proveedor',
    detailedDescription:
      'Para cada proveedor con productos vinculados, muestra cuántos productos tienes con él, el stock total de esos productos, el costo promedio pactado y el valor total en bodega. Útil para negociar volúmenes y diversificar proveedores.',
    icon: 'building',
    route: '/admin/reports/inventory/inventory-by-supplier',
    requiresDateRange: false,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'supplier_id',
    columns: [
      { key: 'supplier_name', header: 'Proveedor', type: 'text' },
      { key: 'supplier_code', header: 'Código', type: 'text' },
      { key: 'product_count', header: 'Productos', type: 'number', footer: 'sum' },
      { key: 'total_stock_quantity', header: 'Stock Total', type: 'number', footer: 'sum' },
      { key: 'avg_cost_per_unit', header: 'Costo Promedio', type: 'currency' },
      { key: 'total_stock_value', header: 'Valor Stock', type: 'currency', footer: 'sum' },
      { key: 'preferred_count', header: 'Preferidos', type: 'number', footer: 'sum' },
    ],
    exportFilename: 'inventario_por_proveedor',
    stats: [
      { key: 'total_stock_value', label: 'Valor Total', type: 'currency', icon: 'dollar-sign' },
      { key: 'total_stock_quantity', label: 'Stock Total', type: 'number', icon: 'layers' },
      { key: '_count', label: 'Proveedores', type: 'number', icon: 'building' },
    ],
    dataEndpoint: 'store/analytics/inventory/by-supplier',
    exportEndpoint: 'store/analytics/inventory/by-supplier/export',
  },

  {
    id: 'inventory-valuation',
    category: 'inventory',
    title: 'Valoracion',
    description: 'Valor total del inventario por costo y precio de venta',
    detailedDescription:
      'Calcula el valor total de tu inventario actual, tanto a precio de costo como a precio de venta. Incluye desglose por ubicacion y categoria.',
    icon: 'calculator',
    route: '/admin/reports/inventory/inventory-valuation',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'location_id',
    columns: [
      { key: 'location_name', header: 'Ubicacion', type: 'text' },
      { key: 'total_quantity', header: 'Cantidad Total', type: 'number', footer: 'sum' },
      { key: 'average_cost', header: 'Costo Promedio', type: 'currency', footer: 'average' },
      { key: 'total_value', header: 'Valor Total', type: 'currency', footer: 'sum' },
      { key: 'percentage_of_total', header: 'Participacion', type: 'percentage' },
    ],
    exportFilename: 'inventory_valuation',
    stats: [
      { key: 'total_quantity', label: 'Cantidad Total', type: 'number', icon: 'layers' },
      { key: 'total_value', label: 'Valor Total', type: 'currency', icon: 'dollar-sign' },
      { key: 'average_cost', label: 'Costo Promedio', type: 'currency', icon: 'calculator' },
      { key: 'total_locations', label: 'Ubicaciones', type: 'number', icon: 'map-pin' },
    ],
    dataEndpoint: 'store/analytics/inventory/valuation',
  },

  {
    id: 'inventory-movements',
    category: 'inventory',
    title: 'Movimientos',
    description: 'Entradas, salidas, ajustes y transferencias del periodo',
    detailedDescription:
      'Rastrea todos los movimientos de inventario: compras, ventas, ajustes manuales y transferencias entre ubicaciones. Ideal para auditorias.',
    icon: 'arrow-left-right',
    route: '/admin/reports/inventory/inventory-movements',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'id',
    columns: [
      { key: 'date', header: 'Fecha', type: 'date' },
      { key: 'product_name', header: 'Producto', type: 'text' },
      { key: 'movement_type', header: 'Tipo', type: 'text' },
      { key: 'quantity', header: 'Cantidad', type: 'number', footer: 'sum' },
      { key: 'from_location', header: 'Desde', type: 'text' },
      { key: 'to_location', header: 'Hacia', type: 'text' },
      { key: 'reason', header: 'Razon', type: 'text' },
    ],
    exportFilename: 'inventory_movements',
    stats: [
      { key: '_count', label: 'Total Movimientos', type: 'number', icon: 'arrow-left-right' },
      { key: 'quantity', label: 'Cantidad Total', type: 'number', icon: 'layers' },
      { key: 'product_id', label: 'Productos', type: 'number', icon: 'package' },
      { key: 'reference_id', label: 'Referencias', type: 'number', icon: 'file-text' },
    ],
    dataEndpoint: 'store/analytics/inventory/movements',
    exportEndpoint: 'store/analytics/inventory/movements/export',
  },

  {
    id: 'inventory-movement-analysis',
    category: 'inventory',
    title: 'Analisis de Movimientos',
    description: 'Resumen y tendencias de movimientos por tipo',
    detailedDescription:
      'Analisis agregado de movimientos de inventario por tipo y periodo. Identifica patrones de rotacion y detecta anomalias.',
    icon: 'activity',
    route: '/admin/reports/inventory/inventory-movement-analysis',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    keyMapping: { count: 'transaction_count' },
    trackKey: 'movement_type',
    columns: [
      { key: 'movement_type', header: 'Tipo de Movimiento', type: 'text' },
      { key: 'total_quantity', header: 'Cantidad Total', type: 'number', footer: 'sum' },
      { key: 'transaction_count', header: 'Transacciones', type: 'number', footer: 'sum' },
      { key: 'percentage', header: 'Participacion', type: 'percentage' },
    ],
    exportFilename: 'inventory_movement_analysis',
    stats: [
      { key: '_count', label: 'Tipos de Movimiento', type: 'number', icon: 'arrow-left-right' },
      { key: 'total_quantity', label: 'Cantidad Total', type: 'number', icon: 'layers' },
      { key: 'transaction_count', label: 'Transacciones', type: 'number', icon: 'list' },
      { key: 'percentage', label: 'Participacion', type: 'percentage', icon: 'pie-chart' },
    ],
    dataEndpoint: 'store/analytics/inventory/movement-summary',
  },

  // ─── PRODUCTOS (3) ────────────────────────────────────────────────────────────

  {
    id: 'product-performance',
    category: 'products',
    title: 'Rendimiento',
    description: 'Margen, rotacion y rentabilidad por producto',
    detailedDescription:
      'Evaluacion integral del rendimiento de cada producto: ventas, margen de ganancia, rotacion de inventario e indice de rentabilidad.',
    icon: 'gauge',
    route: '/admin/reports/products/product-performance',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'product_id',
    columns: [
      { key: 'product_name', header: 'Producto', type: 'text' },
      { key: 'units_sold', header: 'Unidades Vendidas', type: 'number', footer: 'sum' },
      { key: 'revenue', header: 'Ingreso', type: 'currency', footer: 'sum' },
      { key: 'order_count', header: 'Ordenes', type: 'number', footer: 'sum' },
      { key: 'avg_units_per_order', header: 'Unid/Orden', type: 'number', footer: 'average' },
      { key: 'return_rate', header: 'Tasa Devolucion', type: 'percentage' },
    ],
    exportFilename: 'product_performance',
    stats: [
      { key: 'units_sold', label: 'Unidades Vendidas', type: 'number', icon: 'package' },
      { key: 'revenue', label: 'Ingreso', type: 'currency', icon: 'dollar-sign' },
      { key: 'order_count', label: 'Ordenes', type: 'number', icon: 'shopping-cart' },
      { key: 'return_rate', label: 'Tasa Devolucion', type: 'percentage', icon: 'rotate-ccw' },
    ],
    dataEndpoint: 'store/analytics/products/performance',
    exportEndpoint: 'store/analytics/products/performance/export',
  },

  {
    id: 'product-top-sellers',
    category: 'products',
    title: 'Mas Vendidos',
    description: 'Top sellers por cantidad vendida y por ingreso generado',
    detailedDescription:
      'Los productos mas exitosos de tu catalogo. Ranking dual: por unidades vendidas y por ingresos generados, para tomar decisiones de reabastecimiento.',
    icon: 'trophy',
    route: '/admin/reports/products/product-top-sellers',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'product_id',
    columns: [
      { key: 'product_name', header: 'Producto', type: 'text' },
      { key: 'units_sold', header: 'Unidades Vendidas', type: 'number', footer: 'sum' },
      { key: 'revenue', header: 'Ingreso Total', type: 'currency', footer: 'sum' },
      { key: 'average_price', header: 'Precio Promedio', type: 'currency', footer: 'average' },
      { key: 'profit_margin', header: 'Margen', type: 'percentage', footer: 'average' },
    ],
    exportFilename: 'product_top_sellers',
    stats: [
      { key: 'units_sold', label: 'Unidades Vendidas', type: 'number', icon: 'trophy' },
      { key: 'revenue', label: 'Ingreso Total', type: 'currency', icon: 'dollar-sign' },
      { key: 'average_price', label: 'Precio Promedio', type: 'currency', icon: 'calculator' },
      { key: 'profit_margin', label: 'Margen', type: 'percentage', icon: 'percent' },
    ],
    dataEndpoint: 'store/analytics/products/top-sellers',
  },

  {
    id: 'product-profitability',
    category: 'products',
    title: 'Rentabilidad',
    description: 'Costo vs precio vs margen detallado de cada producto',
    detailedDescription:
      'Analisis de rentabilidad linea por linea. Compara precio de costo, precio de venta y margen real para optimizar tu catalogo de precios.',
    icon: 'percent',
    route: '/admin/reports/products/product-profitability',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'product_id',
    columns: [
      { key: 'product_name', header: 'Producto', type: 'text' },
      { key: 'revenue', header: 'Ingresos', type: 'currency', footer: 'sum' },
      { key: 'total_cost', header: 'Costo Total', type: 'currency', footer: 'sum' },
      { key: 'profit', header: 'Ganancia', type: 'currency', footer: 'sum' },
      { key: 'margin', header: 'Margen (%)', type: 'percentage', footer: 'average' },
      { key: 'units_sold', header: 'Unidades', type: 'number', footer: 'sum' },
    ],
    exportFilename: 'product_profitability',
    stats: [
      { key: 'revenue', label: 'Ingresos', type: 'currency', icon: 'dollar-sign' },
      { key: 'total_cost', label: 'Costo Total', type: 'currency', icon: 'trending-down' },
      { key: 'profit', label: 'Ganancia', type: 'currency', icon: 'trending-up' },
      { key: 'margin', label: 'Margen', type: 'percentage', icon: 'percent' },
    ],
    dataEndpoint: 'store/analytics/products/profitability',
    exportEndpoint: 'store/analytics/products/profitability/export',
  },

  // ─── CLIENTES (4) ─────────────────────────────────────────────────────────────

  {
    id: 'customer-summary',
    category: 'customers',
    title: 'Resumen de Clientes',
    description: 'Nuevos, activos, recurrentes y promedio de compra',
    detailedDescription:
      'Panorama general de tu base de clientes: cuantos son nuevos, cuantos repiten compra, y metricas clave como valor de vida del cliente y frecuencia de compra.',
    icon: 'users',
    route: '/admin/reports/customers/customer-summary',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'summary' as ReportType,
    summaryLayout: {
      fields: [
        { key: 'total_customers', label: 'Total Clientes', type: 'number' },
        { key: 'active_customers', label: 'Clientes Activos', type: 'number' },
        { key: 'new_customers', label: 'Clientes Nuevos', type: 'number' },
        { key: 'inactive_customers', label: 'Clientes Inactivos', type: 'number' },
        { key: 'average_spend', label: 'Gasto Promedio', type: 'currency' },
        { key: 'new_customers_growth', label: 'Crecimiento Nuevos', type: 'percentage' },
      ],
    },
    columns: [
      { key: 'metric', header: 'Metrica', type: 'text' },
      { key: 'value', header: 'Valor', type: 'number' },
      { key: 'change', header: 'Cambio', type: 'percentage' },
    ],
    exportFilename: 'customer_summary',
    stats: [
      { key: 'total_customers', label: 'Total Clientes', type: 'number', icon: 'users' },
      { key: 'active_customers', label: 'Clientes Activos', type: 'number', icon: 'user-check' },
      { key: 'new_customers', label: 'Clientes Nuevos', type: 'number', icon: 'user-plus' },
      { key: 'average_spend', label: 'Gasto Promedio', type: 'currency', icon: 'dollar-sign' },
    ],
    dataEndpoint: 'store/analytics/customers/summary',
    exportEndpoint: 'store/analytics/customers/export',
  },
  {
    id: 'customer-acquisition',
    category: 'customers',
    title: 'Adquisicion',
    description: 'Nuevos clientes y canales de adquisicion',
    detailedDescription: 'Rastrea nuevos clientes e identifica cuales canales estan trayendo mas conversiones.',
    icon: 'user-plus',
    route: '/admin/reports/customers/customer-acquisition',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'channel',
    columns: [
      { key: 'channel', header: 'Canal', type: 'text' },
      { key: 'orders', header: 'Ordenes', type: 'number', footer: 'sum' },
      { key: 'revenue', header: 'Ingreso', type: 'currency', footer: 'sum' },
      { key: 'percentage', header: 'Participacion', type: 'percentage' },
    ],
    exportFilename: 'adquisicion-clientes',
    stats: [
      { key: 'total_new_customers', label: 'Clientes Nuevos', type: 'number', icon: 'user-plus' },
      { key: 'total_revenue', label: 'Ingreso Total', type: 'currency', icon: 'dollar-sign' },
      { key: 'total_orders', label: 'Total Ordenes', type: 'number', icon: 'shopping-cart' },
      { key: '_count', label: 'Canales', type: 'number', icon: 'share-2' },
    ],
    dataEndpoint: 'store/analytics/customers/channels',
  },
  {
    id: 'customer-abandoned-carts',
    category: 'customers',
    title: 'Carritos Abandonados',
    description: 'Tasa de abandono y recuperacion de carritos',
    detailedDescription: 'Analiza la tasa de abandono de carritos y recupera ventas potenciales.',
    icon: 'shopping-cart',
    route: '/admin/reports/customers/customer-abandoned-carts',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'summary' as ReportType,
    summaryLayout: {
      fields: [
        { key: 'total_abandoned_carts', label: 'Carritos Abandonados', type: 'number' },
        { key: 'total_abandoned_value', label: 'Valor Abandonado', type: 'currency' },
        { key: 'recovery_rate', label: 'Tasa Recuperacion', type: 'percentage' },
        { key: 'recovered_value', label: 'Valor Recuperado', type: 'currency' },
      ],
    },
    columns: [
      { key: 'total_abandoned_carts', header: 'Carritos Abandonados', type: 'number' },
      { key: 'total_abandoned_value', header: 'Valor Abandonado', type: 'currency' },
      { key: 'recovery_rate', header: 'Tasa Recuperacion', type: 'percentage' },
      { key: 'recovered_value', header: 'Valor Recuperado', type: 'currency' },
    ],
    exportFilename: 'carritos-abandonados',
    stats: [
      { key: 'total_abandoned_carts', label: 'Carritos Abandonados', type: 'number', icon: 'shopping-cart' },
      { key: 'total_abandoned_value', label: 'Valor Total', type: 'currency', icon: 'dollar-sign' },
      { key: 'recovery_rate', label: 'Tasa Recuperacion', type: 'percentage', icon: 'rotate-ccw' },
      { key: 'recovered_value', label: 'Valor Recuperado', type: 'currency', icon: 'check-circle' },
    ],
    dataEndpoint: 'store/analytics/customers/abandoned-carts/summary',
    exportEndpoint: 'store/analytics/customers/abandoned-carts/export',
  },

  {
    // QUI-541: Top clientes por ventas. Reutiliza getTopCustomers (que ya
    // tiene groupBy sobre orders con COMPLETED_STATES) y exporta TODOS
    // los clientes con al menos una orden, no solo el top-10 que muestra
    // la pantalla. Diferencia con sales-by-customer: este vive en la
    // categoría 'customers' (análisis por cliente) y no incluye
    // ticket_promedio (eso lo calcula la vista de sales-by-customer).
    id: 'customers-top',
    category: 'customers',
    title: 'Top Clientes',
    description: 'Clientes con mayor gasto total en el período',
    detailedDescription:
      'Lista completa de clientes con al menos una orden completada en el período, ordenados por gasto total descendente. Útil para identificar clientes VIP y segmentar campañas.',
    icon: 'crown',
    route: '/admin/reports/customers/customers-top',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'id',
    columns: [
      { key: 'id', header: 'ID', type: 'number' },
      { key: 'customer_name', header: 'Cliente', type: 'text' },
      { key: 'email', header: 'Correo', type: 'text' },
      { key: 'total_orders', header: 'Órdenes', type: 'number', footer: 'sum' },
      { key: 'total_spent', header: 'Gasto Total', type: 'currency', footer: 'sum' },
      { key: 'last_order_date', header: 'Última Orden', type: 'date' },
    ],
    exportFilename: 'top_clientes',
    stats: [
      { key: 'total_spent', label: 'Gasto Total', type: 'currency', icon: 'dollar-sign' },
      { key: 'total_orders', label: 'Órdenes Totales', type: 'number', icon: 'shopping-cart' },
      { key: '_count', label: 'Clientes', type: 'number', icon: 'users' },
    ],
    dataEndpoint: 'store/analytics/customers/top',
    exportEndpoint: 'store/analytics/customers/top/export',
  },

  {
    // QUI-540: Cuentas por cobrar de clientes (open + partial) con
    // bucketing de antigüedad 0-30 / 31-60 / 61-90 / 90+.
    id: 'customers-receivable',
    category: 'customers',
    title: 'Cuentas por Cobrar',
    description: 'Cartera abierta con bucketing de antigüedad',
    detailedDescription:
      'Listado de cuentas por cobrar abiertas o parciales con su bucketing de antigüedad (corriente, 31-60, 61-90, 90+ días). Útil para priorizar gestión de cobro.',
    icon: 'hand-coins',
    route: '/admin/reports/customers/customers-receivable',
    requiresDateRange: false,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'id',
    columns: [
      { key: 'document_number', header: 'Documento', type: 'text' },
      { key: 'customer_name', header: 'Cliente', type: 'text' },
      { key: 'customer_document', header: 'NIT/Doc', type: 'text' },
      { key: 'issue_date', header: 'Emisión', type: 'date' },
      { key: 'due_date', header: 'Vencimiento', type: 'date' },
      { key: 'days_overdue', header: 'Días Mora', type: 'number' },
      { key: 'aging_bucket', header: 'Antigüedad', type: 'text' },
      { key: 'balance', header: 'Saldo', type: 'currency', footer: 'sum' },
      { key: 'status', header: 'Estado', type: 'text' },
    ],
    exportFilename: 'cuentas_por_cobrar',
    stats: [
      { key: 'balance', label: 'Saldo Total', type: 'currency', icon: 'dollar-sign' },
    ],
    dataEndpoint: 'store/analytics/customers/receivable',
    exportEndpoint: 'store/analytics/customers/receivable/export',
  },

  // ─── CONTABILIDAD (11) ────────────────────────────────────────────────────────

  {
    id: 'trial-balance',
    category: 'accounting',
    title: 'Balance de Prueba',
    description: 'Sumas y saldos por cuenta contable',
    detailedDescription:
      'Reporte contable fundamental que muestra los debitos y creditos totales de cada cuenta. Verifica que la contabilidad este balanceada.',
    icon: 'scale',
    route: '/admin/reports/accounting/trial-balance',
    requiresDateRange: true,
    requiresFiscalPeriod: true,
    type: 'summary' as ReportType,
    summaryLayout: {
      fields: [
        { key: 'total_debit', label: 'Total Debitos', type: 'currency' },
        { key: 'total_credit', label: 'Total Creditos', type: 'currency' },
      ],
    },
    columns: [
      { key: 'account_code', header: 'Codigo', type: 'text' },
      { key: 'account_name', header: 'Cuenta', type: 'text' },
      { key: 'total_debit', header: 'Debito', type: 'currency', footer: 'sum' },
      { key: 'total_credit', header: 'Credito', type: 'currency', footer: 'sum' },
      { key: 'balance', header: 'Saldo', type: 'currency', footer: 'sum' },
    ],
    exportFilename: 'trial_balance',
    stats: [
      { key: 'totals_total_debit', label: 'Total Debitos', type: 'currency', icon: 'arrow-up' },
      { key: 'totals_total_credit', label: 'Total Creditos', type: 'currency', icon: 'arrow-down' },
      { key: '_count', label: 'Total Cuentas', type: 'number', icon: 'list' },
      { key: 'balance', label: 'Saldo Neto', type: 'currency', icon: 'scale' },
    ],
    dataEndpoint: 'store/accounting/reports/trial-balance',
    fullViewRoute: '/admin/accounting/reports/trial-balance',
  },

  {
    id: 'balance-sheet',
    category: 'accounting',
    title: 'Balance General',
    description: 'Activos, pasivos y patrimonio de la empresa',
    detailedDescription:
      'Estado de situacion financiera: activos, pasivos y patrimonio neto. Fotografia de la salud financiera de tu negocio en un momento dado.',
    icon: 'landmark',
    route: '/admin/reports/accounting/balance-sheet',
    requiresDateRange: true,
    requiresFiscalPeriod: true,
    type: 'nested' as ReportType,
    trackKey: 'account_code',
    columns: [
      { key: 'account_code', header: 'Codigo', type: 'text' },
      { key: 'account_name', header: 'Cuenta', type: 'text' },
      { key: 'balance', header: 'Monto', type: 'currency', footer: 'sum' },
    ],
    exportFilename: 'balance_sheet',
    stats: [
      { key: 'total_assets', label: 'Total Activos', type: 'currency', icon: 'trending-up' },
      { key: 'total_liabilities', label: 'Total Pasivos', type: 'currency', icon: 'trending-down' },
      { key: 'total_equity', label: 'Patrimonio', type: 'currency', icon: 'landmark' },
      { key: '_count', label: 'Total Cuentas', type: 'number', icon: 'list' },
    ],
    dataEndpoint: 'store/accounting/reports/balance-sheet',
    fullViewRoute: '/admin/accounting/reports/balance-sheet',
  },

  {
    id: 'income-statement',
    category: 'accounting',
    title: 'Estado de Resultados',
    description: 'Ingresos menos gastos del periodo',
    detailedDescription:
      'Tu negocio genera ganancias? Este reporte muestra ingresos, costos y gastos para determinar la utilidad neta del periodo fiscal.',
    icon: 'file-bar-chart',
    route: '/admin/reports/accounting/income-statement',
    requiresDateRange: true,
    requiresFiscalPeriod: true,
    type: 'nested' as ReportType,
    trackKey: 'account_code',
    columns: [
      { key: 'account_code', header: 'Codigo', type: 'text' },
      { key: 'account_name', header: 'Cuenta', type: 'text' },
      { key: 'balance', header: 'Monto', type: 'currency', footer: 'sum' },
    ],
    exportFilename: 'income_statement',
    stats: [
      { key: 'total_revenue', label: 'Ingresos', type: 'currency', icon: 'trending-up' },
      { key: 'total_costs', label: 'Costos', type: 'currency', icon: 'trending-down' },
      { key: 'net_income', label: 'Utilidad Neta', type: 'currency', icon: 'dollar-sign' },
      { key: '_count', label: 'Total Cuentas', type: 'number', icon: 'list' },
    ],
    dataEndpoint: 'store/accounting/reports/income-statement',
    fullViewRoute: '/admin/accounting/reports/income-statement',
  },

  {
    id: 'general-ledger',
    category: 'accounting',
    title: 'Libro Mayor',
    description: 'Movimientos detallados por cuenta contable',
    detailedDescription:
      'Detalle completo de todos los movimientos contables por cuenta. Filtra por cuenta especifica para ver cada debito y credito registrado.',
    icon: 'book-open',
    route: '/admin/reports/accounting/general-ledger',
    requiresDateRange: true,
    requiresFiscalPeriod: true,
    type: 'list' as ReportType,
    trackKey: 'entry_number',
    columns: [
      { key: 'entry_date', header: 'Fecha', type: 'date' },
      { key: 'entry_number', header: 'No. Asiento', type: 'text' },
      { key: 'entry_description', header: 'Descripcion', type: 'text' },
      { key: 'debit_amount', header: 'Debito', type: 'currency', footer: 'sum' },
      { key: 'credit_amount', header: 'Credito', type: 'currency', footer: 'sum' },
      { key: 'running_balance', header: 'Saldo', type: 'currency' },
    ],
    exportFilename: 'general_ledger',
    stats: [
      { key: 'debit_amount', label: 'Total Debitos', type: 'currency', icon: 'arrow-up' },
      { key: 'credit_amount', label: 'Total Creditos', type: 'currency', icon: 'arrow-down' },
      { key: '_count', label: 'Total Asientos', type: 'number', icon: 'file-text' },
      { key: 'running_balance', label: 'Saldo', type: 'currency', icon: 'scale' },
    ],
    dataEndpoint: 'store/accounting/reports/general-ledger',
    fullViewRoute: '/admin/accounting/reports/general-ledger',
  },

  // ─── FINANCIERO (3) ───────────────────────────────────────────────────────────

  {
    id: 'tax-summary',
    category: 'financial',
    title: 'Resumen de Impuestos',
    description: 'IVA, retenciones e ICA del periodo',
    detailedDescription:
      'Consolidado de impuestos del periodo: IVA generado, IVA descontable, retenciones en la fuente, retencion de ICA y otros impuestos. Util para declaraciones tributarias.',
    icon: 'file-stack',
    route: '/admin/reports/financial/tax-summary',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'summary' as ReportType,
    summaryLayout: {
      fields: [
        { key: 'total_tax_collected', label: 'Impuestos Recaudados', type: 'currency' },
        { key: 'total_tax_refunded', label: 'Impuestos Reembolsados', type: 'currency' },
        { key: 'net_tax', label: 'Impuesto Neto', type: 'currency' },
        { key: 'total_taxable_revenue', label: 'Base Gravable', type: 'currency' },
        { key: 'effective_tax_rate', label: 'Tasa Efectiva', type: 'percentage' },
      ],
    },
    columns: [
      { key: 'tax_name', header: 'Tipo de Impuesto', type: 'text' },
      { key: 'taxable_amount', header: 'Base Gravable', type: 'currency', footer: 'sum' },
      { key: 'total_tax', header: 'Impuesto', type: 'currency', footer: 'sum' },
      { key: 'tax_rate', header: 'Tasa', type: 'percentage' },
    ],
    exportFilename: 'tax_summary',
    stats: [
      { key: 'total_tax_collected', label: 'Impuestos Recaudados', type: 'currency', icon: 'dollar-sign' },
      { key: 'total_tax_refunded', label: 'Impuestos Reembolsados', type: 'currency', icon: 'rotate-ccw' },
      { key: 'net_tax', label: 'Impuesto Neto', type: 'currency', icon: 'calculator' },
      { key: 'effective_tax_rate', label: 'Tasa Efectiva', type: 'percentage', icon: 'percent' },
    ],
    dataEndpoint: 'store/analytics/financial/tax-summary',
    exportEndpoint: 'store/analytics/financial/tax-summary/export',
  },

  {
    id: 'financial-refunds',
    category: 'financial',
    title: 'Reembolsos',
    description: 'Devoluciones y reembolsos procesados',
    detailedDescription: 'Controla las devoluciones y reembolsos para identificar problemas de calidad o servicio.',
    icon: 'rotate-ccw',
    route: '/admin/reports/financial/financial-refunds',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'refund_id',
    columns: [
      { key: 'order_id', header: 'Orden', type: 'text' },
      { key: 'customer_name', header: 'Cliente', type: 'text' },
      { key: 'amount', header: 'Monto', type: 'currency', footer: 'sum' },
      { key: 'reason', header: 'Motivo', type: 'text' },
      { key: 'status', header: 'Estado', type: 'text' },
      { key: 'created_at', header: 'Fecha', type: 'date' },
    ],
    exportFilename: 'reembolsos',
    stats: [
      { key: 'total_refunds', label: 'Total Reembolsos', type: 'currency', icon: 'dollar-sign' },
      { key: 'subtotal_refunds', label: 'Subtotal', type: 'currency', icon: 'rotate-ccw' },
      { key: 'tax_refunds', label: 'Impuestos', type: 'currency', icon: 'percent' },
      { key: 'shipping_refunds', label: 'Envios', type: 'currency', icon: 'truck' },
    ],
    dataEndpoint: 'store/analytics/financial/refunds',
  },

  {
    // QUI-543: Arqueo de caja. Listado de sesiones de caja con apertura,
    // cierre esperado vs real, y diferencia. El backend (FinancialAnalyticsService.
    // getCashSessionsForExport) ya devuelve los 12 campos en el shape canónico;
    // aquí solo se cablea el registry + ruta.
    id: 'cash-sessions',
    category: 'financial',
    title: 'Arqueo de Caja',
    description: 'Sesiones de caja con apertura, cierre esperado, real y diferencia',
    detailedDescription:
      'Detalle de cada sesión de caja: quién la abrió y cerró, monto de apertura, total de ventas y gastos, cierre esperado vs real, y la diferencia (descuadre). Útil para auditar cuadres diarios y detectar fugas.',
    icon: 'cash',
    route: '/admin/reports/financial/cash-sessions',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'opened_at',
    columns: [
      { key: 'opened_at', header: 'Apertura', type: 'date' },
      { key: 'closed_at', header: 'Cierre', type: 'date' },
      { key: 'register_name', header: 'Caja', type: 'text' },
      { key: 'opened_by_name', header: 'Abrió', type: 'text' },
      { key: 'closed_by_name', header: 'Cerró', type: 'text' },
      { key: 'opening_amount', header: 'Monto Apertura', type: 'currency' },
      { key: 'total_sales', header: 'Ventas', type: 'currency', footer: 'sum' },
      { key: 'total_expenses', header: 'Gastos', type: 'currency', footer: 'sum' },
      { key: 'expected_closing_amount', header: 'Cierre Esperado', type: 'currency' },
      { key: 'actual_closing_amount', header: 'Cierre Real', type: 'currency' },
      { key: 'difference', header: 'Diferencia', type: 'currency', footer: 'sum' },
      { key: 'status', header: 'Estado', type: 'text' },
    ],
    exportFilename: 'arqueo_caja',
    stats: [
      { key: 'total_sales', label: 'Total Ventas', type: 'currency', icon: 'dollar-sign' },
      { key: 'total_expenses', label: 'Total Gastos', type: 'currency', icon: 'trending-down' },
      { key: 'difference', label: 'Descuadre Total', type: 'currency', icon: 'alert-triangle' },
    ],
    dataEndpoint: 'store/analytics/financial/cash-sessions',
    exportEndpoint: 'store/analytics/financial/cash-sessions/export',
  },

  {
    // QUI-544: Resumen de gastos. Submódulo nuevo expenses/analytics/ con
    // 3 endpoints: summary, by-category, detail. Filtra por
    // RECOGNIZED_EXPENSE_STATES (approved|paid) por defecto.
    id: 'expenses-summary',
    category: 'financial',
    title: 'Resumen de Gastos',
    description: 'Totales de gastos aprobados y pagados del período',
    detailedDescription:
      'Resumen agregado de gastos del período: total reconocido, pendientes, count y promedio. Filtra por RECOGNIZED_EXPENSE_STATES (approved, paid); el estado pending NO cuenta como gasto del período.',
    icon: 'trending-down',
    route: '/admin/reports/financial/expenses-summary',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'summary' as ReportType,
    summaryLayout: {
      fields: [
        { key: 'total_recognized', label: 'Reconocidos', type: 'currency' },
        { key: 'total_pending', label: 'Pendientes', type: 'currency' },
        { key: 'average_expense', label: 'Promedio', type: 'currency' },
        { key: 'recognized_count', label: '# Reconocidos', type: 'number' },
      ],
    },
    columns: [
      { key: 'total_recognized', header: 'Reconocidos', type: 'currency' },
      { key: 'total_pending', header: 'Pendientes', type: 'currency' },
      { key: 'recognized_count', header: '# Reconocidos', type: 'number' },
      { key: 'pending_count', header: '# Pendientes', type: 'number' },
      { key: 'average_expense', header: 'Promedio', type: 'currency' },
    ],
    exportFilename: 'resumen_gastos',
    stats: [
      { key: 'total_recognized', label: 'Reconocidos', type: 'currency', icon: 'dollar-sign' },
      { key: 'total_pending', label: 'Pendientes', type: 'currency', icon: 'clock' },
      { key: 'average_expense', label: 'Promedio', type: 'currency', icon: 'calculator' },
      { key: 'recognized_count', label: '# Reconocidos', type: 'number', icon: 'check-circle' },
    ],
    dataEndpoint: 'store/analytics/expenses/summary',
    exportEndpoint: 'store/analytics/expenses/summary',
  },
  {
    id: 'expenses-by-category',
    category: 'financial',
    title: 'Gastos por Categoría',
    description: 'Desglose de gastos por categoría con % de participación',
    detailedDescription:
      'Para cada categoría de gasto, muestra el total, count, promedio y % de participación en el total del período. Útil para identificar dónde se va el dinero.',
    icon: 'pie-chart',
    route: '/admin/reports/financial/expenses-by-category',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'category_id',
    columns: [
      { key: 'category_name', header: 'Categoría', type: 'text' },
      { key: 'expense_count', header: 'Gastos', type: 'number', footer: 'sum' },
      { key: 'total_amount', header: 'Total', type: 'currency', footer: 'sum' },
      { key: 'average_expense', header: 'Promedio', type: 'currency' },
      { key: 'percentage', header: '% Participación', type: 'percentage' },
    ],
    exportFilename: 'gastos_por_categoria',
    stats: [
      { key: 'total_amount', label: 'Total', type: 'currency', icon: 'dollar-sign' },
      { key: 'expense_count', label: 'Gastos', type: 'number', icon: 'list' },
      { key: '_count', label: 'Categorías', type: 'number', icon: 'tag' },
    ],
    dataEndpoint: 'store/analytics/expenses/by-category',
    exportEndpoint: 'store/analytics/expenses/by-category',
  },
  {
    id: 'expenses-detail',
    category: 'financial',
    title: 'Detalle de Gastos',
    description: 'Listado crudo de gastos con categoría, aprobador y recibo',
    detailedDescription:
      'Cada gasto individual del período con su categoría, descripción, monto, estado, aprobador y link al recibo. Útil para auditoría.',
    icon: 'receipt',
    route: '/admin/reports/financial/expenses-detail',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'id',
    columns: [
      { key: 'expense_date', header: 'Fecha', type: 'date' },
      { key: 'category_name', header: 'Categoría', type: 'text' },
      { key: 'description', header: 'Descripción', type: 'text' },
      { key: 'amount', header: 'Monto', type: 'currency', footer: 'sum' },
      { key: 'state', header: 'Estado', type: 'text' },
      { key: 'is_recognized', header: 'Reconocido', type: 'text' },
      { key: 'created_by', header: 'Creado por', type: 'text' },
      { key: 'approved_by', header: 'Aprobado por', type: 'text' },
    ],
    exportFilename: 'detalle_gastos',
    stats: [
      { key: 'amount', label: 'Total', type: 'currency', icon: 'dollar-sign' },
    ],
    dataEndpoint: 'store/analytics/expenses/detail',
    exportEndpoint: 'store/analytics/expenses/detail',
  },

  {
    id: 'profit-loss',
    category: 'financial',
    title: 'Estado de Resultados',
    description: 'Ingreso neto del negocio en el periodo',
    detailedDescription:
      'El reporte mas importante para duenos de negocio: cuanto ganaste realmente? Ingresos por ventas menos costos de mercancia, gastos operativos y otros gastos.',
    icon: 'trending-up',
    route: '/admin/reports/financial/profit-loss',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'nested' as ReportType,
    trackKey: 'account_code',
    columns: [
      { key: 'concept', header: 'Concepto', type: 'text' },
      { key: 'amount', header: 'Monto', type: 'currency', footer: 'sum' },
      { key: 'percentage', header: 'Porcentaje', type: 'percentage' },
    ],
    exportFilename: 'profit_loss',
    stats: [
      { key: 'gross_revenue', label: 'Ingresos Brutos', type: 'currency', icon: 'trending-up' },
      { key: 'cogs', label: 'Costo Mercancia', type: 'currency', icon: 'trending-down' },
      { key: 'net_profit', label: 'Utilidad Neta', type: 'currency', icon: 'dollar-sign' },
      { key: 'net_margin', label: 'Margen Neto', type: 'percentage', icon: 'percent' },
    ],
    dataEndpoint: 'store/analytics/financial/profit-loss',
    exportEndpoint: 'store/analytics/financial/export',
  },

  // ─── NÓMINA (3) ───────────────────────────────────────────────────────────────

  {
    id: 'payroll-summary',
    category: 'payroll',
    title: 'Resumen de Nómina',
    description: 'Devengados, deducciones, costos patronales y neto por período',
    detailedDescription:
      'Consolidado de las corridas de nómina del período: total devengado, deducciones, costos patronales, pago neto y número de empleados por período liquidado.',
    icon: 'banknote',
    route: '/admin/reports/payroll/payroll-summary',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'payroll_number',
    columns: [
      { key: 'period', header: 'Período', type: 'text' },
      { key: 'payroll_number', header: 'No. Nómina', type: 'text' },
      { key: 'employee_count', header: 'Empleados', type: 'number', footer: 'sum' },
      { key: 'total_earnings', header: 'Devengado', type: 'currency', footer: 'sum' },
      { key: 'total_deductions', header: 'Deducciones', type: 'currency', footer: 'sum' },
      { key: 'employer_costs', header: 'Costos Patronales', type: 'currency', footer: 'sum' },
      { key: 'net_pay', header: 'Neto', type: 'currency', footer: 'sum' },
    ],
    exportFilename: 'resumen-nomina',
    stats: [
      { key: 'total_earnings', label: 'Total Devengado', type: 'currency', icon: 'banknote' },
      { key: 'total_deductions', label: 'Total Deducciones', type: 'currency', icon: 'trending-down' },
      { key: 'employer_costs', label: 'Costos Patronales', type: 'currency', icon: 'coins' },
      { key: 'net_pay', label: 'Total Neto', type: 'currency', icon: 'dollar-sign' },
    ],
    dataEndpoint: 'store/reports/payroll/summary',
  },

  {
    id: 'payroll-by-employee',
    category: 'payroll',
    title: 'Nómina por Empleado',
    description: 'Detalle de devengados, deducciones y neto por empleado',
    detailedDescription:
      'Desglose por empleado de la nómina liquidada en el período: salario base, días trabajados, devengados, deducciones y pago neto.',
    icon: 'users',
    route: '/admin/reports/payroll/payroll-by-employee',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'employee_name',
    columns: [
      { key: 'employee_name', header: 'Empleado', type: 'text' },
      { key: 'position', header: 'Cargo', type: 'text' },
      { key: 'department', header: 'Departamento', type: 'text' },
      { key: 'base_salary', header: 'Salario Base', type: 'currency' },
      { key: 'earnings', header: 'Devengado', type: 'currency', footer: 'sum' },
      { key: 'deductions', header: 'Deducciones', type: 'currency', footer: 'sum' },
      { key: 'net_pay', header: 'Neto', type: 'currency', footer: 'sum' },
    ],
    exportFilename: 'nomina-por-empleado',
    stats: [
      { key: 'earnings', label: 'Total Devengado', type: 'currency', icon: 'banknote' },
      { key: 'deductions', label: 'Total Deducciones', type: 'currency', icon: 'trending-down' },
      { key: 'net_pay', label: 'Total Neto', type: 'currency', icon: 'dollar-sign' },
      { key: '_count', label: 'Registros', type: 'number', icon: 'users' },
    ],
    dataEndpoint: 'store/reports/payroll/by-employee',
  },

  {
    id: 'payroll-provisions',
    category: 'payroll',
    title: 'Provisiones Laborales',
    description: 'Cesantías, intereses, primas y vacaciones acumuladas',
    detailedDescription:
      'Provisiones laborales acumuladas por empleado activo: cesantías, intereses a las cesantías, prima de servicios y vacaciones, con el total provisionado.',
    icon: 'piggy-bank',
    route: '/admin/reports/payroll/payroll-provisions',
    requiresDateRange: true,
    requiresFiscalPeriod: false,
    type: 'list' as ReportType,
    trackKey: 'employee_name',
    columns: [
      { key: 'employee_name', header: 'Empleado', type: 'text' },
      { key: 'base_salary', header: 'Salario Base', type: 'currency' },
      { key: 'severance', header: 'Cesantías', type: 'currency', footer: 'sum' },
      { key: 'severance_interest', header: 'Int. Cesantías', type: 'currency', footer: 'sum' },
      { key: 'bonus', header: 'Prima', type: 'currency', footer: 'sum' },
      { key: 'vacation', header: 'Vacaciones', type: 'currency', footer: 'sum' },
      { key: 'total_provisions', header: 'Total Provisiones', type: 'currency', footer: 'sum' },
    ],
    exportFilename: 'provisiones-laborales',
    stats: [
      { key: 'severance', label: 'Cesantías', type: 'currency', icon: 'piggy-bank' },
      { key: 'bonus', label: 'Prima', type: 'currency', icon: 'coins' },
      { key: 'vacation', label: 'Vacaciones', type: 'currency', icon: 'calendar' },
      { key: 'total_provisions', label: 'Total Provisiones', type: 'currency', icon: 'dollar-sign' },
    ],
    dataEndpoint: 'store/reports/payroll/provisions',
  },
];

// ─── HELPERS ──────────────────────────────────────────────────────────────────

export function getReportById(id: string): ReportDefinition | undefined {
  return REPORT_DEFINITIONS.find((report) => report.id === id);
}

export function getReportsByCategory(categoryId: ReportCategoryId): ReportDefinition[] {
  return REPORT_DEFINITIONS.filter((report) => report.category === categoryId);
}

export function getCategoryById(id: ReportCategoryId): ReportCategory | undefined {
  return REPORT_CATEGORIES.find((category) => category.id === id);
}

export function getDefaultReportForCategory(categoryId: ReportCategoryId): ReportDefinition | undefined {
  return getReportsByCategory(categoryId)[0];
}
