export const API_BASE_URL = process.env.EXPO_PUBLIC_API_URL || 'http://10.163.174.41:3000/api';

export const Endpoints = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register-owner',
    LOGOUT: '/auth/logout',
    REFRESH: '/auth/refresh',
    FORGOT_PASSWORD: '/auth/forgot-owner-password',
    RESET_PASSWORD: '/auth/reset-owner-password',
    VERIFY_TOKEN: '/auth/verify-token',
    ME: '/auth/me',
    PROFILE: '/auth/profile',
    SETTINGS: '/auth/settings',
  },
  STORE: {
    DASHBOARD_STATS: '/store/stores/dashboard/stats',
    PRODUCTS: {
      LIST: '/store/products',
      GET: '/store/products/:id',
      CREATE: '/store/products',
      UPDATE: '/store/products/:id',
      DELETE: '/store/products/:id',
      SEARCH: '/store/products/search',
      STATS: '/store/products/stats/store/:storeId',
      DEACTIVATE: '/store/products/:id/deactivate',
      VARIANTS: '/store/products/:productId/variants',
      VARIANT_CREATE: '/store/products/:productId/variants',
      VARIANT_UPDATE: '/store/products/variants/:variantId',
      VARIANT_DELETE: '/store/products/variants/:variantId',
      IMAGES: '/store/products/:productId/images',
      IMAGE_DELETE: '/store/products/images/:imageId',
      IMAGE_SET_MAIN: '/store/products/:productId/images/:imageId/main',
      BY_CATEGORY: '/store/products/category/:categoryId',
      BY_BRAND: '/store/products/brand/:brandId',
      LOW_STOCK: '/store/products/low-stock/:threshold',
      GENERATE_DESCRIPTION: '/store/products/generate-description',
      PROMOTIONS: '/store/products/:productId/promotions',
    },
    ORDERS: {
      LIST: '/store/orders',
      GET: '/store/orders/:id',
      CREATE: '/store/orders',
      UPDATE: '/store/orders/:id',
      DELETE: '/store/orders/:id',
      STATS: '/store/orders/stats',
      TIMELINE: '/store/orders/:id/timeline',
      FLOW_PAY: '/store/orders/:id/flow/pay',
      FLOW_SHIP: '/store/orders/:id/flow/ship',
      FLOW_DELIVER: '/store/orders/:id/flow/deliver',
      FLOW_CANCEL: '/store/orders/:id/flow/cancel',
      FLOW_REFUND: '/store/orders/:id/flow/refund',
      FLOW_REFUND_PREVIEW: '/store/orders/:id/flow/refund/preview',
      FLOW_FAST_TRACK: '/store/orders/:id/flow/fast-track',
      FLOW_CONFIRM_PAYMENT: '/store/orders/:id/flow/confirm-payment',
      ITEMS_UPDATE: '/store/orders/:id/items',
      SHIPPING_ASSIGN: '/store/orders/:id/shipping',
      REFUNDS: '/store/orders/:id/refunds',
    },
    ANALYTICS: {
      SALES_SUMMARY: '/store/analytics/sales/summary',
      SALES_TRENDS: '/store/analytics/sales/trends',
      SALES_BY_CHANNEL: '/store/analytics/sales/by-channel',
      INVENTORY_SUMMARY: '/store/analytics/inventory/summary',
    },
    CUSTOMERS: {
      LIST: '/store/customers',
      GET: '/store/customers/:id',
      CREATE: '/store/customers',
      SEARCH: '/store/customers/search',
    },
    CATEGORIES: {
      LIST: '/store/categories',
      CREATE: '/store/categories',
    },
    BRANDS: {
      LIST: '/store/brands',
      CREATE: '/store/brands',
    },
    TAXES: {
      LIST: '/store/taxes',
      CATEGORIES: '/store/taxes/categories',
    },
    PAYMENT_METHODS: {
      LIST: '/store/payments/methods',
    },
    CASH_REGISTERS: {
      LIST: '/store/cash-registers',
      SESSIONS: '/store/cash-registers/sessions',
    },
    STORES: {
      LIST: '/store/stores',
      GET: '/store/stores/:id',
      STATS: '/store/stores/stats',
      SETTINGS: '/store/stores/:id/settings',
    },
  },
} as const;

export type EndpointKey = keyof typeof Endpoints;
