export const API_BASE_URL = process.env.EXPO_PUBLIC_API_URL || 'https://api.vendix.online/api';

export const Endpoints = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register-owner',
    LOGOUT: '/auth/logout',
    REFRESH: '/auth/refresh',
    FORGOT_PASSWORD: '/auth/forgot-owner-password',
    RESET_PASSWORD: '/auth/reset-owner-password',
    VERIFY_TOKEN: '/auth/verify-token',
    ME: '/auth/me',
    PROFILE: '/auth/profile',
    SETTINGS: '/auth/settings',
    SWITCH_ENVIRONMENT: '/auth/switch-environment',
  },
  STORE: {
    DASHBOARD_STATS: '/store/stores/dashboard/stats',
    PRODUCTS: {
      LIST: '/store/products',
      GET: '/store/products/:id',
      CREATE: '/store/products',
      UPDATE: '/store/products/:id',
      DELETE: '/store/products/:id',
      SEARCH: '/store/products',
      STATS: '/store/products/stats/store/:storeId',
      DEACTIVATE: '/store/products/:id/deactivate',
      VARIANTS: '/store/products/:productId/variants',
      VARIANT_CREATE: '/store/products/:productId/variants',
      VARIANT_UPDATE: '/store/products/variants/:variantId',
      VARIANT_DELETE: '/store/products/variants/:variantId',
      IMAGES: '/store/products/:productId/images',
      IMAGE_DELETE: '/store/products/images/:imageId',
      IMAGE_SET_MAIN: '/store/products/:productId/images/:imageId/main',
      BY_CATEGORY: '/store/products/category/:categoryId',
      BY_BRAND: '/store/products/brand/:brandId',
      LOW_STOCK: '/store/products/low-stock/:threshold',
      GENERATE_DESCRIPTION: '/store/products/generate-description',
      PROMOTIONS: '/store/products/:id/promotions',
      BULK_UPLOAD: '/store/products/bulk-upload',
      BULK_IMAGE_UPLOAD: '/store/products/bulk-image-upload',
      BULK_IMAGES_TEMPLATE: '/store/products/bulk-images/template/download',
      BULK_IMAGES_ANALYZE: '/store/products/bulk-images/analyze',
      BULK_IMAGES_UPLOAD_SESSION: '/store/products/bulk-images/upload-session',
      BULK_IMAGES_CANCEL_SESSION: '/store/products/bulk-images/session/:sessionId',
      BULK_TEMPLATE_DOWNLOAD: '/store/products/bulk/template/download',
      BULK_EXPORT: '/store/products/bulk/export',
      BULK_ANALYZE: '/store/products/bulk/analyze',
      BULK_UPLOAD_SESSION: '/store/products/bulk/upload-session',
      BULK_CANCEL_SESSION: '/store/products/bulk/session/:sessionId',
    },
    ORDERS: {
      LIST: '/store/orders',
      GET: '/store/orders/:id',
      CREATE: '/store/orders',
      UPDATE: '/store/orders/:id',
      DELETE: '/store/orders/:id',
      STATS: '/store/orders/stats',
      TIMELINE: '/store/orders/:id/timeline',
      FLOW_PAY: '/store/orders/:id/flow/pay',
      FLOW_SHIP: '/store/orders/:id/flow/ship',
      FLOW_DELIVER: '/store/orders/:id/flow/deliver',
      FLOW_CANCEL: '/store/orders/:id/flow/cancel',
      FLOW_REFUND: '/store/orders/:id/flow/refund',
      FLOW_REFUND_PREVIEW: '/store/orders/:id/flow/refund/preview',
      FLOW_FAST_TRACK: '/store/orders/:id/flow/fast-track',
      FLOW_CONFIRM_PAYMENT: '/store/orders/:id/flow/confirm-payment',
      ITEMS_UPDATE: '/store/orders/:id/items',
      SHIPPING_ASSIGN: '/store/orders/:id/shipping',
      REFUNDS: '/store/orders/:id/refunds',
    },
    PRICE_TIERS: {
      LIST: '/store/price-tiers',
    },
    ANALYTICS: {
      SALES_SUMMARY: '/store/analytics/sales/summary',
      SALES_TRENDS: '/store/analytics/sales/trends',
      SALES_BY_CHANNEL: '/store/analytics/sales/by-channel',
      INVENTORY_SUMMARY: '/store/analytics/inventory/summary',
      OVERVIEW: '/store/analytics/overview',
      SALES: '/store/analytics/sales',
      INVENTORY: '/store/analytics/inventory',
      FINANCIAL: '/store/analytics/financial',
    },
    CUSTOMERS: {
      LIST: '/store/customers',
      GET: '/store/customers/:id',
      CREATE: '/store/customers',
      UPDATE: '/store/customers/:id',
      DELETE: '/store/customers/:id',
      SEARCH: '/store/customers',
      STATS: '/store/customers/stats/store/:storeId',
      TOPUP: '/store/customers/:id/topup',
    },
    CATEGORIES: {
      LIST: '/store/categories',
      GET: '/store/categories/:id',
      CREATE: '/store/categories',
      UPDATE: '/store/categories/:id',
      DELETE: '/store/categories/:id',
      UPLOAD_IMAGE: '/store/categories/upload-image',
    },
    BRANDS: {
      LIST: '/store/brands',
      GET: '/store/brands/:id',
      CREATE: '/store/brands',
      UPDATE: '/store/brands/:id',
      DELETE: '/store/brands/:id',
      UPLOAD_LOGO: '/store/brands/upload-logo',
    },
    TAXES: {
      // El backend expone las categorías en `/store/taxes` (no `/store/taxes/categories`).
      LIST: '/store/taxes',
      CATEGORIES: '/store/taxes',
      CATEGORY_CREATE: '/store/taxes',
      CATEGORY_UPDATE: '/store/taxes/:id',
      CATEGORY_DELETE: '/store/taxes/:id',
    },
    PAYMENT_METHODS: {
      LIST: '/store/payments/payment-methods',
    },
    PAYMENTS: {
      POS: '/store/payments/pos',
    },
    PROMOTIONS: {
      LIST: '/store/promotions',
      ACTIVE: '/store/promotions/active',
      GET: '/store/promotions/:id',
    },
    CASH_REGISTERS: {
      LIST: '/store/cash-registers',
      SESSIONS: '/store/cash-registers/sessions',
    },
    QUOTATIONS: {
      LIST: '/store/quotations',
      GET: '/store/quotations/:id',
      CREATE: '/store/quotations',
      UPDATE: '/store/quotations/:id',
      DELETE: '/store/quotations/:id',
      STATS: '/store/quotations/stats',
      SEND: '/store/quotations/:id/send',
      ACCEPT: '/store/quotations/:id/accept',
      REJECT: '/store/quotations/:id/reject',
      CANCEL: '/store/quotations/:id/cancel',
      CONVERT: '/store/quotations/:id/convert',
      DUPLICATE: '/store/quotations/:id/duplicate',
    },
    SHIPPING_METHODS: {
      LIST: '/store/shipping-methods',
      ENABLE: '/store/shipping-methods/enable',
    },
    INVOICES: {
      LIST: '/store/invoices',
      GET: '/store/invoices/:id',
      CREATE: '/store/invoices',
      STATS: '/store/invoices/stats',
      SEND: '/store/invoices/:id/send',
      VOID: '/store/invoices/:id/void',
      RESOLUTIONS: '/store/invoices/resolutions',
      CREATE_RESOLUTION: '/store/invoices/resolutions',
      DIAN_CONFIG: '/store/invoices/dian-config',
    },
    STORES: {
      LIST: '/store/stores',
      GET: '/store/stores/:id',
      STATS: '/store/stores/stats',
      SETTINGS: '/store/stores/:id/settings',
    },
    SETTINGS: {
      GET: '/store/settings',
      UPDATE: '/store/settings',
      USERS_LIST: '/store/settings/users',
      USER_CREATE: '/store/settings/users',
      USER_UPDATE: '/store/settings/users/:id',
      USER_TOGGLE_STATE: '/store/settings/users/:id/state',
      ROLES_LIST: '/store/settings/roles',
      ROLE_CREATE: '/store/settings/roles',
      ROLE_UPDATE: '/store/settings/roles/:id',
      ROLE_DELETE: '/store/settings/roles/:id',
    },
    INVENTORY: {
      STATS: '/store/inventory/stats',
      ADJUSTMENTS: {
        LIST: '/store/inventory/adjustments',
        CREATE: '/store/inventory/adjustments/batch-complete',
        CREATE_DRAFT: '/store/inventory/adjustments/batch',
        APPROVE: '/store/inventory/adjustments/:id/approve',
        DELETE: '/store/inventory/adjustments/:id',
        BULK_TEMPLATE: '/store/inventory/adjustments/bulk/template/download',
        BULK_UPLOAD: '/store/inventory/adjustments/bulk/upload',
      },
      TRANSFERS: {
        LIST: '/store/stock-transfers',
        CREATE: '/store/stock-transfers',
        APPROVE: '/store/stock-transfers/:id/approve',
        CANCEL: '/store/stock-transfers/:id/cancel',
        COMPLETE: '/store/stock-transfers/:id/complete',
      },
      MOVEMENTS: {
        LIST: '/store/inventory/movements',
      },
      SUPPLIERS: {
        LIST: '/store/inventory/suppliers',
        CREATE: '/store/inventory/suppliers',
        UPDATE: '/store/inventory/suppliers/:id',
        DELETE: '/store/inventory/suppliers/:id',
      },
      LOCATIONS: {
        LIST: '/store/inventory/locations',
        CREATE: '/store/inventory/locations',
        UPDATE: '/store/inventory/locations/:id',
        DELETE: '/store/inventory/locations/:id',
      },
      CONSOLIDATED_STOCK: '/store/inventory/consolidated-stock/product/:productId',
      STOCK_ALERTS: '/store/inventory/stock-levels/alerts',
      SOURCING_SUGGESTION: '/store/inventory/stock-levels/sourcing-suggestion',
    },
    PURCHASE_ORDERS: {
      LIST: '/store/orders/purchase-orders',
      GET: '/store/orders/purchase-orders/:id',
      CREATE: '/store/orders/purchase-orders',
      UPDATE: '/store/orders/purchase-orders/:id',
      RECEIVE: '/store/orders/purchase-orders/:id/receive',
      COST_PREVIEW: '/store/orders/purchase-orders/cost-preview',
    },
    ACCOUNTING: {
      ACCOUNTS: {
        LIST: '/store/accounting/accounts',
        CREATE: '/store/accounting/accounts',
        UPDATE: '/store/accounting/accounts/:id',
        DELETE: '/store/accounting/accounts/:id',
      },
      JOURNAL_ENTRIES: {
        LIST: '/store/accounting/journal-entries',
        GET: '/store/accounting/journal-entries/:id',
        CREATE: '/store/accounting/journal-entries',
      },
      FISCAL_PERIODS: {
        LIST: '/store/accounting/fiscal-periods',
        CREATE: '/store/accounting/fiscal-periods',
      },
      RECEIVABLES: {
        LIST: '/store/accounting/receivables',
        PAY: '/store/accounting/receivables/:id/pay',
      },
      PAYABLES: {
        LIST: '/store/accounting/payables',
        PAY: '/store/accounting/payables/:id/pay',
      },
    },
  },
  HELP_CENTER: '/help-center',
  NOTIFICATIONS: '/store/notifications',
  ORGANIZATION: {
    STORES: {
      LIST: '/organization/stores',
      CREATE: '/organization/stores',
      GET: '/organization/stores/:id',
      UPDATE: '/organization/stores/:id',
      DELETE: '/organization/stores/:id',
      STATS: '/organization/stores/stats',
      SETTINGS: '/organization/stores/:id/settings',
      SETTINGS_RESET: '/organization/stores/:id/settings/reset',
      DASHBOARD: '/organization/stores/:id/stats',
      CHECK_CODE: '/organization/stores/check-code',
    },
    USERS: {
      LIST: '/organization/users',
      GET: '/organization/users/:id',
      CREATE: '/organization/users',
      UPDATE: '/organization/users/:id',
      DELETE: '/organization/users/:id',
      TOGGLE_STATE: '/organization/users/:id/state',
      RESET_PASSWORD: '/organization/users/:id/reset-password',
      INVITE: '/organization/users/invite',
      VERIFY_EMAIL: '/organization/users/:id/verify-email',
      STATS: '/organization/users/stats',
      ASSIGN_TO_USER: '/organization/users/assign-to-user',
      REMOVE_FROM_USER: '/organization/users/remove-from-user',
      CONFIGURATION: '/organization/users/:id/configuration',
      ARCHIVE: '/organization/users/:id/archive',
      REACTIVATE: '/organization/users/:id/reactivate',
    },
    ROLES: {
      LIST: '/organization/roles',
      GET: '/organization/roles/:id',
      CREATE: '/organization/roles',
      UPDATE: '/organization/roles/:id',
      DELETE: '/organization/roles/:id',
      PERMISSIONS: '/organization/roles/:id/permissions',
      USER_PERMISSIONS: '/organization/roles/user/:userId/permissions',
      USER_ROLES: '/organization/roles/user/:userId/roles',
    },
    ORDERS: {
      LIST: '/organization/orders',
      GET: '/organization/orders/:id',
      STATS: '/organization/orders/stats',
      BY_STORE: '/organization/orders/by-store',
    },
    DASHBOARD: {
      STATS: '/organization/stores/stats',
      RECENT: '/organization/orders/recent',
    },
    SUBSCRIPTIONS: {
      LIST: '/organization/subscriptions',
      GET: '/organization/subscriptions/:id',
      PLANS: '/organization/subscriptions/plans',
      CURRENT: '/organization/subscriptions/current',
      USAGE: '/organization/subscriptions/usage',
    },
    DOMAINS: {
      LIST: '/organization/domains',
      GET: '/organization/domains/:id',
      CREATE: '/organization/domains',
      UPDATE: '/organization/domains/:id',
      DELETE: '/organization/domains/:id',
      VERIFY: '/organization/domains/:id/verify',
      DNS_INSTRUCTIONS: '/organization/domains/dns-instructions/:hostname',
      ROOTS: '/organization/domains/roots',
      ROOTS_DNS: '/organization/domains/roots/:rootId/dns-instructions',
      PROVISION_NEXT: '/organization/domains/roots/:rootId/provision-next',
      VERIFY_ROOT: '/organization/domains/roots/:rootId/verify',
      CHECK_DUPLICATE: '/organization/domains/hostname/:hostname/duplicate',
      VALIDATE_HOSTNAME: '/organization/domains/validate-hostname',
    },
    AUDIT: {
      LOGS: '/organization/audit/logs',
      LOGIN_ATTEMPTS: '/organization/audit/login-attempts',
      SESSIONS: '/organization/audit/sessions',
      SESSIONS_USER: '/organization/audit/sessions/user/:userId',
      STATS: '/organization/audit/stats',
    },
    ACCOUNTING: {
      CHART_OF_ACCOUNTS: {
        LIST: '/organization/accounting/chart-of-accounts',
        TREE: '/organization/accounting/chart-of-accounts/tree',
        GET: '/organization/accounting/chart-of-accounts/:id',
        CREATE: '/organization/accounting/chart-of-accounts',
        UPDATE: '/organization/accounting/chart-of-accounts/:id',
        DELETE: '/organization/accounting/chart-of-accounts/:id',
      },
      JOURNAL_ENTRIES: {
        LIST: '/organization/accounting/journal-entries',
        GET: '/organization/accounting/journal-entries/:id',
        CREATE: '/organization/accounting/journal-entries',
        POST: '/organization/accounting/journal-entries/:id/post',
        VOID: '/organization/accounting/journal-entries/:id/void',
      },
      FISCAL_PERIODS: {
        LIST: '/organization/accounting/fiscal-periods',
        GET: '/organization/accounting/fiscal-periods/:id',
        CREATE: '/organization/accounting/fiscal-periods',
        CLOSE: '/organization/accounting/fiscal-periods/:id/close',
        REACTIVATE: '/organization/accounting/fiscal-periods/:id/reactivate',
      },
      ACCOUNT_MAPPINGS: {
        LIST: '/organization/accounting/mappings',
        GET: '/organization/accounting/mappings/:id',
        CREATE: '/organization/accounting/mappings',
        UPDATE: '/organization/accounting/mappings/:id',
        DELETE: '/organization/accounting/mappings/:id',
      },
    },
    INVENTORY: {
      STOCK_LEVELS: {
        LIST: '/organization/inventory/stock-levels',
        STATS: '/organization/inventory/stock-levels/stats',
        ALERTS: '/organization/inventory/stock-levels/alerts',
        LOW_STOCK: '/organization/inventory/stock-levels/low-stock',
        BY_STORE: '/organization/inventory/stock-levels/store/:storeId',
        BY_PRODUCT: '/organization/inventory/stock-levels/product/:productId',
        UPDATE: '/organization/inventory/stock-levels',
      },
      LOCATIONS: {
        LIST: '/organization/inventory/locations',
        GET: '/organization/inventory/locations/:id',
        CREATE: '/organization/inventory/locations',
        UPDATE: '/organization/inventory/locations/:id',
        DELETE: '/organization/inventory/locations/:id',
        CENTRAL_WAREHOUSE: '/organization/inventory/locations/central-warehouse/ensure',
      },
      MOVEMENTS: {
        LIST: '/organization/inventory/movements',
        GET: '/organization/inventory/movements/:id',
        RECENT: '/organization/inventory/movements/recent',
      },
      SUPPLIERS: {
        LIST: '/organization/inventory/suppliers',
        GET: '/organization/inventory/suppliers/:id',
        CREATE: '/organization/inventory/suppliers',
        UPDATE: '/organization/inventory/suppliers/:id',
        DELETE: '/organization/inventory/suppliers/:id',
      },
      TRANSFERS: {
        LIST: '/organization/inventory/transfers',
        GET: '/organization/inventory/transfers/:id',
        CREATE: '/organization/inventory/transfers',
        DISPATCH: '/organization/inventory/transfers/:id/dispatch',
        CANCEL: '/organization/inventory/transfers/:id/cancel',
      },
      ADJUSTMENTS: {
        LIST: '/organization/inventory/adjustments',
        GET: '/organization/inventory/adjustments/:id',
        CREATE: '/organization/inventory/adjustments',
        APPROVE: '/organization/inventory/adjustments/:id/approve',
      },
      SERIAL_NUMBERS: {
        LIST: '/organization/inventory/serial-numbers',
        GET: '/organization/inventory/serial-numbers/:id',
        CREATE: '/organization/inventory/serial-numbers',
      },
      BATCHES: {
        LIST: '/organization/inventory/batches',
        GET: '/organization/inventory/batches/:id',
        EXPIRING_SOON: '/organization/inventory/batches/expiring-soon',
      },
      TRANSACTIONS: {
        LIST: '/organization/inventory/transactions',
      },
    },
    PURCHASE_ORDERS: {
      LIST: '/organization/purchase-orders',
      GET: '/organization/purchase-orders/:id',
      CREATE: '/organization/purchase-orders',
      UPDATE: '/organization/purchase-orders/:id',
      APPROVE: '/organization/purchase-orders/:id/approve',
      CANCEL: '/organization/purchase-orders/:id/cancel',
      RECEIVE: '/organization/purchase-orders/:id/receive',
    },
    PAYROLL: {
      SETTINGS_GET: '/organization/payroll/settings',
      SETTINGS_UPDATE: '/organization/payroll/settings',
      EMPLOYEES: '/organization/payroll/employees',
      PERIODS: '/organization/payroll/periods',
      PROVISIONS: '/organization/payroll/provisions',
      RUN_PAYROLL: '/organization/payroll/run',
    },
    INVOICING: {
      INVOICES: '/organization/invoicing/invoices',
      INVOICE_GET: '/organization/invoicing/invoices/:id',
      INVOICE_PDF: '/organization/invoicing/invoices/:invoiceId/pdf',
      RESOLUTIONS: '/organization/invoicing/resolutions',
      RESOLUTION_GET: '/organization/invoicing/resolutions/:id',
      DIAN_CONFIG: '/organization/invoicing/dian-config',
      DIAN_CONFIG_GET: '/organization/invoicing/dian-config/:id',
      DIAN_CONFIG_UPLOAD_CERT: '/organization/invoicing/dian-config/:id/upload-certificate',
      DIAN_CONFIG_REQUEST_CERT: '/organization/invoicing/dian-config/:id/certificate/request',
      DIAN_CONFIG_STATUS: '/organization/invoicing/dian-config/:id/certificate/status',
    },
    REPORTS: {
      SALES: '/organization/reports/sales',
      SALES_BY_CHANNEL: '/organization/reports/sales/by-channel',
      SALES_BY_STORE: '/organization/reports/sales/by-store',
      SALES_TOP_PRODUCTS: '/organization/reports/sales/top-products',
      INVENTORY: '/organization/reports/inventory',
      INVENTORY_VALUATION: '/organization/reports/inventory/valuation',
      FINANCIAL: '/organization/reports/financial',
      FINANCIAL_INCOME: '/organization/reports/financial/income-statement',
      FINANCIAL_BALANCE: '/organization/reports/financial/balance-sheet',
      FINANCIAL_TRIAL: '/organization/reports/financial/trial-balance',
      FINANCIAL_LEDGER: '/organization/reports/financial/general-ledger',
      PAYROLL: '/organization/reports/payroll',
      PAYROLL_BY_EMPLOYEE: '/organization/reports/payroll/by-employee',
    },
    FISCAL: {
      DASHBOARD: '/organization/fiscal/dashboard',
      OBLIGATIONS: '/organization/fiscal/obligations',
      DECLARATIONS: '/organization/fiscal/declarations',
      CLOSE: '/organization/fiscal/close',
      EVIDENCE: '/organization/fiscal/evidence',
      HISTORY: '/organization/fiscal/history',
      RULES: '/organization/fiscal/rules',
      WIZARD_START: '/organization/onboarding-wizard/:area/start-wizard',
      WIZARD_STEP: '/organization/onboarding-wizard/:area/mark-step-completed',
      WIZARD_DEACTIVATE: '/organization/onboarding-wizard/:area/deactivate',
      WIZARD_FINALIZE: '/organization/onboarding-wizard/:area/finalize',
      WIZARD_IRREVERSIBILITY: '/organization/onboarding-wizard/:area/irreversibility-check',
      WIZARD_PREFLL: '/organization/onboarding-wizard/wizard-prefill',
    },
    SETTINGS: {
      GET: '/organization/settings',
      UPDATE: '/organization/settings',
      OPERATING_SCOPE: '/organization/settings/operating-scope',
      FISCAL_SCOPE: '/organization/settings/fiscal-scope',
      FISCAL_DATA: '/organization/settings/fiscal-scope/fiscal-data',
      FISCAL_STATUS: '/organization/settings/fiscal-status',
      PAYMENT_POLICIES: '/organization/payment-policies',
    },
    ORGANIZATION: {
      GET: '/organization/organizations/:id',
      UPDATE: '/organization/organizations/:id',
      CONFIGURATION: '/organization/organizations/:id/configuration',
      CONFIGURATION_ACTIVE: '/organization/organizations/active',
    },
  },
} as const;

export type EndpointKey = keyof typeof Endpoints;
