export const API_BASE_URL = process.env.EXPO_PUBLIC_API_URL || 'https://api.vendix.online/api';

export const Endpoints = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register-owner',
    LOGOUT: '/auth/logout',
    REFRESH: '/auth/refresh',
    FORGOT_PASSWORD: '/auth/forgot-owner-password',
    RESET_PASSWORD: '/auth/reset-owner-password',
    VERIFY_TOKEN: '/auth/verify-token',
    ME: '/auth/me',
    PROFILE: '/auth/profile',
    SETTINGS: '/auth/settings',
  },
  STORE: {
    DASHBOARD_STATS: '/store/stores/dashboard/stats',
    PRODUCTS: {
      LIST: '/store/products',
      GET: '/store/products/:id',
      CREATE: '/store/products',
      UPDATE: '/store/products/:id',
      DELETE: '/store/products/:id',
      SEARCH: '/store/products/search',
      STATS: '/store/products/stats/store/:storeId',
      DEACTIVATE: '/store/products/:id/deactivate',
      VARIANTS: '/store/products/:productId/variants',
      VARIANT_CREATE: '/store/products/:productId/variants',
      VARIANT_UPDATE: '/store/products/variants/:variantId',
      VARIANT_DELETE: '/store/products/variants/:variantId',
      IMAGES: '/store/products/:productId/images',
      IMAGE_DELETE: '/store/products/images/:imageId',
      IMAGE_SET_MAIN: '/store/products/:productId/images/:imageId/main',
      BY_CATEGORY: '/store/products/category/:categoryId',
      BY_BRAND: '/store/products/brand/:brandId',
      LOW_STOCK: '/store/products/low-stock/:threshold',
      GENERATE_DESCRIPTION: '/store/products/generate-description',
      PROMOTIONS: '/store/products/:productId/promotions',
    },
    ORDERS: {
      LIST: '/store/orders',
      GET: '/store/orders/:id',
      CREATE: '/store/orders',
      UPDATE: '/store/orders/:id',
      DELETE: '/store/orders/:id',
      STATS: '/store/orders/stats',
      TIMELINE: '/store/orders/:id/timeline',
      FLOW_PAY: '/store/orders/:id/flow/pay',
      FLOW_SHIP: '/store/orders/:id/flow/ship',
      FLOW_DELIVER: '/store/orders/:id/flow/deliver',
      FLOW_CANCEL: '/store/orders/:id/flow/cancel',
      FLOW_REFUND: '/store/orders/:id/flow/refund',
      FLOW_REFUND_PREVIEW: '/store/orders/:id/flow/refund/preview',
      FLOW_FAST_TRACK: '/store/orders/:id/flow/fast-track',
      FLOW_CONFIRM_PAYMENT: '/store/orders/:id/flow/confirm-payment',
      ITEMS_UPDATE: '/store/orders/:id/items',
      SHIPPING_ASSIGN: '/store/orders/:id/shipping',
      REFUNDS: '/store/orders/:id/refunds',
    },
    ANALYTICS: {
      SALES_SUMMARY: '/store/analytics/sales/summary',
      SALES_TRENDS: '/store/analytics/sales/trends',
      SALES_BY_CHANNEL: '/store/analytics/sales/by-channel',
      INVENTORY_SUMMARY: '/store/analytics/inventory/summary',
      OVERVIEW: '/store/analytics/overview',
      SALES: '/store/analytics/sales',
      INVENTORY: '/store/analytics/inventory',
      FINANCIAL: '/store/analytics/financial',
    },
    CUSTOMERS: {
      LIST: '/store/customers',
      GET: '/store/customers/:id',
      CREATE: '/store/customers',
      UPDATE: '/store/customers/:id',
      DELETE: '/store/customers/:id',
      SEARCH: '/store/customers/search',
      STATS: '/store/customers/stats',
      TOPUP: '/store/customers/:id/topup',
    },
    CATEGORIES: {
      LIST: '/store/categories',
      CREATE: '/store/categories',
    },
    BRANDS: {
      LIST: '/store/brands',
      CREATE: '/store/brands',
    },
    TAXES: {
      LIST: '/store/taxes',
      CATEGORIES: '/store/taxes/categories',
    },
    PAYMENT_METHODS: {
      LIST: '/store/payments/methods',
    },
    CASH_REGISTERS: {
      LIST: '/store/cash-registers',
      SESSIONS: '/store/cash-registers/sessions',
    },
    INVOICES: {
      LIST: '/store/invoices',
      GET: '/store/invoices/:id',
      CREATE: '/store/invoices',
      STATS: '/store/invoices/stats',
      SEND: '/store/invoices/:id/send',
      VOID: '/store/invoices/:id/void',
      RESOLUTIONS: '/store/invoices/resolutions',
      CREATE_RESOLUTION: '/store/invoices/resolutions',
      DIAN_CONFIG: '/store/invoices/dian-config',
    },
    STORES: {
      LIST: '/store/stores',
      GET: '/store/stores/:id',
      STATS: '/store/stores/stats',
      SETTINGS: '/store/stores/:id/settings',
    },
    SETTINGS: {
      GET: '/store/settings',
      UPDATE: '/store/settings',
      USERS_LIST: '/store/settings/users',
      USER_CREATE: '/store/settings/users',
      USER_UPDATE: '/store/settings/users/:id',
      USER_TOGGLE_STATE: '/store/settings/users/:id/state',
      ROLES_LIST: '/store/settings/roles',
      ROLE_CREATE: '/store/settings/roles',
      ROLE_UPDATE: '/store/settings/roles/:id',
      ROLE_DELETE: '/store/settings/roles/:id',
    },
    INVENTORY: {
      STATS: '/store/inventory/stats',
      ADJUSTMENTS: {
        LIST: '/store/inventory/adjustments',
        CREATE: '/store/inventory/adjustments',
      },
      TRANSFERS: {
        LIST: '/store/inventory/transfers',
        CREATE: '/store/inventory/transfers',
      },
      MOVEMENTS: {
        LIST: '/store/inventory/movements',
      },
      SUPPLIERS: {
        LIST: '/store/suppliers',
        CREATE: '/store/suppliers',
        UPDATE: '/store/suppliers/:id',
        DELETE: '/store/suppliers/:id',
      },
      LOCATIONS: {
        LIST: '/store/locations',
        CREATE: '/store/locations',
        UPDATE: '/store/locations/:id',
      },
    },
    ACCOUNTING: {
      ACCOUNTS: {
        LIST: '/store/accounting/accounts',
        CREATE: '/store/accounting/accounts',
        UPDATE: '/store/accounting/accounts/:id',
        DELETE: '/store/accounting/accounts/:id',
      },
      JOURNAL_ENTRIES: {
        LIST: '/store/accounting/journal-entries',
        GET: '/store/accounting/journal-entries/:id',
        CREATE: '/store/accounting/journal-entries',
      },
      FISCAL_PERIODS: {
        LIST: '/store/accounting/fiscal-periods',
        CREATE: '/store/accounting/fiscal-periods',
      },
      RECEIVABLES: {
        LIST: '/store/accounting/receivables',
        PAY: '/store/accounting/receivables/:id/pay',
      },
      PAYABLES: {
        LIST: '/store/accounting/payables',
        PAY: '/store/accounting/payables/:id/pay',
      },
    },
  },
} as const;

export type EndpointKey = keyof typeof Endpoints;
