import { Injectable } from '@angular/core';

/**
 * [print-editor-dsk P6] — Print-format thumbnail generator.
 *
 * Generates a 240×320 SVG placeholder representing each print format. The
 * placeholder is colored by the format's category (Logística, Ventas POS,
 * Ventas, Comercial, Compras, Inventario, Facturación, Restaurante) so the
 * Hub can render a recognizable preview tile without needing a real
 * rasterized thumbnail from the backend.
 *
 * The real rasterized thumbnail endpoint (a future backend route returning a
 * PNG/JPEG generated by Puppeteer or pdf2pic) lands in a later phase; this
 * service keeps the same public contract so the Hub does not need to
 * change when the endpoint is ready — only the implementation swaps from
 * `renderPlaceholder` to a real HTTP fetch.
 */
const CATEGORY_COLORS: Record<string, string> = {
  'Logística': '#3b82f6',
  'Ventas POS': '#10b981',
  'Ventas': '#06b6d4',
  'Comercial': '#8b5cf6',
  'Compras': '#f97316',
  'Inventario': '#84cc16',
  'Facturación': '#ef4444',
  'Restaurante': '#a855f7',
};

/**
 * Map of format_type → category. Mirrors
 * `apps/backend/.../print-formats.service.ts` `FORMAT_TYPE_METADATA`. Kept
 * here as a stable frontend lookup so the thumbnail service has no DI deps
 * on the gateway client and can be unit-tested in isolation.
 */
export const PRINT_FORMAT_CATEGORY_MAP: Record<string, string> = {
  pos_sale_ticket: 'Ventas POS',
  sales_order_invoice: 'Ventas',
  dispatch_note: 'Logística',
  dispatch_ticket: 'Logística',
  quotation: 'Comercial',
  credit_note: 'Ventas',
  purchase_order: 'Compras',
  transfer_note: 'Inventario',
  fiscal_electronic_invoice: 'Facturación',
  fiscal_credit_note: 'Facturación',
  kitchen_ticket: 'Restaurante',
};

/**
 * Resolves the category for a given format type, falling back to "Logística"
 * for any unknown format so the placeholder always renders.
 */
export function resolveCategory(formatType: string): string {
  return PRINT_FORMAT_CATEGORY_MAP[formatType] ?? 'Logística';
}

@Injectable({ providedIn: 'root' })
export class PrintThumbnailService {
  private readonly cache = new Map<string, string>(); // formatType -> dataURL

  /**
   * Returns a `data:image/svg+xml;base64,...` URL representing the format's
   * thumbnail. Cached by formatType so repeated calls during Hub renders
   * never re-render the same SVG twice.
   *
   * The thumbnail is intended for a 240×320 frame; the Hub's `<img>` tag
   * uses `object-fit: contain` so the SVG centers cleanly inside whatever
   * slot the Hub card allocates.
   */
  getThumbnail(formatType: string): string {
    const cached = this.cache.get(formatType);
    if (cached) return cached;

    const dataUrl = this.renderPlaceholder(formatType);
    this.cache.set(formatType, dataUrl);
    return dataUrl;
  }

  /** Drops the cached thumbnail for one format (e.g. after a category change). */
  invalidate(formatType: string): void {
    this.cache.delete(formatType);
  }

  /** Drops every cached thumbnail. Useful when a user toggles dark/light theme. */
  clear(): void {
    this.cache.clear();
  }

  /**
   * Builds the SVG placeholder. Uses semantic shapes (rectangles for header,
   * body rows, footer block) tinted with the category color so the thumbnail
   * reads as a "paper document" silhouette at thumbnail scale.
   */
  private renderPlaceholder(formatType: string): string {
    const category = resolveCategory(formatType);
    const color = CATEGORY_COLORS[category] ?? '#6b7280';
    const escapedName = this.escapeXml(formatType);
    const svg =
      `<?xml version="1.0" encoding="UTF-8"?>` +
      `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 320">` +
      `<rect width="240" height="320" fill="${color}" fill-opacity="0.12"/>` +
      `<rect x="60" y="40" width="120" height="20" rx="2" fill="${color}"/>` +
      `<rect x="40" y="100" width="160" height="8" rx="2" fill="${color}" fill-opacity="0.7"/>` +
      `<rect x="40" y="120" width="160" height="8" rx="2" fill="${color}" fill-opacity="0.7"/>` +
      `<rect x="40" y="140" width="120" height="8" rx="2" fill="${color}" fill-opacity="0.7"/>` +
      `<rect x="40" y="170" width="160" height="40" rx="2" fill="${color}" fill-opacity="0.3"/>` +
      `<rect x="40" y="220" width="80" height="8" rx="2" fill="${color}" fill-opacity="0.7"/>` +
      `<text x="120" y="290" font-family="sans-serif" font-size="14" text-anchor="middle" fill="${color}">${escapedName}</text>` +
      `</svg>`;
    // btoa is safe here because the SVG body is ASCII (we escapeXml any user
    // input) and we never call this with binary content.
    return 'data:image/svg+xml;base64,' + btoa(svg);
  }

  private escapeXml(value: string): string {
    return value
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&apos;');
  }
}
