export interface AIGenerationJob {
  app_key: string;
  variables?: Record<string, string>;
  extra_messages?: Array<{ role: string; content: string }>;
  organization_id?: number;
  store_id?: number;
  user_id?: number;
  callback_event?: string;
  /**
   * Correlation id propagated from the originating HTTP request (X-Request-Id)
   * or freshly generated by the producer. Required so the AI quota counter
   * can dedup if BullMQ retries the job or if the AI provider retries
   * internally with the same id.
   */
  request_id?: string;
}

export interface AIEmbeddingJob {
  store_id: number;
  organization_id: number;
  entity_type: string;
  entity_id: number;
  content: string;
}

export interface AIAgentJob {
  goal: string;
  tools?: string[];
  organization_id?: number;
  store_id?: number;
  user_id?: number;
  max_iterations?: number;
  timeout_ms?: number;
  /** See AIGenerationJob.request_id. */
  request_id?: string;
  /**
   * The requesting user's resolved permissions, carried into the worker.
   *
   * A background run has no HTTP request to derive them from, and the tool
   * catalog is filtered by exactly this list — so omitting them does not fail
   * loudly, it silently hands the agent an empty toolset and the task returns
   * "no pude hacer nada". Snapshotted at enqueue time on purpose: the task must
   * run with the authority the person had when they approved it, not with
   * whatever their role became in the meantime.
   */
  permissions?: string[];
  roles?: string[];
  /** `ai_agent_tasks` row this job reports into. */
  task_id?: number;
  /** Conversation the task belongs to, for the closing notification. */
  conversation_id?: number;
  /** Application whose stored prompt drives the run. */
  app_key?: string;
}

export type AIJobStatus =
  | 'waiting'
  | 'active'
  | 'completed'
  | 'failed'
  | 'delayed';

export interface AIJobResult {
  job_id: string;
  status: AIJobStatus;
  result?: any;
  error?: string;
  progress?: number;
}
