import { OnModuleInit } from '@nestjs/common';
import { EventEmitter2 } from '@nestjs/event-emitter';
import { PrismaService } from '../../prisma/prisma.service';
import { CreateDomainSettingDto, UpdateDomainSettingDto, VerifyDomainDto, VerifyDomainResult } from './dto/domain-settings.dto';
import { DomainSettingResponse, DomainResolutionResponse, DomainListResponse, DomainAvailabilityResponse, DomainValidationResponse } from './types/domain.types';
export declare class DomainsService implements OnModuleInit {
    private readonly prisma;
    private readonly eventEmitter;
    private readonly logger;
    private cache;
    private readonly CACHE_TTL_MS;
    constructor(prisma: PrismaService, eventEmitter: EventEmitter2);
    onModuleInit(): void;
    private getFromCache;
    private saveInCache;
    private emitDomainCacheInvalidation;
    clearCache(): void;
    clearOne(hostname: string): void;
    resolveDomain(hostname: string, subdomain?: string, forwardedHost?: string): Promise<DomainResolutionResponse>;
    checkHostnameAvailability(hostname: string): Promise<DomainAvailabilityResponse>;
    createDomainSetting(createDomainSettingDto: CreateDomainSettingDto): Promise<DomainSettingResponse>;
    getAllDomainSettings(filters: {
        organizationId?: number;
        storeId?: number;
        search?: string;
        limit?: number;
        offset?: number;
    }): Promise<DomainListResponse>;
    getDomainSettingByHostname(hostname: string): Promise<DomainSettingResponse>;
    getDomainSettingById(id: number): Promise<DomainSettingResponse>;
    updateDomainSetting(hostname: string, updateDomainSettingDto: UpdateDomainSettingDto): Promise<DomainSettingResponse>;
    deleteDomainSetting(hostname: string): Promise<void>;
    duplicateDomainSetting(hostname: string, newHostname: string): Promise<DomainSettingResponse>;
    verifyDomain(hostname: string, body: VerifyDomainDto): Promise<VerifyDomainResult>;
    validateHostname(hostname: string): Promise<DomainValidationResponse>;
    private validateHostnameFormat;
    private mapToResponse;
    private inferDomainType;
    private inferOwnership;
    private clearExistingPrimary;
    private generateVerificationToken;
    getDomainStats(): Promise<{
        total: number;
        active: number;
        pending: number;
        verified: number;
        platformSubdomains: number;
        customDomains: number;
        clientSubdomains: number;
        aliasDomains: number;
    }>;
}
