import { Injectable, Logger } from '@nestjs/common';
import { print_format_type_enum } from '@prisma/client';
import { StorePrismaService } from '../../../../prisma/services/store-prisma.service';
import { OrganizationPrismaService } from '../../../../prisma/services/organization-prisma.service';
import { VendixHttpException, ErrorCodes } from 'src/common/errors';
import { PrintGatewayService } from './print-gateway.service';
import { PrintFiscalValidatorService } from './print-fiscal-validator.service';
import { DocumentDataProviderRegistry } from '../providers/document-data-provider.registry';
import {
  UpdatePrintFormatConfigDto,
} from '../dto/print-format-config.dto';
import {
  CreatePrintTemplateDto,
  UpdatePrintTemplateDto,
} from '../dto/print-template.dto';
// [print-editor-dsk P1.1] — AJV runtime validation against definition-v2.schema.json.
// Skips v1 overrides (no `v` field) to preserve backward compatibility; only
// validates payloads that opt into v2 with `v: 2` at the top level.
import { validatePrintFormatDefinition } from '../schemas/ajv-instance';

/**
 * [print-editor-dsk P1.1] — Decide whether a payload should go through AJV
 * validation. v1 payloads (no `v` field, or `v: 1`) skip the validator and
 * continue through the legacy fiscal path. v2 payloads (`v: 2`) go through
 * `validatePrintFormatDefinition`; an empty `overrides` is also treated as a
 * no-op (clear-customization) and skips validation.
 */
function shouldValidateV2Payload(payload: unknown): boolean {
  if (!payload || typeof payload !== 'object') return false;
  const v = (payload as Record<string, unknown>).v;
  return v === 2;
}

export const ALL_FORMAT_TYPES: print_format_type_enum[] = [
  'pos_sale_ticket',
  'sales_order_invoice',
  'dispatch_note',
  'quotation',
  'credit_note',
  'purchase_order',
  'transfer_note',
  'fiscal_electronic_invoice',
  'fiscal_credit_note',
  'kitchen_ticket',
  // CP-DTLP-20260827 (Phase B.3): 11th format_type. The cast is intentional —
  // the DB enum accepts this value after migration
  // 20260827120000_add_dispatch_ticket_to_enum, and the @prisma/client enum
  // is regenerated by a later `prisma generate`. Until then the literal
  // 'dispatch_ticket' is unknown to the typed enum but valid in the DB.
  'dispatch_ticket' as unknown as print_format_type_enum,
];

export const FORMAT_TYPE_METADATA: Record<
  print_format_type_enum,
  { name: string; category: string; icon: string; engine: 'html' | 'pdf' }
> = {
  pos_sale_ticket: { name: 'Ticket de Venta POS', category: 'Ventas POS', icon: 'receipt', engine: 'html' },
  sales_order_invoice: { name: 'Factura de Venta / Orden', category: 'Ventas', icon: 'file-text', engine: 'html' },
  dispatch_note: { name: 'Remisión / Despacho', category: 'Logística', icon: 'truck', engine: 'html' },
  quotation: { name: 'Cotización Comercial', category: 'Comercial', icon: 'file-spreadsheet', engine: 'html' },
  credit_note: { name: 'Nota Crédito Comercial', category: 'Ventas', icon: 'corner-down-left', engine: 'html' },
  purchase_order: { name: 'Orden de Compra', category: 'Compras', icon: 'shopping-cart', engine: 'html' },
  transfer_note: { name: 'Traslado entre Tiendas', category: 'Inventario', icon: 'arrow-left-right', engine: 'html' },
  fiscal_electronic_invoice: { name: 'Factura Electrónica (DIAN)', category: 'Facturación', icon: 'shield-check', engine: 'html' },
  fiscal_credit_note: { name: 'Nota Crédito Electrónica', category: 'Facturación', icon: 'file-minus', engine: 'html' },
  kitchen_ticket: { name: 'Ticket de Cocina (KDS)', category: 'Restaurante', icon: 'utensils', engine: 'html' },
  // CP-DTLP-20260827 (Phase B.3): Enlace Universal — Logistics family. The
  // (print_format_type_enum, ...) key cast mirrors the ALL_FORMAT_TYPES cast
  // for the same reason: the @prisma/client enum is regenerated by a later
  // `prisma generate` after the migration lands.
  ...({
    dispatch_ticket: { name: 'Tiquete de Despacho', category: 'Logística', icon: 'package', engine: 'html' },
  } as Record<string, { name: string; category: string; icon: string; engine: 'html' | 'pdf' }>),
};

@Injectable()
export class PrintFormatsService {
  private readonly logger = new Logger(PrintFormatsService.name);

  constructor(
    private readonly storePrisma: StorePrismaService,
    private readonly orgPrisma: OrganizationPrismaService,
    private readonly gateway: PrintGatewayService,
    private readonly fiscalValidator: PrintFiscalValidatorService,
    private readonly registry: DocumentDataProviderRegistry,
  ) {}

  /**
   * Lista el catálogo de los 10 formatos con el estado actual para la tienda
   */
  async listStoreFormats(storeId: number, organizationId: number) {
    const storeConfigs = await this.storePrisma.store_print_format_configs.findMany({
      where: { store_id: storeId },
      include: { template: true },
    });

    const configMap = new Map<print_format_type_enum, any>();
    for (const cfg of storeConfigs) {
      configMap.set(cfg.format_type, cfg);
    }

    return ALL_FORMAT_TYPES.map((type) => {
      const cfg = configMap.get(type);
      const meta = FORMAT_TYPE_METADATA[type];
      return {
        format_type: type,
        name: meta.name,
        category: meta.category,
        icon: meta.icon,
        engine: meta.engine,
        is_configured: Boolean(cfg),
        is_active: cfg?.is_active ?? true,
        gateway_enabled: cfg?.gateway_enabled ?? false,
        template_name: cfg?.template?.name || (cfg?.overrides ? 'Personalizado (Overrides)' : 'Por defecto del sistema'),
        updated_at: cfg?.updated_at || null,
      };
    });
  }

  /**
   * Obtiene la configuración detallada de un formato de impresión
   */
  async getStoreFormatDetail(storeId: number, formatType: print_format_type_enum) {
    const effective = await this.gateway.resolveEffectiveConfig(storeId, formatType);
    const provider = this.registry.getProvider(formatType);
    const meta = FORMAT_TYPE_METADATA[formatType];

    const storeConfig = await this.storePrisma.store_print_format_configs.findFirst({
      where: { store_id: storeId, format_type: formatType },
      include: { template: true },
    });

    return {
      format_type: formatType,
      name: meta.name,
      category: meta.category,
      is_active: effective.is_active,
      gateway_enabled: effective.gateway_enabled,
      is_customized: effective.is_customized,
      template_id: storeConfig?.template_id || null,
      template_name: storeConfig?.template?.name || null,
      definition: effective.definition,
      overrides: storeConfig?.overrides || null,
      available_tokens: provider.getAvailableTokens(),
    };
  }

  /**
   * Actualiza o crea la configuración y overrides para un formato en la tienda
   */
  async updateStoreFormat(
    storeId: number,
    organizationId: number,
    formatType: print_format_type_enum,
    dto: UpdatePrintFormatConfigDto,
  ) {
    // [print-editor-dsk P1.1] — AJV v2 schema validation BEFORE the fiscal pass.
    // Only fires for v2 payloads (`dto.overrides.v === 2`); v1 overrides keep
    // their legacy path. The schema includes per-side margins, height_mm,
    // logo and company_block constraints, plus custom-keyword checks for
    // column-width sums and Handlebars balance.
    if (shouldValidateV2Payload(dto.overrides)) {
      const result = validatePrintFormatDefinition(dto.overrides);
      if (!result.valid) {
        throw new VendixHttpException(
          ErrorCodes.PRINT_CONFIG_VALIDATION_001,
          'v2 schema validation failed for store format overrides',
          { errors: result.errors },
        );
      }
    }

    // Si se están enviando overrides con definición estructurada o custom, validar fiscalmente
    if (dto.overrides) {
      const current = await this.gateway.resolveEffectiveConfig(storeId, formatType);
      const merged = { ...current.definition, ...dto.overrides };
      this.fiscalValidator.assertFiscalCompliance(formatType, merged as any);
    }

    const existing = await this.storePrisma.store_print_format_configs.findFirst({
      where: { store_id: storeId, format_type: formatType },
    });

    let result;
    if (existing) {
      result = await this.storePrisma.store_print_format_configs.update({
        where: { id: existing.id },
        data: {
          is_active: dto.is_active !== undefined ? dto.is_active : existing.is_active,
          gateway_enabled: dto.gateway_enabled !== undefined ? dto.gateway_enabled : existing.gateway_enabled,
          template_id: dto.template_id !== undefined ? dto.template_id : existing.template_id,
          overrides: dto.overrides !== undefined ? (dto.overrides as any) : existing.overrides,
          updated_at: new Date(),
        },
        include: { template: true },
      });
    } else {
      result = await this.storePrisma.store_print_format_configs.create({
        data: {
          store_id: storeId,
          organization_id: organizationId,
          format_type: formatType,
          is_active: dto.is_active ?? true,
          gateway_enabled: dto.gateway_enabled ?? true,
          template_id: dto.template_id || null,
          overrides: (dto.overrides as any) || null,
        },
        include: { template: true },
      });
    }

    return this.getStoreFormatDetail(storeId, formatType);
  }

  /**
   * Restablece la configuración de un formato a los defaults del sistema
   */
  async resetStoreFormatToDefault(storeId: number, formatType: print_format_type_enum) {
    const existing = await this.storePrisma.store_print_format_configs.findFirst({
      where: { store_id: storeId, format_type: formatType },
    });

    if (existing) {
      await this.storePrisma.store_print_format_configs.delete({
        where: { id: existing.id },
      });
    }

    return { success: true, message: 'Configuración restablecida a los valores por defecto del sistema.' };
  }

  /**
   * Activa el flag gateway_enabled para un formato
   */
  async activateGateway(storeId: number, organizationId: number, formatType: print_format_type_enum) {
    await this.updateStoreFormat(storeId, organizationId, formatType, { gateway_enabled: true });
    return { format_type: formatType, gateway_enabled: true };
  }

  /**
   * Desactiva el flag gateway_enabled (revierte a legacy emitter)
   */
  async deactivateGateway(storeId: number, organizationId: number, formatType: print_format_type_enum) {
    await this.updateStoreFormat(storeId, organizationId, formatType, { gateway_enabled: false });
    return { format_type: formatType, gateway_enabled: false };
  }

  // ============================================
  // BIBLIOTECA DE ORGANIZACIÓN (TEMPLATES COMPARTIDOS)
  // ============================================

  async listLibraryTemplates(organizationId: number, formatType?: print_format_type_enum) {
    const where: any = {
      OR: [
        { is_system: true },
        { organization_id: organizationId, is_shared: true },
        { organization_id: organizationId },
      ],
    };

    if (formatType) {
      where.format_type = formatType;
    }

    // `withoutScope()` es deliberado, no un descuido de alcance.
    //
    // `this.orgPrisma.print_templates` (el getter por defecto) pasa por
    // `OrganizationPrismaService.applyOrganizationScoping`, que para modelos
    // sin `SCOPE_OVERRIDES` inyecta `organization_id: context.organization_id`
    // como llave HERMANA del `where` del llamador (no dentro de un `AND`
    // explícito) — ver `organization-prisma.service.ts`. Con un `OR` de primer
    // nivel como el de arriba, Postgres exige AMBAS condiciones: el `OR` de
    // esta consulta Y la igualdad inyectada. Las plantillas de sistema
    // (`is_system = true`) tienen `organization_id = NULL` a propósito —son de
    // TODAS las organizaciones—, así que la igualdad inyectada las descarta
    // siempre. Medido en vivo el 2026-08-24: con 10 plantillas de sistema y 1
    // de la organización 6, `GET /store/print-formats/library` devolvía **1**
    // fila en vez de **11** — el catálogo entero desaparecía en silencio, sin
    // error, y parecía que la biblioteca compartida no existía.
    //
    // El alcance real de esta consulta ya está impuesto A MANO en el `OR` de
    // arriba con el `organizationId` recibido por parámetro (nunca del
    // contexto de otro tenant), así que `withoutScope()` no abre nada: sólo
    // evita que la capa de scoping genérica AND-ee una igualdad que este
    // modelo, por diseño, no puede satisfacer para sus filas de sistema.
    return this.orgPrisma.withoutScope().print_templates.findMany({
      where,
      include: {
        author: {
          select: { id: true, first_name: true, last_name: true, email: true },
        },
      },
      orderBy: [{ is_system: 'desc' }, { created_at: 'desc' }],
    });
  }

  async createLibraryTemplate(
    organizationId: number,
    userId: number,
    dto: CreatePrintTemplateDto,
  ) {
    // [print-editor-dsk P1.1] — AJV v2 schema validation BEFORE fiscal pass.
    // Library templates are whole `definition` objects (not partial
    // overrides), so the schema check applies whenever the creator opts
    // into v2 with `dto.definition.v === 2`. v1 templates still flow
    // through the legacy fiscal path.
    if (shouldValidateV2Payload(dto.definition)) {
      const result = validatePrintFormatDefinition(dto.definition);
      if (!result.valid) {
        throw new VendixHttpException(
          ErrorCodes.PRINT_CONFIG_VALIDATION_001,
          'v2 schema validation failed for library template definition',
          { errors: result.errors },
        );
      }
    }

    // CP-DTLP-20260827: PrintFormatTypeEnum (TS) incluye dispatch_ticket; el
    // validador fiscal espera el tipo Prisma. Cast explícito en la frontera
    // para que tsc acepte el undécimo valor hasta que `prisma generate`
    // regenere el enum de @prisma/client.
    this.fiscalValidator.assertFiscalCompliance(
      dto.format_type as unknown as print_format_type_enum,
      dto.definition as any,
    );

    return this.orgPrisma.print_templates.create({
      data: {
        organization_id: organizationId,
        created_by: userId,
        format_type: dto.format_type,
        name: dto.name,
        description: dto.description || null,
        definition: dto.definition as any,
        is_system: false,
        is_shared: dto.is_shared ?? true,
      },
    });
  }

  async cloneTemplateToStore(
    storeId: number,
    organizationId: number,
    templateId: number,
  ) {
    // Mismo motivo que en `listLibraryTemplates`: el `OR` que admite plantillas
    // de sistema (`organization_id = NULL`) quedaría ANDado con la igualdad de
    // alcance que `this.orgPrisma.print_templates` inyecta sola, y ninguna
    // plantilla de sistema pasaría el filtro. `withoutScope()` con el `OR`
    // manual de abajo (que ya acota a `organizationId`) es el filtro correcto.
    const template = await this.orgPrisma.withoutScope().print_templates.findFirst({
      where: {
        id: templateId,
        OR: [{ is_system: true }, { organization_id: organizationId }],
      },
    });

    if (!template) {
      throw new VendixHttpException(ErrorCodes.PRINT_TEMPLATE_NOT_FOUND_001);
    }

    await this.updateStoreFormat(storeId, organizationId, template.format_type, {
      template_id: template.id,
      overrides: {},
      is_active: true,
      gateway_enabled: true,
    });

    return this.getStoreFormatDetail(storeId, template.format_type);
  }

  async updateTemplateShareState(
    organizationId: number,
    templateId: number,
    isShared: boolean,
  ) {
    const template = await this.orgPrisma.print_templates.findFirst({
      where: { id: templateId, organization_id: organizationId },
    });

    if (!template) {
      throw new VendixHttpException(ErrorCodes.PRINT_TEMPLATE_NOT_FOUND_001);
    }

    if (template.is_system) {
      throw new VendixHttpException(ErrorCodes.PRINT_TEMPLATE_SYSTEM_PROTECTED_001);
    }

    return this.orgPrisma.print_templates.update({
      where: { id: templateId },
      data: { is_shared: isShared, updated_at: new Date() },
    });
  }
}
