#!/usr/bin/env bash
# scripts/install-engram-hooks.sh
# Install a git pre-push hook that stages Engram memory chunks before push.
# Idempotent: re-running reports existing hook and re-installs cleanly.
#
# Behavior of the installed hook:
#   - Runs ./scripts/engram-sync.sh --quiet on every push
#   - If new chunks were staged, amends the last commit OR creates a follow-up
#     commit (configurable via .engram/hooks-config)
#   - Push proceeds normally
#
# To uninstall:
#   ./scripts/install-engram-hooks.sh --uninstall
#
# To skip the hook for one push (e.g. flaky network):
#   git push --no-verify

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
HOOKS_DIR="$REPO_ROOT/.git/hooks"
HOOK_FILE="$HOOKS_DIR/pre-push"
HOOK_MARKER="# engram-pre-push-hook"

usage() {
  cat <<EOF
Engram pre-push hook installer.

Usage:
  ./scripts/install-engram-hooks.sh           # install (idempotent)
  ./scripts/install-engram-hooks.sh --uninstall # remove the hook
  ./scripts/install-engram-hooks.sh --status   # show current state

The hook runs ./scripts/engram-sync.sh before every push. If new chunks are
staged, it amends the last commit (default) or creates a follow-up commit
(set ENGRAM_HOOK_AMEND=0 to disable amending).
EOF
}

say()  { printf '\033[1;34m[engram-hooks]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[engram-hooks]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m[engram-hooks]\033[0m %s\n' "$*" >&2; exit 1; }

# Inside the hook we are not interactive — never block.
AMEND="${ENGRAM_HOOK_AMEND:-1}"
QUIET_FLAG="--quiet"

# Sanity checks
[ -d "$REPO_ROOT/.git" ] || die "Not inside a git repo: $REPO_ROOT"
[ -x "$REPO_ROOT/scripts/engram-sync.sh" ] || \
  die "scripts/engram-sync.sh not found or not executable in $REPO_ROOT"
command -v engram >/dev/null 2>&1 || \
  die "engram is not installed. Run ./scripts/engram-bootstrap.sh first."

case "${1:-}" in
  --help|-h) usage; exit 0 ;;
  --uninstall) shift; UNINSTALL=1 ;;
  --status) shift; STATUS_ONLY=1 ;;
  "") UNINSTALL=0; STATUS_ONLY=0 ;;
  *) usage; exit 1 ;;
esac

if [ "${STATUS_ONLY:-0}" -eq 1 ]; then
  if [ -f "$HOOK_FILE" ] && grep -q "$HOOK_MARKER" "$HOOK_FILE"; then
    say "Hook installed: $HOOK_FILE"
    grep -A 2 "$HOOK_MARKER" "$HOOK_FILE" | sed 's/^/  /'
    exit 0
  else
    say "Hook not installed."
    exit 0
  fi
fi

if [ "${UNINSTALL:-0}" -eq 1 ]; then
  if [ ! -f "$HOOK_FILE" ]; then
    say "No pre-push hook to remove."
    exit 0
  fi
  if ! grep -q "$HOOK_MARKER" "$HOOK_FILE"; then
    warn "Existing pre-push hook is not an Engram hook. Leaving it alone."
    exit 0
  fi
  rm -f "$HOOK_FILE"
  say "Removed pre-push hook."
  exit 0
fi

# Install path
mkdir -p "$HOOKS_DIR"

# If there's a pre-existing pre-push hook from someone else, back it up and chain.
if [ -f "$HOOK_FILE" ] && ! grep -q "$HOOK_MARKER" "$HOOK_FILE"; then
  BACKUP="$HOOKS_DIR/pre-push.backup-$(date +%Y%m%d-%H%M%S)"
  mv "$HOOK_FILE" "$BACKUP"
  warn "Existing pre-push hook moved to $BACKUP (Engram will call it before itself)."
  EXISTING_HOOK="$BACKUP"
else
  EXISTING_HOOK=""
fi

cat > "$HOOK_FILE" <<EOF
#!/usr/bin/env bash
$HOOK_MARKER
# Auto-generated by scripts/install-engram-hooks.sh
# Stage Engram memory chunks before push. Safe to remove with:
#   ./scripts/install-engram-hooks.sh --uninstall

set -e

# Skip when user opts out
if [ -n "\${ENGRAM_SKIP_PRE_PUSH:-}" ]; then
  exit 0
fi

# Skip when engram is not installed on this machine (e.g. CI, Docker)
if ! command -v engram >/dev/null 2>&1; then
  exit 0
fi

REPO_ROOT="\$(git rev-parse --show-toplevel)"
SYNC_SH="\$REPO_ROOT/scripts/engram-sync.sh"

if [ ! -x "\$SYNC_SH" ]; then
  exit 0
fi

# Run the sync; it stages any new chunks.
"\$SYNC_SH" $QUIET_FLAG || true

# If new chunks were staged, fold them into the last commit so the push stays
# clean. Set ENGRAM_HOOK_AMEND=0 to disable amending (creates a follow-up commit
# instead — useful if you don't want the amend to rewrite published history).
if [ -n "\$(git diff --cached --name-only -- .engram/ 2>/dev/null)" ]; then
  if [ "\${ENGRAM_HOOK_AMEND:-1}" = "1" ]; then
    git commit --amend --no-edit -- .engram/ >/dev/null 2>&1 || \
      git commit -m "chore(engram): sync memories" -- .engram/ >/dev/null 2>&1 || true
  else
    git commit -m "chore(engram): sync memories" -- .engram/ >/dev/null 2>&1 || true
  fi
fi

exit 0
EOF

chmod +x "$HOOK_FILE"

# If we backed up an existing hook, append it so the chain keeps working.
if [ -n "$EXISTING_HOOK" ]; then
  {
    echo ""
    echo "# --- existing pre-push hook (chained) ---"
    cat "$EXISTING_HOOK"
  } >> "$HOOK_FILE"
  chmod +x "$HOOK_FILE"
fi

say "Installed pre-push hook: $HOOK_FILE"
say "Next push will run ./scripts/engram-sync.sh before sending commits."
echo
echo "Useful commands:"
echo "  ./scripts/install-engram-hooks.sh --status     # verify it's installed"
echo "  ./scripts/install-engram-hooks.sh --uninstall  # remove it"
echo "  git push --no-verify                           # skip the hook for one push"
echo "  ENGRAM_SKIP_PRE_PUSH=1 git push                # skip without changing hooks"
