#!/usr/bin/env bash
# scripts/install-engram-hooks.sh
# Install a git pre-push hook that stages Engram memory chunks before push.
# Idempotent: re-running reports existing hook and re-installs cleanly.
#
# Behavior of the installed hook:
#   - Runs ./scripts/engram-sync.sh --quiet on every push
#   - If new chunks were staged, amends the last commit OR creates a follow-up
#     commit (configurable via .engram/hooks-config)
#   - Push proceeds normally
#
# To uninstall:
#   ./scripts/install-engram-hooks.sh --uninstall
#
# To skip the hook for one push (e.g. flaky network):
#   git push --no-verify

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
HOOKS_DIR="$REPO_ROOT/.git/hooks"
HOOK_FILE="$HOOKS_DIR/pre-push"
COMMIT_MSG_FILE="$HOOKS_DIR/commit-msg"
HOOK_MARKER="# engram-pre-push-hook"
COMMIT_MSG_MARKER="# engram-commit-msg-hook"

usage() {
  cat <<EOF
Engram hooks installer.

Usage:
  ./scripts/install-engram-hooks.sh           # install (idempotent)
  ./scripts/install-engram-hooks.sh --uninstall # remove the hooks
  ./scripts/install-engram-hooks.sh --status   # show current state

Installs two hooks:

1. pre-push: runs ./scripts/engram-sync.sh before every push. If new chunks
   are staged, it commits them as a SEPARATE "chore(engram): sync memories"
   commit UNLESS the last commit is already a chore(engram) commit AND
   ENGRAM_HOOK_AMEND=1 — in which case it amends the last commit (useful when
   running sync multiple times in a row before pushing).

   This prevents .engram/ files from sneaking into feature commits, which
   causes merge conflicts on .engram/manifest.json every time someone syncs.

2. commit-msg: warns (does NOT abort) when .engram/ files are staged but the
   commit message is not a chore(engram) commit. The hard guard lives in
   pre-push.
EOF
}

say()  { printf '\033[1;34m[engram-hooks]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[engram-hooks]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m[engram-hooks]\033[0m %s\n' "$*" >&2; exit 1; }

# Inside the hook we are not interactive — never block.
AMEND="${ENGRAM_HOOK_AMEND:-1}"
QUIET_FLAG="--quiet"

# Sanity checks
[ -d "$REPO_ROOT/.git" ] || die "Not inside a git repo: $REPO_ROOT"
[ -x "$REPO_ROOT/scripts/engram-sync.sh" ] || \
  die "scripts/engram-sync.sh not found or not executable in $REPO_ROOT"
command -v engram >/dev/null 2>&1 || \
  die "engram is not installed. Run ./scripts/engram-bootstrap.sh first."

case "${1:-}" in
  --help|-h) usage; exit 0 ;;
  --uninstall) shift; UNINSTALL=1 ;;
  --status) shift; STATUS_ONLY=1 ;;
  "") UNINSTALL=0; STATUS_ONLY=0 ;;
  *) usage; exit 1 ;;
esac

if [ "${STATUS_ONLY:-0}" -eq 1 ]; then
  PRE_PUSH="not installed"
  COMMIT_MSG="not installed"
  if [ -f "$HOOK_FILE" ] && grep -q "$HOOK_MARKER" "$HOOK_FILE"; then
    PRE_PUSH="installed: $HOOK_FILE"
  fi
  if [ -f "$COMMIT_MSG_FILE" ] && grep -q "$COMMIT_MSG_MARKER" "$COMMIT_MSG_FILE"; then
    COMMIT_MSG="installed: $COMMIT_MSG_FILE"
  fi
  say "pre-push hook:    $PRE_PUSH"
  say "commit-msg hook:  $COMMIT_MSG"
  exit 0
fi

if [ "${UNINSTALL:-0}" -eq 1 ]; then
  REMOVED=0
  if [ -f "$HOOK_FILE" ] && grep -q "$HOOK_MARKER" "$HOOK_FILE"; then
    rm -f "$HOOK_FILE"
    say "Removed pre-push hook."
    REMOVED=1
  elif [ -f "$HOOK_FILE" ]; then
    warn "Existing pre-push hook is not an Engram hook. Leaving it alone."
  else
    say "No pre-push hook to remove."
  fi
  if [ -f "$COMMIT_MSG_FILE" ] && grep -q "$COMMIT_MSG_MARKER" "$COMMIT_MSG_FILE"; then
    rm -f "$COMMIT_MSG_FILE"
    say "Removed commit-msg hook."
    REMOVED=1
  elif [ -f "$COMMIT_MSG_FILE" ]; then
    warn "Existing commit-msg hook is not an Engram hook. Leaving it alone."
  else
    say "No commit-msg hook to remove."
  fi
  [ "$REMOVED" -eq 0 ] && say "Nothing to do."
  exit 0
fi

# Install path
mkdir -p "$HOOKS_DIR"

# If there's a pre-existing pre-push hook from someone else, back it up and chain.
if [ -f "$HOOK_FILE" ] && ! grep -q "$HOOK_MARKER" "$HOOK_FILE"; then
  BACKUP="$HOOKS_DIR/pre-push.backup-$(date +%Y%m%d-%H%M%S)"
  mv "$HOOK_FILE" "$BACKUP"
  warn "Existing pre-push hook moved to $BACKUP (Engram will call it before itself)."
  EXISTING_HOOK="$BACKUP"
else
  EXISTING_HOOK=""
fi

# Same for commit-msg: back up any existing non-Engram commit-msg hook.
EXISTING_COMMIT_MSG_HOOK=""
if [ -f "$COMMIT_MSG_FILE" ] && ! grep -q "$COMMIT_MSG_MARKER" "$COMMIT_MSG_FILE"; then
  BACKUP_MSG="$HOOKS_DIR/commit-msg.backup-$(date +%Y%m%d-%H%M%S)"
  mv "$COMMIT_MSG_FILE" "$BACKUP_MSG"
  warn "Existing commit-msg hook moved to $BACKUP_MSG (Engram will call it before itself)."
  EXISTING_COMMIT_MSG_HOOK="$BACKUP_MSG"
fi

cat > "$HOOK_FILE" <<EOF
#!/usr/bin/env bash
$HOOK_MARKER
# Auto-generated by scripts/install-engram-hooks.sh
# Stage Engram memory chunks before push. Safe to remove with:
#   ./scripts/install-engram-hooks.sh --uninstall
#
# KEY BEHAVIOR: never amend .engram/ files into a non-chore(engram) commit.
# Doing so causes merge conflicts on .engram/manifest.json every time someone
# syncs, because that file changes on every push.

set -e

# Skip when user opts out
if [ -n "\${ENGRAM_SKIP_PRE_PUSH:-}" ]; then
  exit 0
fi

# Skip when engram is not installed on this machine (e.g. CI, Docker)
if ! command -v engram >/dev/null 2>&1; then
  exit 0
fi

REPO_ROOT="\$(git rev-parse --show-toplevel)"
SYNC_SH="\$REPO_ROOT/scripts/engram-sync.sh"

if [ ! -x "\$SYNC_SH" ]; then
  exit 0
fi

# Run the sync; it stages any new chunks.
"\$SYNC_SH" $QUIET_FLAG || true

# If new chunks were staged, decide whether to amend or create a new commit:
#   - If the last commit is already a chore(engram) commit AND ENGRAM_HOOK_AMEND=1:
#     amend it (typical case: running sync multiple times in a row before pushing).
#   - Otherwise: ALWAYS create a separate chore(engram): sync memories commit
#     to avoid mixing .engram/ files into feature commits.
if [ -n "\$(git diff --cached --name-only -- .engram/ 2>/dev/null)" ]; then
  LAST_MSG="\$(git log -1 --format=%s HEAD 2>/dev/null || echo '')"
  if [ "\${ENGRAM_HOOK_AMEND:-1}" = "1" ] && [[ "\$LAST_MSG" == "chore(engram):"* ]]; then
    git commit --amend --no-edit -- .engram/ >/dev/null 2>&1 || \
      git commit -m "chore(engram): sync memories" -- .engram/ >/dev/null 2>&1 || true
  else
    git commit -m "chore(engram): sync memories" -- .engram/ >/dev/null 2>&1 || true
  fi
fi

exit 0
EOF

chmod +x "$HOOK_FILE"

# --- commit-msg hook (warn-only, the hard guard is in pre-push) ---
cat > "$COMMIT_MSG_FILE" <<EOF
#!/usr/bin/env bash
$COMMIT_MSG_MARKER
# Auto-generated by scripts/install-engram-hooks.sh
# Warn (do NOT abort) if .engram/ files are staged but the commit message is
# not a chore(engram) commit. The hard guard lives in pre-push.

set -e

if [ -n "\${ENGRAM_SKIP_COMMIT_MSG:-}" ]; then
  exit 0
fi

COMMIT_MSG="\$(cat "\$1")"
STAGED_ENGRAM="\$(git diff --cached --name-only -- .engram/ 2>/dev/null || true)"

if [ -n "\$STAGED_ENGRAM" ] && [[ "\$COMMIT_MSG" != "chore(engram):"* ]]; then
  echo ""
  echo "⚠️  WARNING: .engram/ files are staged but commit message is not chore(engram)."
  echo ""
  echo "    Staged .engram/ files:"
  echo "\$STAGED_ENGRAM" | sed 's/^/      /'
  echo ""
  echo "    Mixing .engram/ into feature commits causes merge conflicts on"
  echo "    .engram/manifest.json in PRs (every sync changes it). The pre-push"
  echo "    hook will block this push; unstage .engram/ and commit it separately:"
  echo ""
  echo "      git reset HEAD -- .engram/"
  echo "      git commit -m \"<your original message>\""
  echo "      git add .engram/ && git commit -m \"chore(engram): sync memories\""
  echo ""
  echo "    Bypass with: git commit --no-verify (then split before pushing)."
  echo ""
fi

exit 0
EOF

chmod +x "$COMMIT_MSG_FILE"

# If we backed up existing hooks, append them so the chain keeps working.
if [ -n "$EXISTING_HOOK" ]; then
  {
    echo ""
    echo "# --- existing pre-push hook (chained) ---"
    cat "$EXISTING_HOOK"
  } >> "$HOOK_FILE"
  chmod +x "$HOOK_FILE"
fi
if [ -n "$EXISTING_COMMIT_MSG_HOOK" ]; then
  {
    echo ""
    echo "# --- existing commit-msg hook (chained) ---"
    cat "$EXISTING_COMMIT_MSG_HOOK"
  } >> "$COMMIT_MSG_FILE"
  chmod +x "$COMMIT_MSG_FILE"
fi

say "Installed pre-push hook:   $HOOK_FILE"
say "Installed commit-msg hook: $COMMIT_MSG_FILE"
echo
echo "Behavior:"
echo "  • pre-push runs ./scripts/engram-sync.sh and folds staged .engram/ files"
echo "    into a SEPARATE chore(engram): sync memories commit UNLESS the last"
echo "    commit is already chore(engram) (then it amends)."
echo "  • commit-msg WARNS when .engram/ files are staged in a non-chore(engram)"
echo "    commit but does not abort. The hard guard is in pre-push."
echo
echo "Useful commands:"
echo "  ./scripts/install-engram-hooks.sh --status     # verify both hooks are installed"
echo "  ./scripts/install-engram-hooks.sh --uninstall  # remove both hooks"
echo "  git push --no-verify                           # skip pre-push for one push"
echo "  ENGRAM_SKIP_PRE_PUSH=1 git push                # skip without changing hooks"
echo "  ENGRAM_HOOK_AMEND=0 git push                   # force a separate commit (no amend)"
