import {
  Menu,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  LogOut,
  Plus,
  X,
  Check,
  Search,
  Pencil,
  Trash2,
  Info,
  TriangleAlert,
  User,
  Lock,
  House,
  Building,
  Users,
  Settings,
  TrendingUp,
  CreditCard,
  Headphones,
  RefreshCw,
  Archive,
  Shield,
  CheckCircle,
  Clock,
  UserX,
  MailCheck,
  Eye,
  ShieldCheck,
  Filter,
  Sliders,
  SlidersHorizontal,
  RotateCcw,
  PlusCircle,
  LogIn,
  Database,
  ShoppingCart,
  Store,
  Package,
  Tag,
  Link,
  Globe,
  List,
  FileText,
  HelpCircle,
  LucideIconData,
} from 'lucide-angular';

/**
 * Registry mapping current icon names to Lucide icons
 * This maintains backward compatibility while using Lucide internally
 */
export const ICON_REGISTRY: Record<string, LucideIconData> = {
  // Basic UI icons
  menu: Menu,
  chevron: ChevronDown, // Default chevron points down
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  logout: LogOut,
  plus: Plus,
  close: X,
  check: Check,
  search: Search,
  edit: Pencil,
  delete: Trash2,
  'trash-2': Trash2,
  info: Info,
  warning: TriangleAlert,
  user: User,
  lock: Lock,
  home: House,
  building: Building,
  users: Users,
  settings: Settings,
  'chart-line': TrendingUp,
  'credit-card': CreditCard,
  headset: Headphones,
  refresh: RefreshCw,
  archive: Archive,
  shield: Shield,
  'check-circle': CheckCircle,
  clock: Clock,
  'user-x': UserX,
  'alert-triangle': TriangleAlert,
  'mail-check': MailCheck,
  eye: Eye,
  'shield-check': ShieldCheck,
  filter: Filter,
  sliders: Sliders,
  'sliders-horizontal': SlidersHorizontal,
  'refresh-ccw': RefreshCw,
  'rotate-ccw': RotateCcw,
  'plus-circle': PlusCircle,
  'log-in': LogIn,
  database: Database,
  cart: ShoppingCart,
  store: Store,
  package: Package,
  tag: Tag,
  'link-2': Link,
  'globe-2': Globe,
  list: List,
  'file-text': FileText,

  // Default fallback icon
  default: HelpCircle,
} as const;

export type IconName = keyof typeof ICON_REGISTRY;
