import {
  Menu,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  LogOut,
  Plus,
  X,
  Check,
  Search,
  Pencil,
  Trash2,
  Info,
  TriangleAlert,
  User,
  Lock,
  House,
  Building,
  Users,
  Settings,
  TrendingUp,
  CreditCard,
  Headphones,
  RefreshCw,
  Archive,
  Shield,
  CheckCircle,
  Clock,
  UserX,
  MailCheck,
  Eye,
  ShieldCheck,
  Filter,
  Sliders,
  SlidersHorizontal,
  RotateCcw,
  PlusCircle,
  LogIn,
  Database,
  ShoppingCart,
  Store,
  Package,
  Tag,
  Link,
  Globe,
  List,
  FileText,
  HelpCircle,
  DollarSign,
  BarChart3,
  Warehouse,
  Truck,
  FileCheck,
  HardDrive,
  Megaphone,
  Circle,
  UserPlus,
  UserCheck,
  Barcode,
  Save,
  Star,
  Maximize,
  Minimize,
  ArrowLeft,
  ArrowRight,
  SkipForward,
  Loader2,
  Sparkles,
  Mail,
  Palette,
  CheckSquare,
  Lightbulb,
  LayoutDashboard,
  ShoppingBag,
  Layout,
  MapPin,
  Building2,
  AlignLeft,
  Droplet,
  UserCircle,
  CircleAlert,
  Book,
  Calendar,
  ClipboardList,
  Cog,
  Download,
  Gift,
  Hash,
  Image,
  ImageOff,
  Key,
  Minus,
  Coins,
  Copy,
  FolderOpen,
  GitBranch,
  History,
  Pause,
  Server,
  Unlock,
  UploadCloud,
  LucideIconData,
  Heart,
  ExternalLink,
  Layers,
  ShieldOff,
  CircleX,
  TrendingDown,
  Phone,
  Printer,
  Wallet,
  Edit2,
  Slash,
} from 'lucide-angular';

/**
 * Registry mapping current icon names to Lucide icons
 */
export const ICON_REGISTRY: Record<string, LucideIconData> = {
  // Basic UI icons
  'external-link': ExternalLink,
  menu: Menu,
  chevron: ChevronDown,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  logout: LogOut,
  plus: Plus,
  close: X,
  check: Check,
  search: Search,
  edit: Pencil,
  'edit-2': Edit2,
  delete: Trash2,
  'trash-2': Trash2,
  trash: Trash2,
  info: Info,
  warning: TriangleAlert,
  user: User,
  lock: Lock,
  home: House,
  building: Building,
  users: Users,
  settings: Settings,
  'chart-line': TrendingUp,
  'credit-card': CreditCard,
  headset: Headphones,
  refresh: RefreshCw, // ← solo una vez
  archive: Archive,
  shield: Shield,
  'check-circle': CheckCircle,
  clock: Clock,
  'user-x': UserX,
  'alert-triangle': TriangleAlert,
  'mail-check': MailCheck,
  eye: Eye,
  'shield-check': ShieldCheck,
  filter: Filter,
  sliders: Sliders,
  'sliders-horizontal': SlidersHorizontal,
  'refresh-ccw': RefreshCw,
  'rotate-ccw': RotateCcw,
  'plus-circle': PlusCircle,
  'log-in': LogIn,
  database: Database,
  cart: ShoppingCart,
  store: Store,
  package: Package,
  tag: Tag,
  'link-2': Link,
  'globe-2': Globe,
  list: List,
  'file-text': FileText,

  // Marketing and communication icons
  megaphone: Megaphone,
  bullhorn: Megaphone,

  // UI elements
  circle: Circle,

  // User action icons
  'user-plus': UserPlus,
  'user-check': UserCheck,

  // POS and product icons
  barcode: Barcode,

  // Action icons
  save: Save,
  star: Star,

  // Fullscreen icons
  maximize: Maximize,
  minimize: Minimize,
  'fullscreen-enter': Maximize,
  'fullscreen-exit': Minimize,

  // Financial and business icons
  'dollar-sign': DollarSign,
  'bar-chart': BarChart3,
  warehouse: Warehouse,
  truck: Truck,
  'file-check': FileCheck,
  backup: HardDrive,

  // Default fallback icon
  default: HelpCircle,

  // Onboarding icons
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'skip-forward': SkipForward,
  'loader-2': Loader2,
  sparkles: Sparkles,
  mail: Mail,
  palette: Palette,
  x: X,
  'check-square': CheckSquare,
  globe: Globe,
  lightbulb: Lightbulb,
  'chart-bar': BarChart3,
  'layout-dashboard': LayoutDashboard,
  'shopping-bag': ShoppingBag,
  layout: Layout,
  'refresh-cw': RefreshCw,
  'map-pin': MapPin,
  'building-2': Building2,
  'align-left': AlignLeft,
  droplet: Droplet,
  'help-circle': HelpCircle,
  'user-circle': UserCircle,
  'alert-circle': CircleAlert,
  book: Book,
  calendar: Calendar,
  'clipboard-list': ClipboardList,
  cog: Cog,
  download: Download,
  gift: Gift,
  hash: Hash,
  image: Image,
  'image-off': ImageOff,
  key: Key,
  minus: Minus,
  coins: Coins,
  'folder-open': FolderOpen,
  'git-branch': GitBranch,
  history: History,
  link: Link,
  'log-out': LogOut,
  pause: Pause,
  server: Server,
  'shopping-cart': ShoppingCart,
  'trending-up': TrendingUp,
  unlock: Unlock,
  'upload-cloud': UploadCloud,
  copy: Copy,
  heart: Heart,
  'trending-down': TrendingDown,
  layers: Layers,
  'shield-off': ShieldOff,
  'circle-x': CircleX,
  phone: Phone,
  printer: Printer,
  wallet: Wallet,
  slash: Slash,
} as const;

export type IconName = keyof typeof ICON_REGISTRY;
