import { payments_state_enum } from '@prisma/client';

export interface PaymentData {
  orderId: number;
  customerId?: number;
  amount: number;
  currency: string;
  /**
   * Optional for SaaS subscription path (where there is no per-store payment method
   * resolved up-front and the gateway resolves it itself). Required for store/POS/
   * eCommerce flows that already select a `store_payment_methods` row.
   */
  storePaymentMethodId?: number;
  storeId: number;
  /**
   * Idempotency key for at-least-once retry safety. Provider mapping:
   * - Wompi: HTTP header `Idempotency-Key`
   * - Stripe: SDK option `idempotencyKey`
   * - PayPal: HTTP header `PayPal-Request-Id`
   * - Bank transfer / cash / wallet: no-op (provider has no idempotency primitive)
   *
   * Callers MUST provide a stable key per logical attempt so a retry of the same
   * charge does not double-charge. If empty, the processor falls back to a
   * `crypto.randomUUID()` for back-compat (still safe within a single invocation).
   */
  idempotencyKey: string;
  /**
   * QUI-728 — id de la cuenta bancaria (`bank_accounts.id`) a la que se acredita
   * un pago por transferencia. Lo elige el cajero en el `payment-collector` y
   * viaja en el DTO; el gateway lo valida ANTES de invocar al processor.
   * Únicamente para `bank_transfer`; el resto de métodos lo ignoran.
   */
  bankAccountId?: number;
  /**
   * Cuenta bancaria YA resuelta y validada por el gateway (existe + activa +
   * pertenece a la organización + scope de tienda). Se le pasa al processor como
   * objeto, NO como id, para que no repita la consulta y no confíe en un id
   * sin validar. QUI-728 / ADR-3.
   */
  bankAccount?: ResolvedBankAccount;
  /**
   * Carga OPACA: se persiste en `payments.gateway_response` y se le entrega al
   * processor, que lee de ella lo suyo (Wompi: `paymentMethod`, `wompiConfig`,
   * `customerEmail`, `reference`, `payment_source_id`).
   *
   * INVARIANTE — `metadata` NO decide validación, autorización ni cálculo de
   * dinero. En los endpoints públicos llega desde el body del cliente
   * (`CreatePaymentDto.metadata`, hoy cerrado con `PaymentMetadataDto`), así
   * que cualquier rama del servidor que se bifurque leyendo una llave de aquí
   * es una decisión que toma el llamador, no el servidor. Hubo una:
   * `metadata.is_pos_payment` saltaba la validación de orden y la compuerta
   * anti-sobrepago, y permitía cobrar dos veces la misma orden con solo
   * `store:pos:access`. Si el servidor necesita saber algo del origen, va como
   * campo tipado de primer nivel que él mismo resuelve — el molde de QUI-728
   * con `bankAccountId` / `bankAccount`.
   */
  metadata?: Record<string, any>;
  returnUrl?: string;
  cancelUrl?: string;
}

/**
 * Proyección reducida de `bank_accounts` que viaja al processor y a la UI de
 * selección: `{ id, name, bank_name, account_number }` (+ currency). Nunca debe
 * exponer `current_balance`, `opening_balance`, `chart_account_id` ni
 * `column_mapping` (el saldo bancario no es asunto de una pantalla cuyo único
 * propósito es elegir a qué cuenta pagar). QUI-728.
 *
 * `image_url` es la URL pre-firmada (TTL 300s) calculada en lectura; opcional
 * para no romper callers que aún no propagan el campo. La firma vive en el
 * gateway — el processor solo la lee.
 */
export interface ResolvedBankAccount {
  id: number;
  name: string;
  bank_name: string;
  account_number: string;
  currency: string;
  image_url?: string | null;
}

export interface PaymentResult {
  success: boolean;
  transactionId?: string;
  /**
   * Internal reference generated by Vendix for the gateway transaction
   * (e.g. Wompi `vendix_<storeId>_<orderId>_<ts>`). Persisted in
   * `payments.gateway_reference` so webhooks can match the payment row
   * by `txn.reference` BEFORE the real gateway transaction id is known.
   *
   * Optional because not every processor uses an outbound reference
   * (cash, bank transfer). For Wompi this MUST be set.
   */
  gatewayReference?: string;
  status: payments_state_enum;
  message?: string;
  /**
   * Stable, machine-readable failure code surfaced by processors when the
   * gateway returns a known terminal error that callers must react to
   * (e.g. SaaS billing dunning on revoked card-on-file).
   *
   * Free-form by design: each processor documents its own vocabulary.
   * Wompi values: `PAYMENT_SOURCE_REVOKED`, etc.
   */
  errorCode?: string;
  gatewayResponse?: any;
  nextAction?: {
    type: 'redirect' | '3ds' | 'await' | 'none';
    url?: string;
    data?: any;
  };
}

export interface RefundResult {
  success: boolean;
  refundId?: string;
  amount: number;
  status: 'succeeded' | 'failed' | 'pending';
  message?: string;
  gatewayResponse?: any;
}

export interface PaymentStatus {
  status: payments_state_enum;
  transactionId?: string;
  amount?: number;
  paidAt?: Date;
  gatewayResponse?: any;
}

export interface WebhookEvent {
  processor: string;
  eventType: string;
  data: any;
  signature?: string;
  rawBody?: string;
  storeId?: number;
}

export interface PaymentProcessorConfig {
  enabled: boolean;
  testMode: boolean;
  credentials: Record<string, any>;
  settings: Record<string, any>;
}

export interface OrderValidationResult {
  valid: boolean;
  order?: any;
  errors?: string[];
  warnings?: string[];
}
