import { payments_state_enum } from '@prisma/client';

export interface PaymentData {
  orderId: number;
  customerId?: number;
  amount: number;
  currency: string;
  /**
   * Optional for SaaS subscription path (where there is no per-store payment method
   * resolved up-front and the gateway resolves it itself). Required for store/POS/
   * eCommerce flows that already select a `store_payment_methods` row.
   */
  storePaymentMethodId?: number;
  storeId: number;
  /**
   * Idempotency key for at-least-once retry safety. Provider mapping:
   * - Wompi: HTTP header `Idempotency-Key`
   * - Stripe: SDK option `idempotencyKey`
   * - PayPal: HTTP header `PayPal-Request-Id`
   * - Bank transfer / cash / wallet: no-op (provider has no idempotency primitive)
   *
   * Callers MUST provide a stable key per logical attempt so a retry of the same
   * charge does not double-charge. If empty, the processor falls back to a
   * `crypto.randomUUID()` for back-compat (still safe within a single invocation).
   */
  idempotencyKey: string;
  metadata?: Record<string, any>;
  returnUrl?: string;
  cancelUrl?: string;
}

export interface PaymentResult {
  success: boolean;
  transactionId?: string;
  /**
   * Internal reference generated by Vendix for the gateway transaction
   * (e.g. Wompi `vendix_<storeId>_<orderId>_<ts>`). Persisted in
   * `payments.gateway_reference` so webhooks can match the payment row
   * by `txn.reference` BEFORE the real gateway transaction id is known.
   *
   * Optional because not every processor uses an outbound reference
   * (cash, bank transfer). For Wompi this MUST be set.
   */
  gatewayReference?: string;
  status: payments_state_enum;
  message?: string;
  /**
   * Stable, machine-readable failure code surfaced by processors when the
   * gateway returns a known terminal error that callers must react to
   * (e.g. SaaS billing dunning on revoked card-on-file).
   *
   * Free-form by design: each processor documents its own vocabulary.
   * Wompi values: `PAYMENT_SOURCE_REVOKED`, etc.
   */
  errorCode?: string;
  gatewayResponse?: any;
  nextAction?: {
    type: 'redirect' | '3ds' | 'await' | 'none';
    url?: string;
    data?: any;
  };
}

export interface RefundResult {
  success: boolean;
  refundId?: string;
  amount: number;
  status: 'succeeded' | 'failed' | 'pending';
  message?: string;
  gatewayResponse?: any;
}

export interface PaymentStatus {
  status: payments_state_enum;
  transactionId?: string;
  amount?: number;
  paidAt?: Date;
  gatewayResponse?: any;
}

export interface WebhookEvent {
  processor: string;
  eventType: string;
  data: any;
  signature?: string;
  rawBody?: string;
  storeId?: number;
}

export interface PaymentProcessorConfig {
  enabled: boolean;
  testMode: boolean;
  credentials: Record<string, any>;
  settings: Record<string, any>;
}

export interface OrderValidationResult {
  valid: boolean;
  order?: any;
  errors?: string[];
  warnings?: string[];
}
