import { INestApplication, OnModuleInit } from '@nestjs/common';
import { PrismaClient } from '@prisma/client';
export declare class PrismaService implements OnModuleInit {
    private readonly logger;
    client: any;
    constructor();
    onModuleInit(): Promise<void>;
    enableShutdownHooks(app: INestApplication): Promise<void>;
    get users(): any;
    get organizations(): any;
    get stores(): any;
    get domain_settings(): any;
    get addresses(): any;
    get audit_logs(): any;
    get organization_settings(): any;
    get brands(): any;
    get categories(): any;
    get customers(): any;
    get inventory_movements(): any;
    get inventory_snapshots(): any;
    get inventory_transactions(): any;
    get login_attempts(): any;
    get order_items(): any;
    get order_item_taxes(): any;
    get orders(): any;
    get payment_methods(): any;
    get payments(): any;
    get product_categories(): any;
    get product_images(): any;
    get product_tax_assignments(): any;
    get product_variants(): any;
    get products(): any;
    get refund_items(): any;
    get refunds(): any;
    get reviews(): any;
    get store_settings(): any;
    get user_settings(): any;
    get store_users(): any;
    get tax_categories(): any;
    get tax_rates(): any;
    get taxes(): any;
    get email_verification_tokens(): any;
    get refresh_tokens(): any;
    get roles(): any;
    get user_roles(): any;
    get password_reset_tokens(): any;
    get permissions(): any;
    get role_permissions(): any;
    get inventory_locations(): any;
    get stock_levels(): any;
    get inventory_batches(): any;
    get inventory_serial_numbers(): any;
    get suppliers(): any;
    get supplier_products(): any;
    get inventory_adjustments(): any;
    get stock_reservations(): any;
    get purchase_orders(): any;
    get purchase_order_items(): any;
    get sales_orders(): any;
    get sales_order_items(): any;
    get stock_transfers(): any;
    get stock_transfer_items(): any;
    get return_orders(): any;
    get return_order_items(): any;
    $transaction(...args: any[]): any;
    $connect(): any;
    $disconnect(): any;
    withoutScope(): PrismaClient<import(".prisma/client").Prisma.PrismaClientOptions, never, import("@prisma/client/runtime/library").DefaultArgs>;
}
